export type CrmPriority = "P0" | "P1" | "P2";

export interface CrmComponentDefinition {
  name: string;
  family: string;
  priority: CrmPriority;
}

export const crmComponentRegistry = [
  { name: "CrmProductShell", family: "Shell", priority: "P0" },
  { name: "JourneyShellCanvas", family: "Shell", priority: "P1" },
  { name: "CrmBrowserTrafficLights", family: "Shell / Browser Chrome", priority: "P0" },
  { name: "CrmBrowserToolbarButton", family: "Shell / Browser Chrome", priority: "P0" },
  { name: "CrmBrowserToolbar", family: "Shell / Browser Chrome", priority: "P0" },
  { name: "CrmBrowserAddressBar", family: "Shell / Browser Chrome", priority: "P0" },
  { name: "CrmBrowserChrome", family: "Shell / Browser Chrome", priority: "P0" },
  { name: "CrmShellBrand", family: "Shell / Sidebar", priority: "P0" },
  { name: "CrmSidebarFloatingButton", family: "Shell / Sidebar", priority: "P0" },
  { name: "CrmSidebarNavigation", family: "Shell / Sidebar", priority: "P0" },
  { name: "CrmSidebarUtilityNavigation", family: "Shell / Sidebar", priority: "P0" },
  { name: "CrmShellSidebar", family: "Shell / Sidebar", priority: "P0" },
  { name: "CrmShellBackButton", family: "Shell / Controls", priority: "P0" },
  { name: "CrmTopbarNavChip", family: "Shell / Navigation", priority: "P0" },
  { name: "CrmShellTopNav", family: "Shell / Navigation", priority: "P0" },
  { name: "CrmTopbarActionButton", family: "Shell / Controls", priority: "P0" },
  { name: "CrmShellAvatar", family: "Shell / Controls", priority: "P0" },
  { name: "CrmShellGlobalActions", family: "Shell / Controls", priority: "P0" },
  { name: "CrmEmptyShellTopbar", family: "Shell / Layout", priority: "P0" },
  { name: "CrmEmptyShellPageHeader", family: "Shell / Layout", priority: "P0" },
  { name: "CrmEmptyShellCanvas", family: "Shell / Layout", priority: "P0" },
  { name: "CrmEmptyShellWindow", family: "Shell / Layout", priority: "P0" },
  { name: "CrmEmptyShell", family: "Shell", priority: "P0" },
  { name: "CrmOperationalPanel", family: "Operational", priority: "P0" },
  { name: "CrmOperationalRow", family: "Operational", priority: "P0" },
  { name: "CrmOperationalRows", family: "Operational", priority: "P0" },
  { name: "Sidebar", family: "Shell", priority: "P0" },
  { name: "Topbar", family: "Shell", priority: "P0" },
  { name: "PageHeader", family: "Shell", priority: "P0" },
  { name: "GlobalActions", family: "Shell", priority: "P0" },
  { name: "SidebarItem", family: "Navigation", priority: "P0" },
  { name: "QuotaBadge", family: "Status", priority: "P0" },
  { name: "MetricCard", family: "Surface", priority: "P0" },
  { name: "StatusCard", family: "Surface", priority: "P0" },
  { name: "AgentPanel", family: "Agent", priority: "P0" },
  { name: "SettingsAgentPanel", family: "Agent", priority: "P1" },
  { name: "CopilotSuggestion", family: "Agent", priority: "P0" },
  { name: "AgentStatus", family: "Agent", priority: "P0" },
  { name: "ProductWindowFrame", family: "Layout", priority: "P0" },
  { name: "ListDetailLayout", family: "Layout", priority: "P1" },
  { name: "WorkListDetailPage", family: "Layout", priority: "P1" },
  { name: "CrmPageFamilyShell", family: "Layout", priority: "P1" },
  { name: "CrmWorklistPage", family: "Layout", priority: "P1" },
  { name: "CrmKanbanPage", family: "Layout", priority: "P1" },
  { name: "CrmDashboardPage", family: "Layout", priority: "P1" },
  { name: "CrmThreePanePage", family: "Layout", priority: "P1" },
  { name: "CrmRightPanelPage", family: "Layout", priority: "P1" },
  { name: "PageFilterBar", family: "Layout", priority: "P1" },
  { name: "PageQuickFilters", family: "Layout", priority: "P1" },
  { name: "CrmWorklistTable", family: "Layout", priority: "P1" },
  { name: "CrmDrawer", family: "Operational", priority: "P1" },
  { name: "TaskQueueList", family: "Tasks", priority: "P1" },
  { name: "TaskTable", family: "Tasks", priority: "P1" },
  { name: "LeadTable", family: "Leads", priority: "P1" },
  { name: "CrmRecordDrawer", family: "Operational", priority: "P1" },
  { name: "ChecklistTable", family: "Operational", priority: "P1" },
  { name: "ChecklistDrawer", family: "Operational", priority: "P1" },
  { name: "ApprovalTable", family: "Approvals", priority: "P1" },
  { name: "StudentTable", family: "Students", priority: "P1" },
  { name: "ReplacementTable", family: "Agenda", priority: "P1" },
  { name: "ClassSummaryCard", family: "Agenda", priority: "P1" },
  { name: "ReplacementMatcherPanel", family: "Agenda", priority: "P1" },
  { name: "WaitlistPanel", family: "Agenda", priority: "P1" },
  { name: "ResourceConflictPanel", family: "Agenda", priority: "P1" },
  { name: "DocumentViewerPanel", family: "Documents", priority: "P1" },
  { name: "UploadReceiptPanel", family: "Documents", priority: "P1" },
  { name: "ReconciliationSummaryTable", family: "Finance", priority: "P1" },
  { name: "MoneyInputGroup", family: "Finance", priority: "P1" },
  { name: "FinancialSimulationPanel", family: "Finance", priority: "P1" },
  { name: "FlowSimulationPanel", family: "Agents", priority: "P1" },
  { name: "PublicationPreflightPanel", family: "Agents", priority: "P1" },
  { name: "ExecutionTraceTable", family: "Agents", priority: "P1" },
  { name: "AgentIncidentPanel", family: "Agents", priority: "P1" },
  { name: "EvaluationQualityPanel", family: "Agents", priority: "P1" },
  { name: "PrivacyRequestTable", family: "Governance", priority: "P1" },
  { name: "SupportGrantPanel", family: "Governance", priority: "P1" },
  { name: "AdvancedReportsPanel", family: "Reports", priority: "P1" },
  { name: "ExportQueuePanel", family: "Reports", priority: "P1" },
  { name: "SegmentCommunicationPanel", family: "Reports", priority: "P1" },
  { name: "ThreePaneLayout", family: "Layout", priority: "P1" },
  { name: "ContextPanel", family: "Layout", priority: "P1" },
  { name: "RightPanelLayout", family: "Layout", priority: "P1" },
  { name: "DashboardGrid", family: "Layout", priority: "P1" },
  { name: "ProfileTabs", family: "Tabs", priority: "P1" },
  { name: "ActivityFeed", family: "Timeline", priority: "P1" },
  { name: "OperationActivityTable", family: "Timeline", priority: "P1" },
  { name: "AuditTrail", family: "Timeline", priority: "P1" },
  { name: "KanbanBoard", family: "Kanban", priority: "P1" },
  { name: "KanbanColumn", family: "Kanban", priority: "P1" },
  { name: "KanbanCard", family: "Kanban", priority: "P1" },
  { name: "WeeklyCalendar", family: "Agenda", priority: "P1" },
  { name: "MiniCalendar", family: "Agenda", priority: "P1" },
  { name: "CompactCalendar", family: "Agenda", priority: "P1" },
  { name: "ClassCard", family: "Agenda", priority: "P1" },
  { name: "Roster", family: "Agenda", priority: "P1" },
  { name: "SetupShell", family: "Setup", priority: "P1" },
  { name: "SetupPage", family: "Setup", priority: "P1" },
  { name: "SetupStepper", family: "Setup", priority: "P1" },
  { name: "SetupBlockHeader", family: "Setup", priority: "P1" },
  { name: "SetupContentGrid", family: "Setup", priority: "P1" },
  { name: "SetupBottomBar", family: "Setup", priority: "P1" },
  { name: "SetupWelcome", family: "Setup", priority: "P1" },
  { name: "SetupWelcomeWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupChoiceCard", family: "Setup", priority: "P1" },
  { name: "SetupConsumptionWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupStudioWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupTeamWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupChannelsWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupPlansWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupPaymentWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupStudentsWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupClassesWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupAgendaWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupReviewWorkspace", family: "Setup", priority: "P1" },
  { name: "SetupImportSourceCard", family: "Setup", priority: "P1" },
  { name: "SetupReviewPanel", family: "Setup", priority: "P1" },
  { name: "SetupAgentChat", family: "Setup", priority: "P1" },
  { name: "SetupHumanHelpCTA", family: "Setup", priority: "P1" },
  { name: "AccessShell", family: "Access", priority: "P1" },
  { name: "AuthCard", family: "Access", priority: "P1" },
  { name: "AccessFooterLinks", family: "Access", priority: "P1" },
  { name: "CheckoutPaymentCard", family: "Subscription", priority: "P1" },
  { name: "CheckoutReviewPanel", family: "Subscription", priority: "P1" },
  { name: "SubscriptionStatusCard", family: "Subscription", priority: "P1" },
  { name: "SubscriptionProgressStepper", family: "Subscription", priority: "P1" },
  { name: "SubscriptionResolutionPanel", family: "Subscription", priority: "P1" },
  { name: "SubscriptionResultHeader", family: "Subscription", priority: "P1" },
  { name: "ConfirmedSetupHandoff", family: "Subscription", priority: "P1" },
  { name: "PlanSummaryCard", family: "Billing", priority: "P1" },
  { name: "BillingAddOnsWorkspace", family: "Billing", priority: "P1" },
  { name: "BillingInvoicesWorkspace", family: "Billing", priority: "P1" },
  { name: "BillingSubscriptionWorkspace", family: "Billing", priority: "P1" },
  { name: "InvoiceTable", family: "Billing", priority: "P1" },
  { name: "AddOnCard", family: "Billing", priority: "P1" },
  { name: "QuotaProgress", family: "Usage", priority: "P1" },
  { name: "UsageOverviewWorkspace", family: "Usage", priority: "P1" },
  { name: "CrmHeaderSummary", family: "Shell", priority: "P1" },
  { name: "UsageLedgerTable", family: "Usage", priority: "P1" },
  { name: "ApprovalPanel", family: "Approvals", priority: "P1" },
  { name: "ImpactSummary", family: "Approvals", priority: "P1" },
  { name: "BeforeAfterDiff", family: "Approvals", priority: "P1" },
  { name: "SettingsSection", family: "Forms", priority: "P1" },
  { name: "PermissionMatrix", family: "Forms", priority: "P1" },
  { name: "PermissionRoleCard", family: "Forms", priority: "P1" },
  { name: "RuleRow", family: "Forms", priority: "P1" },
  { name: "SettingsHubCard", family: "Config", priority: "P1" },
  { name: "IntegrationStatusRow", family: "Config", priority: "P1" },
  { name: "UnsavedChangesBar", family: "Config", priority: "P1" },
  { name: "ConfigImpactPreview", family: "Config", priority: "P1" },
  { name: "SettingsPermissionsWorkspace", family: "Config", priority: "P1" },
  { name: "SettingsStudioWorkspace", family: "Config", priority: "P1" },
  { name: "SettingsTeamWorkspace", family: "Config", priority: "P1" },
  { name: "SettingsChannelsWorkspace", family: "Config", priority: "P1" },
  { name: "SettingsPlansWorkspace", family: "Config", priority: "P1" },
  { name: "SettingsPaymentsWorkspace", family: "Config", priority: "P1" },
  { name: "SettingsAgendaWorkspace", family: "Config", priority: "P1" },
  { name: "SettingsNotificationsWorkspace", family: "Config", priority: "P1" },
  { name: "ConversationList", family: "Inbox", priority: "P1" },
  { name: "ConversationThread", family: "Inbox", priority: "P1" },
  { name: "MessageBubble", family: "Inbox", priority: "P1" },
  { name: "Composer", family: "Inbox", priority: "P1" },
  { name: "ComposerPanel", family: "Inbox", priority: "P1" },
  { name: "ChannelStatus", family: "Inbox", priority: "P1" },
  { name: "ChannelStatusPanel", family: "Inbox", priority: "P1" },
  { name: "CopilotPanel", family: "Inbox", priority: "P1" },
  { name: "HandoffBanner", family: "Inbox", priority: "P1" },
  { name: "QuickReplyChips", family: "Inbox", priority: "P1" },
  { name: "ChecklistRow", family: "Operational", priority: "P1" },
  { name: "CommentThread", family: "Operational", priority: "P1" },
  { name: "TaskDrawer", family: "Operational", priority: "P1" },
  { name: "ApprovalDrawer", family: "Operational", priority: "P1" },
  { name: "CaseDrawer", family: "Operational", priority: "P1" },
  { name: "StudentDrawer", family: "Operational", priority: "P1" },
  { name: "ClassDrawer", family: "Operational", priority: "P1" },
  { name: "ClassOperationalDetail", family: "Operational", priority: "P1" },
  { name: "PaymentDrawer", family: "Operational", priority: "P1" },
  { name: "ReplacementDrawer", family: "Operational", priority: "P1" },
  { name: "LeadDrawer", family: "Operational", priority: "P1" },
  { name: "AgentFlowDrawer", family: "Operational", priority: "P1" },
  { name: "UsageDrawer", family: "Operational", priority: "P1" },
  { name: "SupportStatusSidebar", family: "Support", priority: "P1" },
  { name: "SupportAgentPanel", family: "Support", priority: "P1" },
  { name: "SupportCentralWorkspace", family: "Support", priority: "P1" },
  { name: "SupportTicketDrawer", family: "Operational", priority: "P1" },
  { name: "TenantSecurityDrawer", family: "Operational", priority: "P1" },
  { name: "TenantSummaryDrawer", family: "Operational", priority: "P1" },
  { name: "WeeklyHoursGrid", family: "Setup", priority: "P1" },
  { name: "RoleCard", family: "Setup", priority: "P1" },
  { name: "InviteRow", family: "Setup", priority: "P1" },
  { name: "PaymentMethodRow", family: "Subscription", priority: "P1" },
  { name: "SecurePaymentNotice", family: "Subscription", priority: "P1" },
  { name: "UsageOriginRow", family: "Usage", priority: "P1" },
  { name: "ExportAction", family: "Reports", priority: "P1" },
  { name: "AgentCatalog", family: "Agents", priority: "P2" },
  { name: "AgentCard", family: "Agents", priority: "P2" },
  { name: "AgentRoutineIntro", family: "Agents", priority: "P2" },
  { name: "AgentRoutineCard", family: "Agents", priority: "P2" },
  { name: "AgentRoutineWorkspace", family: "Agents", priority: "P2" },
  { name: "AgentFlowWorkspace", family: "Agents", priority: "P2" },
  { name: "AgentFlowSectionPanel", family: "Agents", priority: "P2" },
  { name: "AgentFlowSettingsPanel", family: "Agents", priority: "P2" },
  { name: "AgentFlowActionBar", family: "Agents", priority: "P2" },
  { name: "AgentRoutineFlowCard", family: "Agents", priority: "P2" },
  { name: "AgentPublishRoutineWorkspace", family: "Agents", priority: "P2" },
  { name: "AgentPublishFlowCard", family: "Agents", priority: "P2" },
  { name: "ModeSelector", family: "Agents", priority: "P2" },
  { name: "FlowBuilder", family: "Agents", priority: "P2" },
  { name: "PreflightChecklist", family: "Agents", priority: "P2" },
  { name: "SimulationRunner", family: "Agents", priority: "P2" },
  { name: "ExecutionReceipt", family: "Agents", priority: "P2" },
  { name: "ModeCard", family: "Agents", priority: "P2" },
  { name: "FlowStepCard", family: "Agents", priority: "P2" },
  { name: "ScenarioList", family: "Agents", priority: "P2" },
  { name: "PhonePreview", family: "Agents", priority: "P2" },
  { name: "ExecutionTimeline", family: "Agents", priority: "P2" },
  { name: "StudentHeader", family: "Students", priority: "P2" },
  { name: "StudentSummary", family: "Students", priority: "P2" },
  { name: "RelationshipList", family: "Students", priority: "P2" },
  { name: "FinancePriorityPanel", family: "Financeiro", priority: "P2" },
  { name: "PaymentCaseCard", family: "Financeiro", priority: "P2" },
  { name: "FinanceKanbanCard", family: "Financeiro", priority: "P2" },
  { name: "ReconciliationRow", family: "Financeiro", priority: "P2" },
  { name: "PipelineCard", family: "Vendas", priority: "P2" },
  { name: "LeadSummary", family: "Vendas", priority: "P2" },
  { name: "TrialClassCard", family: "Vendas", priority: "P2" },
  { name: "EnrollmentChecklist", family: "Vendas", priority: "P2" },
  { name: "RiskCard", family: "Retencao", priority: "P2" },
  { name: "CancellationCase", family: "Retencao", priority: "P2" },
  { name: "ReactivationCard", family: "Retencao", priority: "P2" },
  { name: "ComplaintPanel", family: "Retencao", priority: "P2" },
  { name: "SensitiveActionDialog", family: "Retencao", priority: "P2" },
  { name: "SupportTicketPanel", family: "Support", priority: "P2" },
  { name: "GrantAccessPanel", family: "Support", priority: "P2" },
  { name: "TenantCard", family: "Internal", priority: "P2" },
  { name: "InternalOverviewDashboard", family: "Internal", priority: "P2" },
  { name: "InternalShell", family: "Internal", priority: "P2" },
  { name: "InternalWorklistPage", family: "Internal", priority: "P2" },
  { name: "TenantDetailLayout", family: "Internal", priority: "P2" },
  { name: "SecurityRulePanel", family: "Internal", priority: "P2" },
  { name: "ChartPanel", family: "Reports", priority: "P2" },
  { name: "ReportFilterBar", family: "Reports", priority: "P2" },
  { name: "OpportunityGroupCard", family: "Reports", priority: "P2" },
  { name: "OpportunityPanel", family: "Reports", priority: "P2" },
  { name: "ImportProgress", family: "Data Quality", priority: "P2" },
  { name: "FieldMappingTable", family: "Data Quality", priority: "P2" },
  { name: "DuplicateResolver", family: "Data Quality", priority: "P2" },
  { name: "PermissionState", family: "Advanced States", priority: "P2" },
  { name: "PlanBlockedState", family: "Advanced States", priority: "P2" },
  { name: "QuotaBlockedState", family: "Advanced States", priority: "P2" },
  { name: "IntegrationFailedState", family: "Advanced States", priority: "P2" },
  { name: "PlanAgentsPanel", family: "Governance", priority: "P2" },
  { name: "FallbackControlCard", family: "Governance", priority: "P2" },
  { name: "BillingGovernancePanel", family: "Governance", priority: "P2" },
  { name: "GovernanceAuditPanel", family: "Governance", priority: "P2" },
  { name: "GuardrailPolicyPanel", family: "Governance", priority: "P2" },
  { name: "GeneralSettingsPanel", family: "Governance", priority: "P2" },
  { name: "SetupWizardPanel", family: "Setup", priority: "P2" },
  { name: "ActivationChecklistPanel", family: "Setup", priority: "P2" },
  { name: "DataConflictQueue", family: "Data Quality", priority: "P2" },
  { name: "ProfileTabsPanel", family: "Students", priority: "P2" },
  { name: "ConsentPreferencesPanel", family: "Students", priority: "P2" },
  { name: "SensitiveTimelinePanel", family: "Students", priority: "P2" }
] as const satisfies readonly CrmComponentDefinition[];

export const crmComponentNames = crmComponentRegistry.map((component) => component.name);

export type CrmComponentName = (typeof crmComponentRegistry)[number]["name"];
