import type { TokenRecord } from "./types.js";

export const chartTokens = {
  "chart.blue": "#5E8EE8",
  "chart.green": "#16A34A",
  "chart.red": "#EF4444",
  "chart.orange": "#F59E0B",
  "chart.purple": "#8B5CF6",
  "chart.grid": "rgba(16, 20, 26, 0.08)",
  "chart.axis": "rgba(16, 20, 26, 0.42)",
  "chart.heatmap.1": "rgba(94, 142, 232, 0.16)",
  "chart.heatmap.2": "rgba(94, 142, 232, 0.28)",
  "chart.heatmap.3": "rgba(94, 142, 232, 0.44)",
  "chart.heatmap.4": "rgba(94, 142, 232, 0.62)",
  "chart.series.1": "#5E8EE8",
  "chart.series.2": "#16A34A",
  "chart.series.3": "#F59E0B",
  "chart.series.4": "#8B5CF6",
  "chart.series.5": "#20B8C7",
  "chart.panel.min-height": "190px",
  "chart.panel.padding": "16px",
  "chart.panel.gap": "14px",
  "chart.panel.header-gap": "12px",
  "chart.panel.header-text-gap": "3px",
  "chart.line.height": "120px",
  "chart.line.grid-stroke-width": "1",
  "chart.line.series-stroke-width": "3",
  "chart.bar.gap": "8px",
  "chart.bar.min-column": "14px",
  "chart.bar.group-height": "122px",
  "chart.bar.min-height": "18px",
  "chart.bar.radius": "4px",
  "chart.funnel.gap": "8px",
  "chart.funnel.item.height": "28px",
  "chart.funnel.item.padding-x": "10px",
  "chart.ranking.gap": "9px",
  "chart.ranking.columns": "72px minmax(0, 1fr) 34px",
  "chart.ranking.bar.height": "3px",
  "chart.heatmap.gap": "5px",
  "chart.heatmap.cell.size": "18px",
  "chart.heatmap.cell.radius": "4px",
  "chart.state.min-height": "120px"
} as const satisfies TokenRecord;

