import type { TokenRecord } from "./types.js";

export const colorTokens = {
  "color.text.primary": "#10141A",
  "color.text.secondary": "rgba(16, 20, 26, 0.66)",
  "color.text.secondary-strong": "rgba(16, 20, 26, 0.68)",
  "color.text.body": "rgba(16, 20, 26, 0.72)",
  "color.text.tertiary": "rgba(16, 20, 26, 0.56)",
  "color.text.hint": "rgba(16, 20, 26, 0.36)",
  "color.text.strong": "rgba(16, 20, 26, 0.92)",
  "color.text.muted": "rgba(16, 20, 26, 0.44)",
  "color.text.disabled": "rgba(16, 20, 26, 0.30)",
  "color.text.inverse": "#FFFFFF",
  "color.logo-dot.start": "#2E72FF",
  "color.logo-dot.end": "#1F61FF",
  "color.accent.info": "#5E8EE8",
  "color.accent.danger": "#EF4444",
  "color.accent.success": "#16A34A",
  "color.accent.warning": "#F59E0B",
  "color.accent.category-purple": "#8B5CF6",
  "color.accent.category-cyan": "#20B8C7",
  "color.crm-empty-shell.stage-bg":
    "radial-gradient(circle at 50% 31%, rgba(255, 255, 255, 0.40), rgba(255, 255, 255, 0) 355px), linear-gradient(135deg, #C1C3C8 0%, #E3E3E6 44%, #D0D1D5 68%, #AEB0B7 100%)",
  "color.crm-empty-shell.image-79.stage-bg": "#A8A9AD",
  "color.crm-empty-shell.image-79.frame-border": "#ECEBEF",
  "color.crm-empty-shell.frame-bg": "rgba(246, 245, 249, 0.96)",
  "color.crm-empty-shell.frame-border": "var(--taliya-surface-segmented)",
  "color.crm-browser.chrome-bg": "linear-gradient(180deg, #FBFBFD, #F4F4F8)",
  "color.crm-browser.foreground": "#11141A",
  "color.crm-browser.muted": "rgba(16, 20, 26, 0.28)",
  "color.crm-browser.address-bg": "rgba(255, 255, 255, 0.74)",
  "color.crm-browser.address-border": "var(--taliya-surface-disabled)",
  "color.crm-browser.address-icon": "var(--taliya-color-text-secondary)",
  "color.crm-browser.traffic-red": "#ED5653",
  "color.crm-browser.traffic-gray": "#9FA1A1",
  "color.crm-browser.traffic-green": "#21C15A",
  "color.crm-access-shell.page-bg": "var(--taliya-surface-app)",
  "color.crm-access-shell.brandbar-bg": "var(--taliya-surface-panel)",
  "color.crm-access-shell.content-bg": "var(--taliya-surface-card)",
  "color.crm-access-shell.centered-main-bg": "var(--taliya-surface-app)",
  "color.crm-access-shell.footer-bg": "var(--taliya-surface-panel)",
  "color.crm-access-shell.panel-bg": "var(--taliya-surface-card)",
  "color.crm-access-shell.panel-border": "var(--taliya-border-default)",
  "color.crm-access-shell.placeholder-border": "rgba(113, 122, 138, 0.24)",
  "color.crm-access-shell.rule": "var(--taliya-border-default)",
  "color.crm-access-shell.traffic-yellow": "#F4B935",
  "color.crm-access-shell.browser-address-fg": "rgba(16, 20, 26, 0.72)",
  "color.crm-empty-shell.body-bg": "rgba(242, 241, 247, 0.88)",
  "color.crm-empty-shell.sidebar-bg": "rgba(250, 250, 252, 0.58)",
  "color.crm-empty-shell.main-bg": "rgba(244, 243, 248, 0.78)",
  "color.crm-empty-shell.title": "#0C0D0F",
  "color.crm-empty-shell.divider": "rgba(16, 20, 26, 0.05)",
  "color.crm-empty-shell.canvas-bg": "rgba(240, 239, 245, 0.50)",
  "color.crm-empty-shell.image-79.body-bg": "#EBEAEF",
  "color.crm-empty-shell.image-79.sidebar-bg": "#EBEBEF",
  "color.crm-empty-shell.image-79.main-bg": "#ECEBEF",
  "color.crm-empty-shell.image-79.canvas-bg": "#EBEAEF",
  "color.crm-role-card.bg": "rgba(247, 250, 255, 0.92)",
  "color.crm-role-card.border": "#C4D8FA",
  "color.crm-role-card.hover-bg": "rgba(239, 246, 255, 0.95)",
  "color.crm-role-card.muted": "#2F3A56",
  "color.crm-invite-row.bg": "var(--taliya-surface-card)",
  "color.crm-invite-row.hover-bg": "rgba(46, 114, 255, 0.035)",
  "color.crm-invite-row.border": "var(--taliya-border-default)",
  "color.crm-invite-row.text": "var(--taliya-color-text-primary)",
  "color.crm-invite-row.muted": "#25324B",
  "color.crm-invite-row.prepared": "#1F66E5",
  "color.crm-invite-row.warning": "var(--taliya-color-accent-warning)",
  "color.crm-invite-row.success": "#0F9A4A",
  "color.crm-invite-row.danger": "#B94444",
  "color.crm-invite-row.disabled": "rgba(46, 57, 83, 0.48)",
  "color.crm-payment-method-row.bg": "var(--taliya-surface-card)",
  "color.crm-payment-method-row.selected-border": "#0D6BFF",
  "color.crm-payment-method-row.border": "#DCE5F4",
  "color.crm-payment-method-row.hover-bg": "rgba(46, 114, 255, 0.035)",
  "color.crm-payment-method-row.title": "var(--taliya-color-text-primary)",
  "color.crm-payment-method-row.text": "#25324B",
  "color.crm-payment-method-row.pix": "#16C7B2",
  "color.crm-payment-method-row.cash": "#58C56C",
  "color.crm-payment-method-row.card": "#1F66E5",
  "color.crm-payment-method-row.check-bg": "#0D6BFF",
  "color.crm-payment-method-row.check-fg": "var(--taliya-color-text-inverse)",
  "color.crm-payment-method-row.failed": "var(--taliya-color-accent-danger)",
  "color.crm-payment-method-row.disabled": "rgba(46, 57, 83, 0.48)",
  "color.crm-usage-origin-row.bg": "transparent",
  "color.crm-usage-origin-row.hover-bg": "rgba(0, 92, 255, 0.035)",
  "color.crm-usage-origin-row.selected-bg": "rgba(0, 92, 255, 0.055)",
  "color.crm-usage-origin-row.text": "var(--taliya-color-text-primary)",
  "color.crm-usage-origin-row.muted": "#25324B",
  "color.crm-usage-origin-row.icon-bg": "#EEF5FF",
  "color.crm-usage-origin-row.icon-fg": "#005CFF",
  "color.crm-usage-origin-row.track": "#DFE4EC",
  "color.crm-usage-origin-row.fill": "#005CFF",
  "color.crm-usage-origin-row.disabled": "rgba(46, 57, 83, 0.48)",
  "color.crm-export-action.bg": "var(--taliya-surface-card)",
  "color.crm-export-action.hover-bg": "var(--taliya-surface-field-disabled)",
  "color.crm-export-action.border": "var(--taliya-border-default)",
  "color.crm-export-action.text": "var(--taliya-color-text-primary)",
  "color.crm-export-action.icon": "var(--taliya-color-text-primary)",
  "color.crm-export-action.disabled": "rgba(46, 57, 83, 0.48)",
  "color.crm-export-action.menu-bg": "var(--taliya-surface-card)",
  "color.crm-export-action.menu-border": "var(--taliya-border-default)",
  "color.crm-export-action.menu-hover": "rgba(0, 92, 255, 0.055)",
  "color.crm-phone-preview.whatsapp-bg": "#F3EEE6",
  "color.crm-phone-preview.wallpaper-mark": "rgba(16, 20, 26, 0.035)",
  "color.crm-phone-preview.header-bg": "linear-gradient(135deg, #00694F 0%, #063D36 100%)",
  "color.crm-phone-preview.outbound-bg": "#E0FBDC",
  "color.crm-phone-preview.outbound-border": "rgba(22, 163, 74, 0.20)",
  "color.crm-phone-preview.receipt-bg": "#E8FBEE",
  "color.crm-phone-preview.receipt-icon-bg": "#0B6B52",
  "color.crm-phone-preview.send-bg": "#050505",
  "color.crm-relationship-marker.bg": "var(--taliya-color-accent-info)",
  "color.crm-profile-tabs.text": "#25385F",
  "color.crm-activity-feed.text": "var(--taliya-color-text-primary)",
  "color.crm-activity-feed.muted": "#25385F",
  "color.crm-activity-feed.line": "#DFE6F1",
  "color.crm-activity-feed.row-border": "var(--taliya-border-default)",
  "color.crm-activity-feed.row-hover": "var(--taliya-surface-field-disabled)",
  "color.crm-activity-feed.blue": "#1473FF",
  "color.crm-activity-feed.green": "#12B84A",
  "color.crm-activity-feed.orange": "#FF7A12",
  "color.crm-activity-feed.purple": "#8B42FF",
  "color.crm-activity-feed.red": "#FF1717",
  "color.crm-audit-trail.bg": "var(--taliya-surface-card)",
  "color.crm-audit-trail.title": "var(--taliya-color-text-primary)",
  "color.crm-audit-trail.text": "#344056",
  "color.crm-audit-trail.muted": "#566278",
  "color.crm-audit-trail.border": "var(--taliya-border-subtle)",
  "color.crm-audit-trail.table-border": "var(--taliya-surface-field-disabled)",
  "color.crm-audit-trail.row-hover": "var(--taliya-surface-field-disabled)",
  "color.crm-audit-trail.success-bg": "#DFF7E8",
  "color.crm-audit-trail.success-fg": "#0F9A4A",
  "color.crm-audit-trail.alert-bg": "#FBEDE8",
  "color.crm-audit-trail.alert-fg": "#E65F00",
  "color.crm-audit-trail.denied-bg": "rgba(239, 68, 68, 0.12)",
  "color.crm-audit-trail.denied-fg": "#B94444",
  "color.crm-audit-trail.link": "#52617E",
  "color.crm-kanban-board.bg": "transparent",
  "color.crm-kanban-rail.bg": "rgba(248, 249, 252, 0.82)",
  "color.crm-kanban-column.bg": "rgba(248, 249, 252, 0.76)",
  "color.crm-kanban-column.border": "var(--taliya-border-subtle)",
  "color.crm-kanban-column.count-bg": "rgba(230, 233, 239, 0.92)",
  "color.crm-kanban-column.count-fg": "#52617E",
  "color.crm-kanban-column.empty-bg": "var(--taliya-surface-segmented)",
  "color.crm-kanban-column.empty-border": "var(--taliya-border-subtle)",
  "color.crm-kanban-column.empty-text": "#7A8497",
  "color.crm-kanban-card.bg": "var(--taliya-surface-card)",
  "color.crm-kanban-card.border": "var(--taliya-border-default)",
  "color.crm-kanban-title": "var(--taliya-color-text-primary)",
  "color.crm-kanban-text": "#25324B",
  "color.crm-kanban-muted": "#52617E",
  "color.crm-kanban-quick-filter.bg": "var(--taliya-surface-card)",
  "color.crm-kanban-quick-filter.hover": "rgba(94, 142, 232, 0.07)",
  "color.crm-kanban-quick-filter.border": "var(--taliya-border-subtle)",
  "color.crm-page-quick-filter.selected-soft-bg": "var(--taliya-color-crm-kanban-manual-bg)",
  "color.crm-page-quick-filter.selected-soft-border": "rgba(94, 142, 232, 0.18)",
  "color.crm-page-quick-filter.selected-soft-fg": "var(--taliya-color-crm-kanban-manual-fg)",
  "color.crm-kanban-manual.bg": "#EAF3FF",
  "color.crm-kanban-manual.fg": "#005CFF",
  "color.crm-kanban-blocked.bg": "#FFE6E6",
  "color.crm-kanban-blocked.fg": "#FF2B31",
  "color.crm-kanban-waiting.bg": "var(--taliya-status-warning-waiting-bg)",
  "color.crm-kanban-waiting.fg": "#E65F00",
  "color.crm-kanban-suggested.bg": "#F1E7FF",
  "color.crm-kanban-suggested.fg": "#6D42D8",
  "color.crm-kanban-resolved.bg": "#DFF7E8",
  "color.crm-kanban-resolved.fg": "#0F9A4A",
  "color.crm-kanban-quota.bg": "#EAF3FF",
  "color.crm-kanban-quota.fg": "#005CFF",
  "color.crm-class-card.bg": "var(--taliya-surface-card)",
  "color.crm-class-card.border": "var(--taliya-border-default)",
  "color.crm-class-card.text": "var(--taliya-color-text-primary)",
  "color.crm-class-card.meta": "#52617E",
  "color.crm-class-card.time": "#25385F",
  "color.crm-class-card.capacity": "#25324B",
  "color.crm-class-card.selected": "#1473FF",
  "color.crm-class-card.success-bg": "#DFF7E8",
  "color.crm-class-card.success-fg": "#0F9A4A",
  "color.crm-class-card.danger-bg": "#FFE6E6",
  "color.crm-class-card.danger-fg": "#FF2B31",
  "color.crm-class-card.warning-bg": "#FFF0DC",
  "color.crm-class-card.warning-fg": "#E65F00",
  "color.crm-class-card.purple-bg": "#F1E7FF",
  "color.crm-class-card.purple-fg": "#6D42D8",
  "color.crm-roster.bg": "var(--taliya-surface-card)",
  "color.crm-roster.border": "rgba(47, 62, 99, 0.12)",
  "color.crm-roster.hover-bg": "var(--taliya-surface-control-hover-faint)",
  "color.crm-roster.focus-bg": "rgba(46, 114, 255, 0.035)",
  "color.crm-roster.text": "var(--taliya-color-text-primary)",
  "color.crm-roster.muted": "#56637D",
  "color.crm-roster-pending.bg": "#F2F3F7",
  "color.crm-roster-pending.avatar-bg": "#EEE8FF",
  "color.crm-roster-pending.fg": "#60677C",
  "color.crm-roster-success.bg": "#DCF7E7",
  "color.crm-roster-success.fg": "#14904D",
  "color.crm-roster-warning.bg": "#FFF1E7",
  "color.crm-roster-warning.fg": "#FF6F16",
  "color.crm-roster-danger.bg": "#FFE5E8",
  "color.crm-roster-danger.fg": "#FF1F2D",
  "color.crm-roster-info.bg": "#EEE8FF",
  "color.crm-roster-info.fg": "#5F3EE7",
  "color.crm-roster-action.bg": "var(--taliya-surface-card)",
  "color.crm-roster-action.border": "var(--taliya-border-subtle)",
  "color.crm-roster-action.fg": "var(--taliya-color-text-primary)",
  "color.crm-roster-action.hover-bg": "var(--taliya-surface-field-disabled)",
  "color.crm-class-drawer.bg": "var(--taliya-surface-product-drawer)",
  "color.crm-class-drawer.edge": "rgba(16, 20, 26, 0.08)",
  "color.crm-class-drawer.rule": "rgba(16, 20, 26, 0.08)",
  "color.crm-class-drawer.text": "var(--taliya-color-text-primary)",
  "color.crm-class-drawer.muted": "#56637D",
  "color.crm-class-drawer.pending-bg": "#F2F3F7",
  "color.crm-class-drawer.pending-fg": "#60677C",
  "color.crm-class-drawer.success-bg": "#DCF7E7",
  "color.crm-class-drawer.success-fg": "#14904D",
  "color.crm-class-drawer.warning-bg": "#FFF1E7",
  "color.crm-class-drawer.warning-fg": "#FF6F16",
  "color.crm-class-drawer.danger-bg": "#FFE5E8",
  "color.crm-class-drawer.danger-fg": "#FF1F2D",
  "color.crm-class-drawer.info-bg": "#EEE8FF",
  "color.crm-class-drawer.info-fg": "#5F3EE7",
  "color.crm-class-drawer.copilot-bg": "#F4F0FF",
  "color.crm-class-drawer.focus": "rgba(46, 114, 255, 0.28)",
  "color.crm-lead-drawer.bg": "var(--taliya-surface-card)",
  "color.crm-lead-drawer.edge": "rgba(16, 20, 26, 0.08)",
  "color.crm-lead-drawer.rule": "rgba(16, 20, 26, 0.08)",
  "color.crm-lead-drawer.text": "var(--taliya-color-text-primary)",
  "color.crm-lead-drawer.muted": "#56637D",
  "color.crm-lead-drawer.info-bg": "#EAF3FF",
  "color.crm-lead-drawer.info-fg": "#0D6BFF",
  "color.crm-lead-drawer.warning-bg": "#FFF1E7",
  "color.crm-lead-drawer.warning-fg": "#FF6F16",
  "color.crm-lead-drawer.danger-bg": "#FFE5E8",
  "color.crm-lead-drawer.danger-fg": "#FF1F2D",
  "color.crm-lead-drawer.success-fg": "#12B84A",
  "color.crm-lead-drawer.suggestion-bg": "#F4F0FF",
  "color.crm-lead-drawer.safe-bg": "var(--taliya-status-warning-safe-bg)",
  "color.crm-lead-drawer.focus": "rgba(46, 114, 255, 0.28)",
  "color.crm-usage-drawer.bg": "var(--taliya-surface-card)",
  "color.crm-usage-drawer.edge": "rgba(16, 20, 26, 0.08)",
  "color.crm-usage-drawer.text": "var(--taliya-color-text-primary)",
  "color.crm-usage-drawer.muted": "#56637D",
  "color.crm-usage-drawer.info-bg": "#F4F8FF",
  "color.crm-usage-drawer.info-border": "#D5E5FF",
  "color.crm-usage-drawer.info-fg": "#0D6BFF",
  "color.crm-usage-drawer.question-bg": "var(--taliya-surface-card)",
  "color.crm-usage-drawer.question-border": "var(--taliya-border-default)",
  "color.crm-usage-drawer.question-hover": "rgba(13, 107, 255, 0.055)",
  "color.crm-usage-drawer.composer-border": "rgba(16, 20, 26, 0.12)",
  "color.crm-usage-drawer.send-bg": "var(--taliya-raw-black-950)",
  "color.crm-usage-drawer.send-fg": "var(--taliya-surface-card)",
  "color.crm-usage-drawer.presence": "#12B84A",
  "color.crm-usage-drawer.focus": "rgba(13, 107, 255, 0.28)",
  "color.crm-payment-drawer.bg": "var(--taliya-surface-product-drawer)",
  "color.crm-payment-drawer.edge": "var(--taliya-color-crm-task-drawer-edge)",
  "color.crm-payment-drawer.text": "var(--taliya-color-text-primary)",
  "color.crm-payment-drawer.muted": "var(--taliya-color-crm-task-drawer-muted)",
  "color.crm-payment-drawer.info-bg": "var(--taliya-color-crm-replacement-drawer-info-bg)",
  "color.crm-payment-drawer.info-fg": "var(--taliya-color-crm-replacement-drawer-info-fg)",
  "color.crm-payment-drawer.danger-bg": "var(--taliya-status-danger-bg)",
  "color.crm-payment-drawer.danger-fg": "var(--taliya-status-danger-fg)",
  "color.crm-payment-drawer.success-fg": "var(--taliya-status-success-fg)",
  "color.crm-payment-drawer.copilot-bg": "var(--taliya-color-crm-conversation-thread-suggestion-bg)",
  "color.crm-payment-drawer.focus": "var(--taliya-color-crm-task-drawer-focus)",
  "color.crm-student-drawer.bg": "var(--taliya-surface-product-drawer)",
  "color.crm-student-drawer.edge": "rgba(16, 20, 26, 0.08)",
  "color.crm-student-drawer.rule": "rgba(16, 20, 26, 0.07)",
  "color.crm-student-drawer.text": "var(--taliya-color-text-primary)",
  "color.crm-student-drawer.muted": "#56637D",
  "color.crm-student-drawer.chip-success-bg": "#DCF7E7",
  "color.crm-student-drawer.chip-success-fg": "#14904D",
  "color.crm-student-drawer.chip-warning-bg": "#FFF1E7",
  "color.crm-student-drawer.chip-warning-fg": "#FF6F16",
  "color.crm-student-drawer.chip-info-bg": "#EEE8FF",
  "color.crm-student-drawer.chip-info-fg": "#5F3EE7",
  "color.crm-student-drawer.dot-warning": "#FF7A12",
  "color.crm-student-drawer.focus": "rgba(46, 114, 255, 0.28)",
  "color.crm-setup-shell.bg": "#F8FAFD",
  "color.crm-setup-shell.frame-border": "var(--taliya-border-default)",
  "color.crm-setup-shell.panel-bg": "var(--taliya-surface-card)",
  "color.crm-setup-shell.panel-border": "var(--taliya-border-default)",
  "color.crm-setup-shell.text": "var(--taliya-color-text-primary)",
  "color.crm-setup-shell.muted": "#56637D",
  "color.crm-setup-shell.blue": "#0D6BFF",
  "color.crm-setup-shell.blue-soft": "#EAF3FF",
  "color.crm-setup-shell.blue-border": "#BFD5FF",
  "color.crm-setup-shell.divider": "var(--taliya-border-default)",
  "color.crm-setup-shell.dash": "#D7DDE8",
  "color.crm-setup-shell.placeholder": "#EEF1F5",
  "color.crm-setup-shell.success": "#22C55E",
  "color.crm-setup-shell.warning": "#0D6BFF",
  "color.crm-setup-welcome.bg": "#FBFCFF",
  "color.crm-setup-choice-card.bg": "var(--taliya-surface-card)",
  "color.crm-setup-choice-card.border": "var(--taliya-border-default)",
  "color.crm-setup-choice-card.selected-border": "#2E75FF",
  "color.crm-setup-choice-card.icon-bg": "#F2F4F7",
  "color.crm-setup-choice-card.selected-icon-bg": "#EAF3FF",
  "color.crm-setup-choice-card.selected-icon-fg": "#2E75FF",
  "color.crm-setup-import-source-card.bg": "var(--taliya-surface-card)",
  "color.crm-setup-import-source-card.border": "var(--taliya-border-default)",
  "color.crm-setup-import-source-card.hover-border": "var(--taliya-border-strong)",
  "color.crm-setup-import-source-card.selected-border": "#2E75FF",
  "color.crm-setup-import-source-card.selected-bg": "#F8FBFF",
  "color.crm-setup-import-source-card.imported-border": "rgba(34, 197, 94, 0.26)",
  "color.crm-setup-import-source-card.imported-bg": "#F7FEFA",
  "color.crm-setup-import-source-card.error-border": "rgba(239, 68, 68, 0.26)",
  "color.crm-setup-import-source-card.error-bg": "#FFF8F8",
  "color.crm-setup-import-source-card.icon": "var(--taliya-color-text-primary)",
  "color.crm-setup-import-source-card.status-selected": "#2E75FF",
  "color.crm-setup-import-source-card.status-imported": "#0F9A4A",
  "color.crm-setup-import-source-card.status-error": "#D33B3B",
  "color.crm-setup-review-panel.bg": "var(--taliya-surface-card)",
  "color.crm-setup-review-panel.border": "var(--taliya-border-default)",
  "color.crm-setup-review-panel.text": "var(--taliya-color-text-primary)",
  "color.crm-setup-review-panel.muted": "#52617E",
  "color.crm-setup-review-panel.divider": "var(--taliya-border-default)",
  "color.crm-setup-review-panel.ready-bg": "#E8F8ED",
  "color.crm-setup-review-panel.ready-fg": "#0F9A4A",
  "color.crm-setup-review-panel.ready-border": "rgba(22, 163, 74, 0.14)",
  "color.crm-setup-review-panel.review-bg": "var(--taliya-status-warning-review-bg)",
  "color.crm-setup-review-panel.review-fg": "#F25C05",
  "color.crm-setup-review-panel.review-border": "rgba(242, 92, 5, 0.28)",
  "color.crm-setup-review-panel.blocking-bg": "var(--taliya-status-danger-blocking-bg)",
  "color.crm-setup-review-panel.blocking-border": "rgba(239, 68, 68, 0.22)",
  "color.crm-setup-review-panel.blocking-fg": "#E11D2E",
  "color.crm-setup-review-panel.warning-bg": "#FFF8ED",
  "color.crm-setup-review-panel.warning-border": "rgba(249, 115, 22, 0.22)",
  "color.crm-setup-review-panel.warning-fg": "#F25C05",
  "color.crm-setup-review-panel.info": "#0D6BFF",
  "color.crm-setup-review-panel.success": "var(--taliya-color-accent-success)",
  "color.crm-setup-review-panel.action-bg": "var(--taliya-surface-card)",
  "color.crm-setup-review-panel.action-border": "var(--taliya-border-default)",
  "color.crm-setup-review-panel.primary-bg": "#070A0F",
  "color.crm-setup-review-panel.primary-fg": "var(--taliya-color-text-inverse)",
  "color.crm-setup-review-panel.chip-bg": "#F1F5FF",
  "color.crm-setup-review-panel.chevron": "#1F2B49",
  "color.crm-setup-agent-chat.bg": "var(--taliya-surface-card)",
  "color.crm-setup-agent-chat.border": "var(--taliya-border-default)",
  "color.crm-setup-agent-chat.text": "var(--taliya-color-text-primary)",
  "color.crm-setup-agent-chat.muted": "#777B84",
  "color.crm-setup-agent-chat.rule": "rgba(16, 20, 26, 0.10)",
  "color.crm-setup-agent-chat.info-bg": "#F2F7FF",
  "color.crm-setup-agent-chat.info-border": "#C9DAFA",
  "color.crm-setup-agent-chat.info-fg": "#1C6FEF",
  "color.crm-setup-agent-chat.message-bg": "var(--taliya-surface-card)",
  "color.crm-setup-agent-chat.message-border": "var(--taliya-border-default)",
  "color.crm-setup-agent-chat.composer-border": "rgba(16, 20, 26, 0.14)",
  "color.crm-setup-agent-chat.send-bg": "var(--taliya-raw-black-950)",
  "color.crm-setup-agent-chat.send-fg": "var(--taliya-surface-card)",
  "color.crm-setup-agent-chat.help-link": "#1F6FEF",
  "color.crm-agent-flow-drawer.bg": "var(--taliya-surface-card)",
  "color.crm-agent-flow-drawer.edge": "rgba(16, 20, 26, 0.08)",
  "color.crm-agent-flow-drawer.rule": "rgba(16, 20, 26, 0.08)",
  "color.crm-agent-flow-drawer.text": "var(--taliya-color-text-primary)",
  "color.crm-agent-flow-drawer.muted": "#56637D",
  "color.crm-agent-flow-drawer.info-bg": "#F4F8FF",
  "color.crm-agent-flow-drawer.info-border": "#D5E5FF",
  "color.crm-agent-flow-drawer.info-fg": "#0D6BFF",
  "color.crm-agent-flow-drawer.question-bg": "var(--taliya-surface-card)",
  "color.crm-agent-flow-drawer.question-border": "var(--taliya-border-default)",
  "color.crm-agent-flow-drawer.question-hover": "rgba(13, 107, 255, 0.055)",
  "color.crm-agent-flow-drawer.composer-border": "rgba(16, 20, 26, 0.12)",
  "color.crm-agent-flow-drawer.send-bg": "var(--taliya-raw-black-950)",
  "color.crm-agent-flow-drawer.send-fg": "var(--taliya-surface-card)",
  "color.crm-agent-flow-drawer.focus": "rgba(13, 107, 255, 0.28)",
  "color.crm-setup-human-help-cta.bg": "var(--taliya-surface-card)",
  "color.crm-setup-human-help-cta.rule": "rgba(16, 20, 26, 0.10)",
  "color.crm-setup-human-help-cta.link": "#1F6FEF",
  "color.crm-setup-human-help-cta.active": "#16A34A",
  "color.crm-setup-human-help-cta.unavailable": "#8A93A5",
  "color.crm-setup-block-header.warning-bg": "rgba(255, 241, 231, 0.95)",
  "color.crm-setup-block-header.warning-border": "rgba(255, 111, 22, 0.28)",
  "color.crm-setup-block-header.warning-fg": "#9A4B00",
  "color.crm-setup-block-header.complete-bg": "rgba(220, 247, 231, 0.95)",
  "color.crm-setup-block-header.complete-border": "rgba(20, 144, 77, 0.25)",
  "color.crm-setup-block-header.complete-fg": "#0F7A3E",
  "color.crm-mini-calendar.bg": "var(--taliya-surface-card)",
  "color.crm-mini-calendar.text": "var(--taliya-color-text-primary)",
  "color.crm-mini-calendar.muted": "#5E6A83",
  "color.crm-mini-calendar.weekday": "#56627A",
  "color.crm-mini-calendar.outside": "#8D96AA",
  "color.crm-mini-calendar.selected-bg": "#080A0D",
  "color.crm-mini-calendar.selected-fg": "var(--taliya-surface-card)",
  "color.crm-mini-calendar.today-bg": "#EEF5FF",
  "color.crm-mini-calendar.today-border": "#D7E7FF",
  "color.crm-mini-calendar.today-fg": "#1D2945",
  "color.crm-mini-calendar.hover-bg": "rgba(0, 92, 255, 0.055)",
  "color.crm-mini-calendar.disabled": "rgba(46, 57, 83, 0.38)",
  "color.crm-relationship-marker.fg": "var(--taliya-surface-card)",
  "color.crm-relationship-marker.ring": "rgba(94, 142, 232, 0.18)",
  "color.crm-finance.payment-method-pix": "#18A982",
  "color.crm-sales.row-selected-bg": "rgba(94, 142, 232, 0.07)",
  "color.crm-sales.whatsapp": "#10B963",
  "color.crm-sales.checklist-line": "rgba(94, 142, 232, 0.36)",
  "color.crm-retention.row-selected-bg": "rgba(94, 142, 232, 0.07)",
  "color.crm-retention.automation-bg": "rgba(255, 126, 42, 0.14)",
  "color.crm-retention.suggestion-bg": "rgba(139, 92, 246, 0.11)",
  "color.crm-retention.whatsapp": "#10B963",
  "color.crm-retention.divider": "var(--taliya-border-default)",
  "color.crm-support.suggestion-bg": "rgba(139, 92, 246, 0.12)",
  "color.crm-support.message-bg": "rgba(94, 142, 232, 0.08)",
  "color.crm-support.access-bg": "rgba(239, 68, 68, 0.10)",
  "color.crm-internal.access-bg": "rgba(22, 163, 74, 0.10)",
  "color.crm-internal.security-bg": "rgba(255, 126, 42, 0.09)",
  "color.crm-internal.copilot-bg": "rgba(139, 92, 246, 0.11)",
  "color.crm-internal.row-selected-bg": "rgba(94, 142, 232, 0.08)",
  "color.crm-internal.progress-track": "rgba(16, 20, 26, 0.10)",
  "color.crm-reports.metric-danger": "#EF1F1F",
  "color.crm-reports.metric-success": "#0F9A4A",
  "color.crm-reports.impact-dot": "rgba(16, 20, 26, 0.25)",
  "color.crm-opportunity.suggestion-bg": "rgba(139, 92, 246, 0.12)",
  "color.crm-opportunity.notice-bg": "rgba(255, 126, 42, 0.10)",
  "color.crm-opportunity.manual-bg": "var(--taliya-surface-disabled)",
  "color.crm-opportunity.timeline-line": "rgba(94, 142, 232, 0.45)",
  "color.crm-subscription.title": "#172033",
  "color.crm-subscription.text": "#25324B",
  "color.crm-subscription.text-muted": "rgba(46, 57, 83, 0.68)",
  "color.crm-subscription.supporting": "rgba(46, 57, 83, 0.66)",
  "color.crm-subscription.label": "#151D2F",
  "color.crm-subscription.detail-text": "#1B263D",
  "color.crm-subscription.card-border": "var(--taliya-border-subtle)",
  "color.crm-subscription.card-shadow": "var(--taliya-surface-field-disabled)",
  "color.crm-subscription.verifying-card-bg": "#FBFCFE",
  "color.crm-subscription.verifying-status-row-bg": "var(--taliya-surface-segmented)",
  "color.crm-subscription.action-shadow": "rgba(16, 20, 26, 0.075)",
  "color.crm-subscription.secure-bg": "rgba(22, 163, 74, 0.045)",
  "color.crm-subscription.secure-border": "rgba(22, 163, 74, 0.085)",
  "color.crm-subscription.secure-icon": "#18B96A",
  "color.crm-subscription.secure-content": "rgba(46, 57, 83, 0.48)",
  "color.crm-subscription.failed-callout-bg": "rgba(245, 158, 11, 0.045)",
  "color.crm-subscription.failed-callout-border": "rgba(245, 158, 11, 0.22)",
  "color.crm-subscription.failed-callout-body": "rgba(46, 57, 83, 0.56)",
  "color.crm-subscription.failed-details-bg": "rgba(255, 255, 255, 0.28)",
  "color.crm-subscription.failed-details-border": "var(--taliya-surface-field-disabled)",
  "color.crm-subscription.failed-detail-text": "#202B40",
  "color.crm-subscription.failed-header-subcopy": "rgba(46, 57, 83, 0.66)",
  "color.crm-subscription.failed-link": "rgba(46, 57, 83, 0.72)",
  "color.crm-subscription.failed-supporting": "rgba(46, 57, 83, 0.58)",
  "color.crm-subscription.failed-action-fg": "rgba(255, 255, 255, 0.88)",
  "color.crm-subscription.progress-success": "#20BF6B",
  "color.crm-subscription.progress-current": "#37BEB2",
  "color.crm-subscription.status-dot": "#35D5C9",
  "color.crm-subscription.link": "#52617E",
  "color.crm-subscription.detail-icon": "#1F66E5",
  "color.crm-subscription.card-bg": "var(--taliya-surface-card)",
  "color.crm-subscription.confirmed-icon-bg": "var(--taliya-surface-card)",
  "color.crm-subscription.confirmed-icon-ring": "#C4F7D3",
  "color.crm-subscription.confirmed-icon-fg": "#08D044",
  "color.crm-subscription.release-note-bg": "rgba(22, 163, 74, 0.04)",
  "color.crm-subscription.release-note-icon": "#08D044",
  "color.crm-subscription.primary-action-bg-start": "#171B23",
  "color.crm-subscription.primary-action-bg-end": "#05070B",
  "color.crm-subscription.primary-action-border": "var(--taliya-border-strong)",
  "color.crm-subscription.failed-action-bg-start": "#171C26",
  "color.crm-subscription.failed-action-bg-end": "#10141D",
  "color.crm-subscription.failed-action-highlight": "rgba(255, 255, 255, 0.055)",
  "color.crm-subscription.failed-action-shadow": "rgba(16, 20, 26, 0.045)",
  "color.crm-subscription.verifying-action-bg-start": "#414A57",
  "color.crm-subscription.verifying-action-bg-end": "#2F3743",
  "color.crm-checkout-payment-card.bg": "var(--taliya-surface-card)",
  "color.crm-checkout-payment-card.title": "#101827",
  "color.crm-checkout-payment-card.text": "var(--taliya-color-text-primary)",
  "color.crm-checkout-payment-card.muted": "#52617E",
  "color.crm-checkout-payment-card.divider": "var(--taliya-border-default)",
  "color.crm-checkout-payment-card.field-bg": "var(--taliya-surface-card)",
  "color.crm-checkout-payment-card.field-border": "var(--taliya-border-default)",
  "color.crm-checkout-payment-card.placeholder": "rgba(46, 57, 83, 0.48)",
  "color.crm-checkout-payment-card.link": "#5869D6",
  "color.crm-plan-summary.title": "#101827",
  "color.crm-plan-summary.text": "#25324B",
  "color.crm-plan-summary.muted": "#52617E",
  "color.crm-plan-summary.icon-bg": "rgba(46, 114, 255, 0.10)",
  "color.crm-plan-summary.icon-fg": "#1F66E5",
  "color.crm-plan-summary.success": "#20C86F",
  "color.crm-plan-summary.disabled": "rgba(46, 57, 83, 0.42)",
  "color.crm-plan-summary.neutral-status": "#A8B0BF",
  "color.crm-plan-summary.divider": "var(--taliya-border-default)",
  "color.crm-plan-summary.chip-bg": "var(--taliya-border-subtle)",
  "color.crm-invoice-table.bg": "var(--taliya-surface-card)",
  "color.crm-invoice-table.title": "var(--taliya-color-text-primary)",
  "color.crm-invoice-table.text": "#25324B",
  "color.crm-invoice-table.header": "#2E3953",
  "color.crm-invoice-table.divider": "var(--taliya-border-default)",
  "color.crm-invoice-table.border": "var(--taliya-border-subtle)",
  "color.crm-invoice-table.action-border": "var(--taliya-border-default)",
  "color.crm-invoice-table.action-hover-bg": "var(--taliya-surface-disabled)",
  "color.crm-invoice-table.open-bg": "#FBEDE8",
  "color.crm-invoice-table.open-fg": "#E65F00",
  "color.crm-invoice-table.paid-bg": "#DFF7E8",
  "color.crm-invoice-table.paid-fg": "#0F9A4A",
  "color.crm-invoice-table.failed-bg": "rgba(239, 68, 68, 0.12)",
  "color.crm-invoice-table.failed-fg": "#B94444",
  "color.crm-addon-card.bg": "var(--taliya-surface-card)",
  "color.crm-addon-card.title": "var(--taliya-color-text-primary)",
  "color.crm-addon-card.text": "var(--taliya-color-text-primary)",
  "color.crm-addon-card.muted": "#52617E",
  "color.crm-addon-card.border": "var(--taliya-border-default)",
  "color.crm-addon-card.icon-bg": "rgba(131, 162, 219, 0.14)",
  "color.crm-addon-card.icon-fg": "#1F66E5",
  "color.crm-addon-card.available-bg": "#DFF7E8",
  "color.crm-addon-card.available-fg": "#0F9A4A",
  "color.crm-addon-card.plan-bg": "#FBEDE8",
  "color.crm-addon-card.plan-fg": "#E65F00",
  "color.crm-addon-card.consult-bg": "#F1E7FF",
  "color.crm-addon-card.consult-fg": "#6D42D8",
  "color.crm-addon-card.active-bg": "rgba(22, 163, 74, 0.12)",
  "color.crm-addon-card.active-fg": "var(--taliya-color-accent-success)",
  "color.crm-addon-card.action-primary-bg": "var(--taliya-raw-black-950)",
  "color.crm-addon-card.action-primary-fg": "var(--taliya-surface-card)",
  "color.crm-addon-card.action-border": "#A9B2C6",
  "color.crm-settings-hub-card.bg": "var(--taliya-surface-card)",
  "color.crm-settings-hub-card.title": "var(--taliya-color-text-primary)",
  "color.crm-settings-hub-card.text": "#52617E",
  "color.crm-settings-hub-card.border": "var(--taliya-border-default)",
  "color.crm-settings-hub-card.icon-bg": "rgba(46, 114, 255, 0.08)",
  "color.crm-settings-hub-card.icon-fg": "#005CFF",
  "color.crm-settings-hub-card.action-bg": "var(--taliya-surface-card)",
  "color.crm-settings-hub-card.action-border": "#A9B2C6",
  "color.crm-settings-hub-card.action-fg": "var(--taliya-color-text-primary)",
  "color.crm-settings-hub-card.ready-bg": "#DFF7E8",
  "color.crm-settings-hub-card.ready-fg": "#0F9A4A",
  "color.crm-settings-hub-card.pending-bg": "#FBEDE8",
  "color.crm-settings-hub-card.pending-fg": "#E65F00",
  "color.crm-settings-hub-card.review-bg": "#FBEDE8",
  "color.crm-settings-hub-card.review-fg": "#E65F00",
  "color.crm-settings-hub-card.connected-bg": "#DFF7E8",
  "color.crm-settings-hub-card.connected-fg": "#0F9A4A",
  "color.crm-settings-hub-card.blocked-bg": "var(--taliya-border-subtle)",
  "color.crm-settings-hub-card.blocked-fg": "#566278",
  "color.crm-settings-section.bg": "var(--taliya-surface-card)",
  "color.crm-settings-section.title": "var(--taliya-color-text-primary)",
  "color.crm-settings-section.text": "var(--taliya-color-text-primary)",
  "color.crm-settings-section.muted": "#25385F",
  "color.crm-settings-section.border": "var(--taliya-border-default)",
  "color.crm-settings-section.row-border": "var(--taliya-border-default)",
  "color.crm-settings-section.action-bg": "var(--taliya-surface-card)",
  "color.crm-settings-section.action-border": "#E1E5EE",
  "color.crm-settings-section.action-hover": "var(--taliya-surface-field-disabled)",
  "color.crm-settings-section.toggle-on-bg": "#0D6BFF",
  "color.crm-settings-section.toggle-off-bg": "#EEF1F5",
  "color.crm-settings-section.toggle-off-border": "#D6DCE6",
  "color.crm-settings-section.info": "#2A4C86",
  "color.crm-settings-section.warning": "#FF7E2A",
  "color.crm-settings-section.success": "#12C44F",
  "color.crm-settings-section.danger": "#FE2B31",
  "color.crm-settings-section.neutral": "#7B8494",
  "color.crm-settings-section.dirty-bg": "var(--taliya-status-warning-dirty-bg)",
  "color.crm-settings-section.dirty-fg": "#E65F00",
  "color.crm-settings-section.saved-bg": "#DFF7E8",
  "color.crm-settings-section.saved-fg": "#0F9A4A",
  "color.crm-settings-section.blocked-bg": "var(--taliya-border-subtle)",
  "color.crm-settings-section.blocked-fg": "#566278",
  "color.crm-integration-status-row.bg": "var(--taliya-surface-card)",
  "color.crm-integration-status-row.title": "var(--taliya-color-text-primary)",
  "color.crm-integration-status-row.text": "#2A3656",
  "color.crm-integration-status-row.divider": "#E1E5EE",
  "color.crm-integration-status-row.pix": "#04BFA9",
  "color.crm-integration-status-row.card": "#274A86",
  "color.crm-integration-status-row.recurrence": "#7C1FFF",
  "color.crm-integration-status-row.reconciliation": "#FF7E2A",
  "color.crm-integration-status-row.connected": "#0F9A4A",
  "color.crm-integration-status-row.pending": "#E65F00",
  "color.crm-integration-status-row.failed": "#FE2B31",
  "color.crm-integration-status-row.blocked": "#2A3656",
  "color.crm-integration-status-row.loading": "#1F66E5",
  "color.crm-unsaved-changes-bar.bg": "var(--taliya-surface-card)",
  "color.crm-unsaved-changes-bar.cancel-bg": "var(--taliya-surface-card)",
  "color.crm-unsaved-changes-bar.cancel-border": "#E1E5EE",
  "color.crm-unsaved-changes-bar.cancel-fg": "var(--taliya-color-text-primary)",
  "color.crm-unsaved-changes-bar.primary-bg": "var(--taliya-raw-black-950)",
  "color.crm-unsaved-changes-bar.primary-fg": "var(--taliya-surface-card)",
  "color.crm-unsaved-changes-bar.saved-bg": "#DFF7E8",
  "color.crm-unsaved-changes-bar.saved-fg": "#0F9A4A",
  "color.crm-unsaved-changes-bar.saving-bg": "#FBEDE8",
  "color.crm-unsaved-changes-bar.saving-fg": "#E65F00",
  "color.crm-unsaved-changes-bar.blocked-bg": "var(--taliya-border-subtle)",
  "color.crm-unsaved-changes-bar.blocked-fg": "#566278",
  "color.crm-rule-row.bg": "var(--taliya-surface-card)",
  "color.crm-rule-row.text": "var(--taliya-color-text-primary)",
  "color.crm-rule-row.muted": "#52617E",
  "color.crm-rule-row.border": "var(--taliya-border-default)",
  "color.crm-rule-row.select-bg": "var(--taliya-surface-card)",
  "color.crm-rule-row.select-border": "#DCE1EA",
  "color.crm-rule-row.select-hover": "var(--taliya-surface-field-disabled)",
  "color.crm-rule-row.toggle-on-bg": "#12AA42",
  "color.crm-rule-row.toggle-off-bg": "#EEF1F5",
  "color.crm-rule-row.toggle-off-border": "#D6DCE6",
  "color.crm-rule-row.danger": "#FE2B31",
  "color.crm-rule-row.warning": "#FF7E2A",
  "color.crm-rule-row.info": "#1F66E5",
  "color.crm-rule-row.neutral": "#7B8494",
  "color.crm-rule-row.success": "#0F9A4A",
  "color.crm-quota-progress.bg": "var(--taliya-surface-card)",
  "color.crm-quota-progress.title": "var(--taliya-color-text-primary)",
  "color.crm-quota-progress.text": "var(--taliya-color-text-primary)",
  "color.crm-quota-progress.muted": "#25324B",
  "color.crm-quota-progress.border": "var(--taliya-border-default)",
  "color.crm-quota-progress.track": "#E3E5ED",
  "color.crm-quota-progress.fill": "#005CFF",
  "color.crm-quota-progress.fill-label": "#FFFFFF",
  "color.crm-quota-progress.icon-bg": "rgba(46, 114, 255, 0.08)",
  "color.crm-quota-progress.icon-fg": "#005CFF",
  "color.crm-quota-progress.normal-bg": "#EBF7EE",
  "color.crm-quota-progress.normal-fg": "#0F9A4A",
  "color.crm-quota-progress.normal-border": "rgba(22, 163, 74, 0.18)",
  "color.crm-quota-progress.action-border": "#A9B2C6",
  "color.crm-quota-progress.action-secondary-fg": "#25324B",
  "color.crm-quota-progress.action-primary-bg": "#005CFF",
  "color.crm-quota-progress.action-primary-bg-hover": "#0053E8",
  "color.crm-quota-progress.action-primary-fg": "var(--taliya-surface-card)",
  "color.crm-usage-ledger.bg": "var(--taliya-surface-card)",
  "color.crm-usage-ledger.title": "var(--taliya-color-text-primary)",
  "color.crm-usage-ledger.text": "var(--taliya-color-text-primary)",
  "color.crm-usage-ledger.muted": "#25324B",
  "color.crm-usage-ledger.border": "var(--taliya-border-default)",
  "color.crm-usage-ledger.table-border": "var(--taliya-border-default)",
  "color.crm-usage-ledger.table-header": "#25324B",
  "color.crm-usage-ledger.filter-bg": "var(--taliya-surface-card)",
  "color.crm-usage-ledger.filter-border": "rgba(16, 20, 26, 0.11)",
  "color.crm-usage-ledger.filter-hover": "var(--taliya-surface-disabled)",
  "color.crm-usage-ledger.link": "#005CFF",
  "color.crm-usage-ledger.link-hover": "#0048D8",
  "color.crm-usage-ledger.consumed-bg": "#E6F7E9",
  "color.crm-usage-ledger.consumed-fg": "#0F9A4A",
  "color.crm-usage-ledger.consumed-border": "rgba(22, 163, 74, 0.12)",
  "color.crm-usage-ledger.estimated-bg": "#EEF4FF",
  "color.crm-usage-ledger.estimated-fg": "#005CFF",
  "color.crm-usage-ledger.estimated-border": "rgba(0, 92, 255, 0.08)",
  "color.crm-usage-ledger.reprocessed-bg": "#F1F4F8",
  "color.crm-usage-ledger.reprocessed-fg": "#52617E",
  "color.crm-usage-ledger.reprocessed-border": "rgba(82, 97, 126, 0.08)",
  "color.crm-usage-ledger.whatsapp-bg": "rgba(22, 199, 91, 0.14)",
  "color.crm-usage-ledger.whatsapp-fg": "#16C75B",
  "color.crm-usage-ledger.ai-bg": "rgba(0, 92, 255, 0.10)",
  "color.crm-usage-ledger.ai-fg": "#005CFF",
  "color.crm-usage-ledger.action-border": "var(--taliya-border-default)",
  "color.crm-usage-header-summary.bg": "var(--taliya-surface-card)",
  "color.crm-usage-header-summary.border": "var(--taliya-border-default)",
  "color.crm-usage-header-summary.text": "var(--taliya-color-text-primary)",
  "color.crm-usage-header-summary.info": "var(--taliya-color-crm-usage-ledger-link)",
  "color.crm-usage-header-summary.success-bg": "var(--taliya-status-success-bg)",
  "color.crm-usage-header-summary.success-border": "var(--taliya-status-success-border)",
  "color.crm-usage-header-summary.success-text": "var(--taliya-status-success-fg)",
  "color.crm-usage-header-summary.warning-bg": "var(--taliya-status-warning-bg)",
  "color.crm-usage-header-summary.warning-border": "var(--taliya-status-warning-border)",
  "color.crm-usage-header-summary.warning-text": "var(--taliya-status-warning-fg)",
  "color.crm-approval-panel.bg": "var(--taliya-color-white)",
  "color.crm-approval-panel.title": "var(--taliya-color-text-primary)",
  "color.crm-approval-panel.text": "#1F2B49",
  "color.crm-approval-panel.muted": "#33405E",
  "color.crm-approval-panel.border": "var(--taliya-border-default)",
  "color.crm-approval-panel.divider": "var(--taliya-border-default)",
  "color.crm-approval-panel.close-bg": "var(--taliya-surface-card)",
  "color.crm-approval-panel.close-border": "var(--taliya-border-default)",
  "color.crm-approval-panel.close-hover": "var(--taliya-surface-disabled)",
  "color.crm-approval-panel.chip-bg": "#F0E8FF",
  "color.crm-approval-panel.chip-fg": "#6D42D8",
  "color.crm-approval-panel.suggestion-bg": "rgba(139, 92, 246, 0.10)",
  "color.crm-approval-panel.suggestion-border": "rgba(139, 92, 246, 0.06)",
  "color.crm-approval-panel.status-pending": "var(--taliya-color-accent-warning)",
  "color.crm-approval-panel.status-approved": "var(--taliya-color-accent-success)",
  "color.crm-approval-panel.status-rejected": "var(--taliya-color-accent-danger)",
  "color.crm-approval-panel.status-expired": "#B94444",
  "color.crm-approval-panel.whatsapp": "#16C75B",
  "color.crm-approval-panel.copilot": "#7C3AED",
  "color.crm-approval-panel.low-risk": "var(--taliya-color-accent-success)",
  "color.crm-approval-panel.medium-risk": "var(--taliya-color-accent-warning)",
  "color.crm-approval-panel.high-risk": "var(--taliya-color-accent-danger)",
  "color.crm-approval-panel.link": "#005CFF",
  "color.crm-approval-panel.timeline-dot": "#7D8AAA",
  "color.crm-approval-panel.action-primary-bg": "var(--taliya-raw-black-950)",
  "color.crm-approval-panel.action-primary-fg": "var(--taliya-surface-card)",
  "color.crm-approval-panel.action-secondary-bg": "var(--taliya-surface-card)",
  "color.crm-approval-panel.action-border": "var(--taliya-border-default)",
  "color.crm-approval-panel.action-hover": "var(--taliya-surface-field-disabled)",
  "color.crm-approval-table.selected-bg": "var(--taliya-color-crm-product-shell-control-hover-bg)",
  "color.crm-student-table.selected-bg": "var(--taliya-color-crm-product-shell-control-hover-bg)",
  "color.crm-impact-summary.bg": "var(--taliya-surface-card)",
  "color.crm-impact-summary.title": "#2E3138",
  "color.crm-impact-summary.text": "#687180",
  "color.crm-impact-summary.muted": "#747C89",
  "color.crm-impact-summary.border": "var(--taliya-border-default)",
  "color.crm-impact-summary.icon-info-bg": "#EEF4FF",
  "color.crm-impact-summary.icon-info-fg": "#2E72FF",
  "color.crm-impact-summary.icon-success-bg": "#E6F7E9",
  "color.crm-impact-summary.icon-success-fg": "#0F9A4A",
  "color.crm-impact-summary.icon-warning-bg": "#FFF0DC",
  "color.crm-impact-summary.icon-warning-fg": "var(--taliya-color-accent-warning)",
  "color.crm-impact-summary.icon-danger-bg": "#FEE7E7",
  "color.crm-impact-summary.icon-danger-fg": "var(--taliya-color-accent-danger)",
  "color.crm-permission-matrix.bg": "var(--taliya-surface-card)",
  "color.crm-permission-matrix.title": "#1F252E",
  "color.crm-permission-matrix.text": "#28303A",
  "color.crm-permission-matrix.muted": "#6C7480",
  "color.crm-permission-matrix.header": "#687180",
  "color.crm-permission-matrix.border": "var(--taliya-border-default)",
  "color.crm-permission-matrix.row-border": "var(--taliya-border-subtle)",
  "color.crm-permission-matrix.index-bg": "var(--taliya-color-accent-info)",
  "color.crm-permission-matrix.index-fg": "var(--taliya-surface-card)",
  "color.crm-permission-matrix.toggle-on-bg": "var(--taliya-color-text-primary)",
  "color.crm-permission-matrix.toggle-off-bg": "#F2F3F5",
  "color.crm-permission-matrix.toggle-off-border": "#CCD1DA",
  "color.crm-permission-matrix.select-bg": "var(--taliya-surface-card)",
  "color.crm-permission-matrix.select-border": "#DCE1EA",
  "color.crm-permission-matrix.control-hover": "var(--taliya-surface-field-disabled)",
  "color.crm-permission-matrix.dirty-bg": "var(--taliya-status-warning-dirty-bg)",
  "color.crm-permission-matrix.dirty-fg": "#E65F00",
  "color.crm-before-after-diff.bg": "var(--taliya-surface-card)",
  "color.crm-before-after-diff.title": "var(--taliya-color-text-primary)",
  "color.crm-before-after-diff.text": "#344056",
  "color.crm-before-after-diff.muted": "#566278",
  "color.crm-before-after-diff.border": "var(--taliya-border-subtle)",
  "color.crm-before-after-diff.table-border": "rgba(16, 20, 26, 0.038)",
  "color.crm-before-after-diff.changed-bg": "rgba(22, 163, 74, 0.055)",
  "color.crm-before-after-diff.added-bg": "rgba(22, 163, 74, 0.055)",
  "color.crm-before-after-diff.removed-bg": "rgba(239, 68, 68, 0.055)",
  "color.crm-before-after-diff.action-primary-bg": "var(--taliya-raw-black-950)",
  "color.crm-before-after-diff.action-primary-fg": "var(--taliya-surface-card)",
  "color.crm-before-after-diff.action-secondary-bg": "var(--taliya-surface-card)",
  "color.crm-before-after-diff.action-border": "var(--taliya-border-default)",
  "color.crm-conversation-list.bg": "var(--taliya-surface-card)",
  "color.crm-conversation-list.row-bg": "var(--taliya-surface-card)",
  "color.crm-conversation-list.row-selected-bg": "rgba(94, 142, 232, 0.045)",
  "color.crm-conversation-list.row-border": "var(--taliya-border-default)",
  "color.crm-conversation-list.row-selected-border": "#A8C7FF",
  "color.crm-conversation-list.text": "var(--taliya-color-text-primary)",
  "color.crm-conversation-list.muted": "#25385F",
  "color.crm-conversation-list.time": "#25385F",
  "color.crm-conversation-list.whatsapp": "#16C75B",
  "color.crm-conversation-list.meta-bg": "var(--taliya-surface-field-disabled)",
  "color.crm-conversation-list.meta-fg": "#52617E",
  "color.crm-conversation-list.waiting-bg": "var(--taliya-status-warning-waiting-bg)",
  "color.crm-conversation-list.waiting-fg": "#E65F00",
  "color.crm-conversation-list.progress-bg": "#E8F1FF",
  "color.crm-conversation-list.progress-fg": "#0D6BFF",
  "color.crm-conversation-list.copilot-bg": "#F2E8FF",
  "color.crm-conversation-list.copilot-fg": "#7C3AED",
  "color.crm-conversation-list.failed-bg": "#FFECEC",
  "color.crm-conversation-list.failed-fg": "#FE2B31",
  "color.crm-conversation-list.optout-bg": "#DFF7E8",
  "color.crm-conversation-list.optout-fg": "#0F9A4A",
  "color.crm-conversation-list.footer-control-bg": "var(--taliya-surface-card)",
  "color.crm-conversation-list.footer-current-bg": "var(--taliya-raw-black-950)",
  "color.crm-conversation-list.footer-current-fg": "var(--taliya-surface-card)",
  "color.crm-quick-reply.bg": "var(--taliya-surface-card)",
  "color.crm-quick-reply.bg-hover": "#f7faff",
  "color.crm-quick-reply.bg-selected": "#eef5ff",
  "color.crm-quick-reply.border": "#c6d9ff",
  "color.crm-quick-reply.border-hover": "#8fb6ff",
  "color.crm-quick-reply.fg": "#1f66e5",
  "color.crm-quick-reply.icon-bg": "var(--taliya-surface-card)",
  "color.crm-quick-reply.disabled-bg": "var(--taliya-surface-field-disabled)",
  "color.crm-quick-reply.disabled-border": "var(--taliya-border-default)",
  "color.crm-quick-reply.disabled-fg": "var(--taliya-color-text-disabled)",
  "color.crm-checklist-row.bg": "var(--taliya-surface-card)",
  "color.crm-checklist-row.bg-hover": "rgba(94, 142, 232, 0.035)",
  "color.crm-checklist-row.bg-selected": "rgba(94, 142, 232, 0.06)",
  "color.crm-checklist-row.text": "var(--taliya-color-text-primary)",
  "color.crm-checklist-row.index": "#566278",
  "color.crm-checklist-row.border": "var(--taliya-border-subtle)",
  "color.crm-checklist-row.check-border": "#a8b3c4",
  "color.crm-checklist-row.check-complete-bg": "#1fbf75",
  "color.crm-checklist-row.check-complete-fg": "var(--taliya-surface-card)",
  "color.crm-checklist-row.warning": "#f08a24",
  "color.crm-checklist-row.blocked": "var(--taliya-color-accent-danger)",
  "color.crm-checklist-row.disabled-fg": "var(--taliya-color-text-disabled)",
  "color.crm-comment-thread.bg": "var(--taliya-surface-card)",
  "color.crm-comment-thread.border": "var(--taliya-border-default)",
  "color.crm-comment-thread.text": "var(--taliya-color-text-primary)",
  "color.crm-comment-thread.muted": "#596784",
  "color.crm-comment-thread.link": "#1f66e5",
  "color.crm-comment-thread.row-hover": "rgba(94, 142, 232, 0.035)",
  "color.crm-comment-thread.failed-bg": "rgba(239, 68, 68, 0.055)",
  "color.crm-comment-thread.failed-fg": "var(--taliya-color-accent-danger)",
  "color.crm-comment-thread.blocked-bg": "var(--taliya-surface-field-disabled)",
  "color.crm-comment-thread.disabled-fg": "rgba(16, 20, 26, 0.36)",
  "color.crm-task-drawer.bg": "var(--taliya-surface-product-drawer)",
  "color.crm-task-drawer.edge": "rgba(16, 20, 26, 0.08)",
  "color.crm-task-drawer.text": "var(--taliya-color-text-primary)",
  "color.crm-task-drawer.muted": "#2f3e63",
  "color.crm-task-drawer.subtle": "#5c6d91",
  "color.crm-task-drawer.rule": "rgba(47, 62, 99, 0.14)",
  "color.crm-task-drawer.label-bg": "#eaf3ff",
  "color.crm-task-drawer.label-fg": "#1f66e5",
  "color.crm-task-drawer.pending-bg": "#fff1e7",
  "color.crm-task-drawer.pending-fg": "#ff7a1a",
  "color.crm-task-drawer.danger": "#ff2525",
  "color.crm-task-drawer.focus": "rgba(31, 102, 229, 0.24)",
  "color.crm-task-drawer.row-hover": "rgba(94, 142, 232, 0.04)",
  "color.crm-task-drawer.blocked-bg": "var(--taliya-surface-field-disabled)",
  "color.crm-task-drawer.disabled-fg": "rgba(16, 20, 26, 0.36)",
  "color.crm-case-drawer.bg": "var(--taliya-surface-product-drawer)",
  "color.crm-case-drawer.edge": "var(--taliya-color-crm-task-drawer-edge)",
  "color.crm-case-drawer.text": "var(--taliya-color-text-primary)",
  "color.crm-case-drawer.muted": "var(--taliya-color-crm-task-drawer-muted)",
  "color.crm-case-drawer.rule": "var(--taliya-color-crm-task-drawer-rule)",
  "color.crm-case-drawer.chip-bg": "var(--taliya-color-crm-conversation-thread-suggestion-bg)",
  "color.crm-case-drawer.chip-fg": "var(--taliya-color-crm-conversation-thread-suggestion-icon)",
  "color.crm-case-drawer.danger": "var(--taliya-color-crm-task-drawer-danger)",
  "color.crm-case-drawer.focus": "var(--taliya-color-crm-task-drawer-focus)",
  "color.crm-case-drawer.warning-bg": "var(--taliya-status-warning-bg)",
  "color.crm-case-drawer.warning-fg": "var(--taliya-status-warning-fg)",
  "color.crm-case-drawer.success-bg": "var(--taliya-status-success-bg)",
  "color.crm-case-drawer.success-fg": "var(--taliya-status-success-fg)",
  "color.crm-case-drawer.suggestion-bg": "var(--taliya-color-crm-conversation-thread-suggestion-bg)",
  "color.crm-case-drawer.action-border": "var(--taliya-border-default)",
  "color.crm-case-drawer.option-warning-dot": "#F28B24",
  "color.crm-case-drawer.option-success-dot": "#16C75B",
  "color.crm-case-drawer.message-chip-bg": "#EAF3FF",
  "color.crm-case-drawer.message-chip-fg": "#1F66E5",
  "color.crm-case-drawer.review-chip-bg": "rgba(16, 20, 26, 0.055)",
  "color.crm-case-drawer.timeline-dot": "#9AA7BA",
  "color.crm-replacement-drawer.bg": "var(--taliya-surface-product-drawer)",
  "color.crm-replacement-drawer.edge": "var(--taliya-color-crm-task-drawer-edge)",
  "color.crm-replacement-drawer.text": "var(--taliya-color-text-primary)",
  "color.crm-replacement-drawer.muted": "var(--taliya-color-crm-task-drawer-muted)",
  "color.crm-replacement-drawer.rule": "var(--taliya-color-crm-task-drawer-rule)",
  "color.crm-replacement-drawer.focus": "var(--taliya-color-crm-task-drawer-focus)",
  "color.crm-replacement-drawer.info-bg": "var(--taliya-color-crm-conversation-thread-suggestion-bg)",
  "color.crm-replacement-drawer.info-fg": "var(--taliya-color-crm-conversation-thread-suggestion-icon)",
  "color.crm-replacement-drawer.suggestion-bg": "var(--taliya-color-crm-conversation-thread-suggestion-bg)",
  "color.crm-replacement-drawer.success-bg": "var(--taliya-status-success-bg)",
  "color.crm-replacement-drawer.success-fg": "var(--taliya-status-success-fg)",
  "color.crm-replacement-drawer.warning-bg": "var(--taliya-status-warning-bg)",
  "color.crm-replacement-drawer.warning-fg": "var(--taliya-status-warning-fg)",
  "color.crm-replacement-drawer.danger-bg": "var(--taliya-status-danger-bg)",
  "color.crm-replacement-drawer.danger-fg": "var(--taliya-status-danger-fg)",
  "color.crm-replacement-drawer.safe-bg": "var(--taliya-status-success-bg)",
  "color.crm-conversation-thread.bg": "var(--taliya-surface-card)",
  "color.crm-conversation-thread.text": "var(--taliya-color-text-primary)",
  "color.crm-conversation-thread.muted": "#52617E",
  "color.crm-conversation-thread.divider": "rgba(16, 20, 26, 0.055)",
  "color.crm-conversation-thread.message-bg": "var(--taliya-surface-card)",
  "color.crm-conversation-thread.message-border": "var(--taliya-border-default)",
  "color.crm-conversation-thread.banner-bg": "var(--taliya-status-warning-banner-bg)",
  "color.crm-conversation-thread.banner-border": "#FFE9BE",
  "color.crm-conversation-thread.banner-fg": "#566278",
  "color.crm-conversation-thread.banner-icon": "#F28B24",
  "color.crm-conversation-thread.system-dot": "#5E8EE8",
  "color.crm-conversation-thread.suggestion-bg": "#F4EFFF",
  "color.crm-conversation-thread.suggestion-border": "#E7DAFF",
  "color.crm-conversation-thread.suggestion-icon": "#6D3DFF",
  "color.crm-conversation-thread.action-bg": "var(--taliya-surface-card)",
  "color.crm-conversation-thread.action-border": "#E4E8F1",
  "color.crm-conversation-thread.composer-bg": "var(--taliya-surface-card)",
  "color.crm-conversation-thread.composer-placeholder": "#6D7892",
  "color.crm-conversation-thread.send-bg": "var(--taliya-raw-black-950)",
  "color.crm-conversation-thread.send-fg": "var(--taliya-surface-card)",
  "color.crm-context-panel.bg": "var(--taliya-surface-card)",
  "color.crm-context-panel.border": "var(--taliya-border-default)",
  "color.crm-context-panel.divider": "var(--taliya-border-default)",
  "color.crm-context-panel.text": "var(--taliya-color-text-primary)",
  "color.crm-context-panel.muted": "#52617E",
  "color.crm-context-panel.link": "#1473FF",
  "color.crm-context-panel.success": "#16C75B",
  "color.crm-context-panel.success-bg": "#D7F7E4",
  "color.crm-context-panel.warning-bg": "#FFF0D8",
  "color.crm-context-panel.warning": "#E77805"
} as const satisfies TokenRecord;
