import { describe, expect, it } from "vitest";
import {
  allTokens,
  operationalStateNames,
  quotaNames,
  statusNames,
  tokenGroups,
  tokenToCssVar,
  tokenVar
} from "./index";

describe("@taliya/tokens", () => {
  it("exposes canonical v1 visual token groups", () => {
    expect(allTokens["raw.gray.100"]).toBe("#E4E4E4");
    expect(allTokens["raw.gray.110"]).toBe("#E4E6EA");
    expect(allTokens["surface.app"]).toBe("#E4E4E4");
    expect(allTokens["layout.sidebar.compact"]).toBe("72px");
    expect(allTokens["layout.crm-empty-shell.sidebar.control-offset-x"]).toBe("-29px");
    expect(allTokens["layout.crm-empty-shell.sidebar.nav-offset-y"]).toBe("35px");
    expect(allTokens["layout.crm-empty-shell.sidebar.nav-gap"]).toBe("13px");
    expect(allTokens["layout.crm-empty-shell.sidebar.first-control-gap"]).toBe("1px");
    expect(allTokens["layout.crm-empty-shell.sidebar.padding-bottom"]).toBe("88px");
    expect(allTokens["layout.crm-empty-shell.sidebar.utility-gap"]).toBe("12px");
    expect(allTokens["layout.crm-empty-shell.topbar.nav-gap"]).toBe("19px");
    expect(allTokens["color.logo-dot.start"]).toBe("#2E72FF");
    expect(allTokens["control.icon.stroke-width"]).toBe("1.8");
    expect(allTokens["control.icon-button.md.size"]).toBe("40px");
    expect(allTokens["control.icon-button.md.icon"]).toBe("18px");
    expect(allTokens["control.avatar.md"]).toBe("40px");
    expect(allTokens["control.avatar.2xl"]).toBe("108px");
    expect(allTokens["control.avatar.add-icon.size"]).toBe("16px");
    expect(allTokens["control.chip.icon.size"]).toBe("13px");
    expect(allTokens["control.menu.icon.size"]).toBe("14px");
    expect(allTokens["control.feedback.icon.size"]).toBe("18px");
    expect(allTokens["control.feedback.body-gap"]).toBe("0px");
    expect(allTokens["control.toast.min-height"]).toBe("46px");
    expect(allTokens["control.inline-alert.min-height"]).toBe("46px");
    expect(allTokens["control.field.icon.size"]).toBe("16px");
    expect(allTokens["control.select.item-icon.size"]).toBe("14px");
    expect(allTokens["control.checkbox.size"]).toBe("18px");
    expect(allTokens["control.toggle.track.width"]).toBe("40px");
    expect(allTokens["control.card.padding"]).toBe("16px");
    expect(allTokens["control.table.header.height"]).toBe("48px");
    expect(allTokens["control.table.action-column-width"]).toBe("44px");
    expect(allTokens["control.table.pagination.page-size-gap"]).toBe("8px");
    expect(allTokens["control.list.row.height"]).toBe("68px");
    expect(allTokens["control.list.row.padding-x"]).toBe("12px");
    expect(allTokens["control.list-icon.icon.size"]).toBe("15px");
    expect(allTokens["control.flow-node.width"]).toBe("168px");
    expect(allTokens["layout.crm-list-detail.list-width"]).toBe("190px");
    expect(allTokens["layout.crm-list-detail.main-width"]).toBe("780px");
    expect(allTokens["layout.crm-list-detail.main-wide-width"]).toBe("810px");
    expect(allTokens["layout.crm-list-detail.detail-width"]).toBe("330px");
    expect(allTokens["layout.crm-list-detail.gap"]).toBe("8px");
    expect(allTokens["layout.crm-task-drawer.compact-width"]).toContain("crm-checklist-drawer-width");
    expect(allTokens["control.crm-work-list-detail.filter-padding-x"]).toBe("8px");
    expect(allTokens["control.crm-work-list-detail.filter-gap"]).toBe("6px");
    expect(allTokens["control.crm-work-list-detail.filter-icon-size"]).toBe("14px");
    expect(allTokens["control.crm-work-list-detail.filter-count-size"]).toBe("18px");
    expect(allTokens["control.crm-work-list-detail.filter-count-padding-x"]).toBe("0px");
    expect(allTokens["layout.crm-work-list-detail.main-priority-rail-width"]).toBe("176px");
    expect(allTokens["control.crm-work-list-detail.main-priority-rail-padding"]).toBe("18px 8px 14px");
    expect(allTokens["control.crm-work-list-detail.main-priority-filter-padding-x"]).toBe("4px");
    expect(allTokens["control.crm-work-list-detail.main-priority-filter-gap"]).toBe("4px");
    expect(allTokens["control.crm-work-list-detail.main-priority-filter-icon-size"]).toBe("13px");
    expect(allTokens["control.crm-work-list-detail.main-priority-filter-count-size"]).toBe("18px");
    expect(allTokens["control.crm-work-list-detail.main-priority-filter-count-padding-x"]).toBe("0px");
    expect(allTokens["layout.crm-work-list-detail.compact-rail-width"]).toBe("166px");
    expect(allTokens["layout.crm-work-list-detail.wide-main-rail-width"]).toBe("166px");
    expect(allTokens["layout.crm-list-detail.columns"]).toContain("crm-list-detail-list-width");
    expect(allTokens["layout.crm-task-filter-bar.width"]).toBe("977px");
    expect(allTokens["layout.crm-page-filter-bar.tight-search-basis"]).toBe("264px");
    expect(allTokens["layout.crm-page-filter-bar.tight-filter-width"]).toBe("78px");
    expect(allTokens["control.crm-page-filter-bar.tight-action-padding-x"]).toBe("12px");
    expect(allTokens["control.crm-task-filter-bar.height"]).toBe("65px");
    expect(allTokens["control.crm-task-filter-bar.control-height"]).toBe("38px");
    expect(allTokens["layout.crm-task-queue-list.width"]).toBe("190px");
    expect(allTokens["control.crm-task-queue-list.item-height"]).toBe("40px");
    expect(allTokens["layout.crm-task-table.width"]).toBe("780px");
    expect(allTokens["layout.crm-task-table.columns"]).toBe("42px 150px 74px 64px 88px 116px 56px 119px 49px");
    expect(allTokens["control.crm-task-table.row-height"]).toBe("73px");
    expect(allTokens["layout.crm-approval-table.title-column"]).toBe("20%");
    expect(allTokens["layout.crm-approval-table.type-column"]).toBe("12%");
    expect(allTokens["layout.crm-approval-table.origin-column"]).toBe("10%");
    expect(allTokens["layout.crm-approval-table.requester-column"]).toBe("11%");
    expect(allTokens["layout.crm-approval-table.activity-column"]).toBe("11%");
    expect(allTokens["layout.crm-product-shell.main.header-spacious-height"]).toBe("72px");
    expect(allTokens["layout.crm-product-shell.main.header-compact-stacked-height"]).toBe("72px");
    expect(allTokens["layout.crm-product-shell.main.header-dashboard-height"]).toBe("74px");
    expect(allTokens["layout.crm-product-shell.main.header-stacked-height"]).toBe("96px");
    expect(allTokens["layout.crm-product-shell.main.header-stacked-meta-height"]).toBe("130px");
    expect(allTokens["layout.crm-product-shell.viewport-gutter"]).toBe("clamp(8px, 0.7vw, 14px)");
    expect(allTokens["layout.crm-product-shell.topbar.dashboard-nav-left"]).toBe("349px");
    expect(allTokens["layout.crm-product-shell.topbar.dashboard-nav-top"]).toBe("18px");
    expect(allTokens["layout.crm-product-shell.topbar.dashboard-nav-gap"]).toBe("37px");
    expect(allTokens["layout.crm-product-shell.topbar.dashboard-actions-gap"]).toBe("27px");
    expect(allTokens["layout.crm-product-shell.dashboard-brand-left"]).toBe("37px");
    expect(allTokens["control.crm-product-shell.dashboard-brand-width"]).toBe("160px");
    expect(allTokens["layout.crm-product-shell.header-dashboard-copy-offset-y"]).toBe("18px");
    expect(allTokens["layout.crm-product-shell.header-stacked-copy-offset-y"]).toBe("14px");
    expect(allTokens["layout.crm-product-shell.header-stacked-copy-gap"]).toBe("8px");
    expect(allTokens["layout.crm-product-shell.content-work-list-padding"]).toBe("0 28px 28px 27px");
    expect(allTokens["layout.crm-product-shell.content-work-list-compact-padding"]).toBe("0 28px 28px 11px");
    expect(allTokens["layout.crm-product-shell.content-work-list-wide-padding"]).toBe("0 28px 28px 16px");
    expect(allTokens["layout.crm-product-shell.content-main-priority-padding"]).toBe("0 28px 27px 16px");
    expect(allTokens["layout.crm-product-shell.content-kanban-padding"]).toBe("0 28px 28px 24px");
    expect(allTokens["layout.crm-product-shell.content-dashboard-padding"]).toBe("0 41px 28px 52px");
    expect(allTokens["layout.crm-product-shell.floating-drawer-top"]).toBe("120px");
    expect(allTokens["layout.crm-product-shell.replacement-floating-drawer-top"]).toBe("104px");
    expect(allTokens["layout.crm-product-shell.tenant-floating-drawer-top"]).toBe("99px");
    expect(allTokens["layout.crm-product-shell.tenant-floating-drawer-bottom"]).toBe("4px");
    expect(allTokens["layout.crm-product-shell.floating-drawer-right"]).toBe("14px");
    expect(allTokens["layout.crm-product-shell.floating-drawer-bottom"]).toBe("24px");
    expect(allTokens["layout.crm-product-shell.floating-drawer-reserved-width"]).toBe("var(--taliya-control-drawer-width-sm)");
    expect(allTokens["control.crm-replacement-drawer.title-offset-top"]).toBe("28px");
    expect(allTokens["control.crm-replacement-drawer.credit-fact-row-height"]).toBe("45px");
    expect(allTokens["control.crm-replacement-drawer.footer-gap"]).toBe("5px");
    expect(allTokens["layout.crm-three-pane.width"]).toBe("1294px");
    expect(allTokens["layout.crm-three-pane.columns"]).toContain("crm-three-pane-center-width");
    expect(allTokens["layout.crm-right-panel.width"]).toBe("1390px");
    expect(allTokens["layout.crm-right-panel.columns"]).toContain("crm-right-panel-main-width");
    expect(allTokens["layout.crm-right-panel.drawer-wide-columns"]).toContain("crm-right-panel-drawer-wide-main-width");
    expect(allTokens["layout.crm-right-panel.drawer-panel-offset-x"]).toBe("-8px");
    expect(allTokens["layout.crm-dashboard.columns-asymmetrical"]).toContain("1.35fr");
    expect(allTokens["layout.field-grid.columns-4"]).toBe("repeat(4, minmax(0, 1fr))");
    expect(allTokens["control.field.textarea.compact-min-height"]).toBe("72px");
    expect(allTokens["control.tag-input.chip-height"]).toBe("22px");
    expect(allTokens["control.tag-input.remove-size"]).toBe("14px");
    expect(allTokens["layout.crm-dashboard.columns-agenda"]).toBe("minmax(220px, 280px) minmax(0, 1fr)");
    expect(allTokens["layout.crm-dashboard.columns-reports"]).toBe("repeat(6, minmax(0, 1fr))");
    expect(allTokens["control.crm-report-card.dashboard-height"]).toBe("210px");
    expect(allTokens["layout.crm-dashboard.today-width"]).toBe("100%");
    expect(allTokens["layout.crm-dashboard.today-columns"]).toBe("minmax(0, 393fr) minmax(0, 316fr) minmax(0, 270fr) minmax(0, 487fr)");
    expect(allTokens["layout.crm-dashboard.today-rows"]).toBe("minmax(255px, auto) minmax(230px, auto) minmax(194px, auto)");
    expect(allTokens["layout.crm-payment-drawer.width"]).toBe("399px");
    expect(allTokens["layout.crm-payment-drawer.compact-width"]).toBe("323px");
    expect(allTokens["layout.crm-payment-drawer.fact-columns"]).toBe("18px 112px minmax(0, 1fr)");
    expect(allTokens["control.crm-payment-drawer.primary-height"]).toBe("40px");
    expect(allTokens["control.crm-operational-row.dense-height"]).toBe("43px");
    expect(allTokens["control.crm-operational-row.schedule-dense-height"]).toBe("41px");
    expect(allTokens["control.crm-operational-panel.schedule-dense-rows-margin-top"]).toBe("4px");
    expect(allTokens["layout.crm-activity-feed.width"]).toBe("100%");
    expect(allTokens["layout.crm-activity-feed.height"]).toBe("auto");
    expect(allTokens["control.crm-task-drawer.section-gap"]).toBe("14px");
    expect(allTokens["control.crm-task-drawer.compact-header-min-height"]).toBe("122px");
    expect(allTokens["control.crm-task-drawer.compact-fact-row-height"]).toBe("28px");
    expect(allTokens["control.crm-task-drawer.compact-copilot-icon-size"]).toBe("18px");
    expect(allTokens["layout.crm-task-drawer.conversation-footer-columns"]).toBe("96px 76px 90px 74px");
    expect(allTokens["layout.crm-case-drawer.shell-height"]).toBe("var(--taliya-layout-viewport-height)");
    expect(allTokens["layout.crm-case-drawer.shell-z-index"]).toBe("50");
    expect(allTokens["control.crm-case-drawer.header-grid-rows"]).toBe("50px auto auto");
    expect(allTokens["control.crm-case-drawer.header-padding-top"]).toBe("24px");
    expect(allTokens["layout.crm-operation-activity-table.row-columns"]).toContain("minmax(190px, 1fr)");
    expect(allTokens["control.crm-activity-feed.row-height"]).toBe("64px");
    expect(allTokens["control.crm-activity-feed.icon-size"]).toBe("35px");
    expect(allTokens["layout.crm-weekly-calendar.compact-width"]).toBe("100%");
    expect(allTokens["layout.crm-weekly-calendar.compact-columns"]).toBe("48px repeat(5, minmax(0, 1fr))");
    expect(allTokens["control.crm-weekly-calendar.event-width-compact"]).toBe("calc(var(--taliya-layout-crm-weekly-calendar-day-width) - 16px)");
    expect(allTokens["color.crm-activity-feed.blue"]).toBe("#1473FF");
    expect(allTokens["control.crm-operation-activity-table.padding"]).toBe("10px 20px");
    expect(allTokens["control.crm-operation-activity-table.row-height"]).toBe("40px");
    expect(allTokens["layout.crm-audit-trail.width"]).toBe("502px");
    expect(allTokens["layout.crm-audit-trail.table-columns"]).toContain("78px");
    expect(allTokens["layout.crm-audit-trail.open-column"]).toBe("50px");
    expect(allTokens["control.crm-audit-trail.height"]).toBe("184px");
    expect(allTokens["control.crm-audit-trail.table-row-height"]).toBe("21px");
    expect(allTokens["color.crm-audit-trail.alert-fg"]).toBe("#E65F00");
    expect(allTokens["layout.crm-kanban.board-width"]).toBe("1284px");
    expect(allTokens["layout.crm-page-quick-filters.width"]).toBe("220px");
    expect(allTokens["color.crm-page-quick-filter.selected-soft-bg"]).toBe("var(--taliya-color-crm-kanban-manual-bg)");
    expect(allTokens["color.crm-page-quick-filter.selected-soft-fg"]).toBe("var(--taliya-color-crm-kanban-manual-fg)");
    expect(allTokens["layout.crm-kanban.column-width"]).toBe("195px");
    expect(allTokens["layout.crm-kanban.rail-width"]).toContain("crm-page-quick-filters-width");
    expect(allTokens["layout.crm-kanban.column-min-height"]).toBe("100%");
    expect(allTokens["control.crm-kanban-column.count-size"]).toBe("17px");
    expect(allTokens["color.crm-kanban-column.count-bg"]).toBe("rgba(230, 233, 239, 0.92)");
    expect(allTokens["layout.crm-weekly-calendar.width"]).toBe("765px");
    expect(allTokens["layout.crm-weekly-calendar.short-height"]).toBe("720px");
    expect(allTokens["layout.crm-weekly-calendar.columns"]).toBe("58px repeat(5, 137px)");
    expect(allTokens["control.crm-weekly-calendar.event-width"]).toBe("122px");
    expect(allTokens["layout.crm-class-card.width"]).toBe("122px");
    expect(allTokens["layout.crm-class-card.selected-height"]).toBe("86px");
    expect(allTokens["control.crm-class-card.status-font-size"]).toBe("7px");
    expect(allTokens["color.crm-class-card.warning-fg"]).toBe("#E65F00");
    expect(allTokens["layout.crm-roster.width"]).toBe("375px");
    expect(allTokens["layout.crm-roster.columns"]).toBe("52px minmax(0, 1fr) 122px 31px");
    expect(allTokens["control.crm-roster.row-height"]).toBe("73.2px");
    expect(allTokens["control.crm-roster.chip-height"]).toBe("24px");
    expect(allTokens["color.crm-roster-warning.fg"]).toBe("#FF6F16");
    expect(allTokens["shadow.crm-checklist-table.row-selected"]).toBe("none");
    expect(allTokens["layout.crm-checklist-table.status-column"]).toBe("10.75%");
    expect(allTokens["layout.crm-checklist-table.next-step-column"]).toBe("10.5%");
    expect(allTokens["layout.crm-mini-calendar.width"]).toBe("204px");
    expect(allTokens["layout.crm-mini-calendar.height"]).toBe("242px");
    expect(allTokens["control.crm-mini-calendar.day-size"]).toBe("24px");
    expect(allTokens["control.crm-mini-calendar.grid-row-gap"]).toBe("5px");
    expect(allTokens["color.crm-mini-calendar.selected-bg"]).toBe("#080A0D");
    expect(allTokens["layout.crm-setup-shell.width"]).toBe("1660px");
    expect(allTokens["layout.crm-setup-shell.columns"]).toBe("220px 978px 397px");
    expect(allTokens["layout.crm-setup-shell.bottom-bar-grid-column"]).toBe("1 / 4");
    expect(allTokens["layout.crm-setup-bottom-bar.width"]).toBe("1630px");
    expect(allTokens["layout.crm-setup-bottom-bar.height"]).toBe("73px");
    expect(allTokens["layout.crm-setup-welcome.width"]).toBe("690px");
    expect(allTokens["layout.crm-setup-welcome.height"]).toBe("470px");
    expect(allTokens["layout.crm-setup-welcome.field-width"]).toBe("600px");
    expect(allTokens["layout.crm-setup-choice-card.width"]).toBe("280px");
    expect(allTokens["layout.crm-setup-choice-card.height"]).toBe("90px");
    expect(allTokens["layout.crm-setup-import-source-card.width"]).toBe("166px");
    expect(allTokens["layout.crm-setup-import-source-card.height"]).toBe("75px");
    expect(allTokens["layout.crm-setup-review-panel.width"]).toBe("1064px");
    expect(allTokens["layout.crm-setup-review-panel.height"]).toBe("807px");
    expect(allTokens["layout.crm-setup-agent-chat.width"]).toBe("675px");
    expect(allTokens["layout.crm-setup-agent-chat.height"]).toBe("1381px");
    expect(allTokens["shadow.crm-setup-agent-chat.panel"]).toContain("rgba(16, 20, 26");
    expect(allTokens["layout.crm-setup-block-header.width"]).toBe("735px");
    expect(allTokens["layout.crm-setup-block-header.height"]).toBe("84px");
    expect(allTokens["layout.crm-setup-stepper.width"]).toBe("220px");
    expect(allTokens["layout.crm-setup-stepper.height"]).toBe("738px");
    expect(allTokens["layout.crm-setup-stepper.header-height"]).toBe("86px");
    expect(allTokens["control.crm-setup-shell.panel-radius"]).toBe("15px");
    expect(allTokens["control.crm-setup-block-header.title-size"]).toBe("28px");
    expect(allTokens["control.crm-setup-block-header.chip-height"]).toBe("31px");
    expect(allTokens["control.crm-setup-bottom-bar.toggle-size"]).toBe("44px");
    expect(allTokens["control.crm-setup-bottom-bar.toggle-icon-size"]).toBe("18px");
    expect(allTokens["control.crm-setup-welcome.title-size"]).toBe("52px");
    expect(allTokens["control.crm-setup-welcome.button-height"]).toBe("65px");
    expect(allTokens["control.crm-setup-welcome.button-icon-size"]).toBe("22px");
    expect(allTokens["control.crm-setup-welcome.input-radius"]).toBe("18px");
    expect(allTokens["control.crm-setup-welcome.padding-top"]).toBe("28px");
    expect(allTokens["control.crm-setup-welcome.button-shadow"]).toBe("0 10px 24px rgba(16, 20, 26, 0.18)");
    expect(allTokens["control.crm-setup-choice-card.icon-size"]).toBe("30px");
    expect(allTokens["control.crm-setup-choice-card.gap"]).toBe("13px");
    expect(allTokens["control.crm-setup-choice-card.selected-dot-ring"]).toBe("2px");
    expect(allTokens["control.crm-setup-choice-card.title-size"]).toBe("15px");
    expect(allTokens["control.crm-setup-import-source-card.icon-size"]).toBe("24px");
    expect(allTokens["control.crm-setup-import-source-card.body-width"]).toBe("107px");
    expect(allTokens["control.crm-setup-import-source-card.title-size"]).toBe("11px");
    expect(allTokens["control.crm-setup-import-source-card.description-size"]).toBe("9px");
    expect(allTokens["control.crm-setup-review-panel.card-icon-size"]).toBe("24px");
    expect(allTokens["control.crm-setup-review-panel.footer-button-height"]).toBe("40px");
    expect(allTokens["control.crm-setup-agent-chat.composer-height"]).toBe("82px");
    expect(allTokens["control.crm-setup-agent-chat.send-size"]).toBe("62px");
    expect(allTokens["control.crm-setup-agent-chat.logo-mark-width"]).toBe("47px");
    expect(allTokens["control.crm-setup-agent-chat.message-one-height"]).toBe("209px");
    expect(allTokens["layout.crm-setup-human-help-cta.width"]).toBe("372px");
    expect(allTokens["layout.crm-setup-human-help-cta.height"]).toBe("83px");
    expect(allTokens["color.crm-setup-human-help-cta.link"]).toBe("#1F6FEF");
    expect(allTokens["control.crm-setup-stepper.connector-height"]).toBe("54px");
    expect(allTokens["control.crm-setup-stepper.source-padding-x"]).toBe("23px");
    expect(allTokens["color.crm-setup-shell.blue"]).toBe("#0D6BFF");
    expect(allTokens["color.crm-setup-welcome.bg"]).toBe("#FBFCFF");
    expect(allTokens["color.crm-setup-choice-card.selected-border"]).toBe("#2E75FF");
    expect(allTokens["color.crm-setup-import-source-card.selected-border"]).toBe("#2E75FF");
    expect(allTokens["color.crm-setup-review-panel.warning-fg"]).toBe("#F25C05");
    expect(allTokens["color.crm-setup-agent-chat.info-fg"]).toBe("#1C6FEF");
    expect(allTokens["color.crm-setup-block-header.warning-fg"]).toBe("#9A4B00");
    expect(allTokens["color.crm-setup-block-header.complete-fg"]).toBe("#0F7A3E");
    expect(allTokens["layout.crm-setup-bottom-bar.columns"]).toBe("278px 1px minmax(0, 1fr) 360px 1px 44px");
    expect(allTokens["layout.crm-access-shell.main-width"]).toBe("440px");
    expect(allTokens["layout.crm-access-shell.window-width"]).toBe("1528px");
    expect(allTokens["layout.crm-access-shell.window-height"]).toBe("852px");
    expect(allTokens["layout.crm-access-shell.content-width"]).toBe("966px");
    expect(allTokens["layout.crm-access-shell.centered-content-width"]).toBe("100%");
    expect(allTokens["layout.crm-access-shell.centered-content-placeholder-height"]).toBe("100%");
    expect(allTokens["layout.crm-access-shell.centered-logo-width"]).toBe("176px");
    expect(allTokens["layout.crm-access-shell.rail-card-width"]).toBe("475px");
    expect(allTokens["color.crm-access-shell.page-bg"]).toBe("var(--taliya-surface-app)");
    expect(allTokens["color.crm-access-shell.centered-main-bg"]).toBe("var(--taliya-surface-app)");
    expect(allTokens["color.crm-access-shell.footer-bg"]).toBe("var(--taliya-surface-panel)");
    expect(allTokens["color.crm-access-shell.content-bg"]).toBe("var(--taliya-surface-card)");
    expect(allTokens["color.crm-access-shell.browser-address-fg"]).toBe("rgba(16, 20, 26, 0.72)");
    expect(allTokens["control.crm-access-shell.browser-address.font-size"]).toBe("16px");
    expect(allTokens["control.crm-access-shell.browser-address.font-weight"]).toBe("400");
    expect(allTokens["control.crm-access-footer-links.font-size"]).toBe("16px");
    expect(allTokens["control.crm-access-footer-links.cluster-gap"]).toBe("38px");
    expect(allTokens["control.crm-access-footer-links.separator-size"]).toBe("16px");
    expect(allTokens["control.crm-access-footer-links.cluster-offset-y"]).toBe("4px");
    expect(allTokens["layout.crm-auth-card.signup-width"]).toBe("460px");
    expect(allTokens["layout.crm-auth-card.signin-width"]).toBe("523px");
    expect(allTokens["layout.crm-auth-card.signin-height"]).toBe("577px");
    expect(allTokens["layout.crm-auth-card.signup-padding"]).toBe("36px 41px 26px");
    expect(allTokens["layout.crm-auth-card.signin-padding"]).toBe("32px 33px 31px");
    expect(allTokens["control.crm-auth-card.social-icon-column"]).toBe("60px");
    expect(allTokens["control.crm-auth-card.title-size"]).toBe("28px");
    expect(allTokens["control.crm-auth-card.title-weight"]).toBe("600");
    expect(allTokens["control.crm-auth-card.subtitle-width"]).toBe("378px");
    expect(allTokens["control.crm-auth-card.button-size"]).toBe("16px");
    expect(allTokens["control.crm-auth-card.signup-header-margin-bottom"]).toBe("10px");
    expect(allTokens["control.crm-auth-card.signin-options-margin"]).toBe("13px 0 10px");
    expect(allTokens["color.crm-auth-card.primary-bg"]).toBe("#050505");
    expect(allTokens["color.crm-auth-card.bg"]).toBe("var(--taliya-surface-card)");
    expect(allTokens["color.crm-auth-card.control-bg"]).toBe("var(--taliya-surface-field)");
    expect(allTokens["color.crm-auth-card.primary-bg-start"]).toBe("#151515");
    expect(allTokens["shadow.crm-auth-card-primary"]).toContain("inset 0 1px 0");
    expect(allTokens["layout.crm-subscription-status-card.width"]).toBe("726px");
    expect(allTokens["layout.crm-subscription-status-card.content-width"]).toBe("592px");
    expect(allTokens["layout.crm-subscription-status-card.failed-width"]).toBe("706px");
    expect(allTokens["layout.crm-subscription-status-card.confirmed-width"]).toBe("546px");
    expect(allTokens["color.crm-subscription.title"]).toBe("#172033");
    expect(allTokens["color.crm-subscription.text-muted"]).toBe("rgba(46, 57, 83, 0.68)");
    expect(allTokens["color.crm-subscription.card-border"]).toBe("var(--taliya-border-subtle)");
    expect(allTokens["color.crm-subscription.card-bg"]).toBe("var(--taliya-surface-card)");
    expect(allTokens["color.crm-subscription.verifying-card-bg"]).toBe("#FBFCFE");
    expect(allTokens["color.crm-subscription.action-shadow"]).toBe("rgba(16, 20, 26, 0.075)");
    expect(allTokens["color.crm-subscription.secure-bg"]).toBe("rgba(22, 163, 74, 0.045)");
    expect(allTokens["color.crm-subscription.failed-callout-bg"]).toBe("rgba(245, 158, 11, 0.045)");
    expect(allTokens["color.crm-subscription.failed-callout-border"]).toBe("rgba(245, 158, 11, 0.22)");
    expect(allTokens["color.crm-subscription.failed-callout-body"]).toBe("rgba(46, 57, 83, 0.56)");
    expect(allTokens["color.crm-subscription.failed-details-border"]).toBe("var(--taliya-surface-field-disabled)");
    expect(allTokens["color.crm-subscription.failed-header-subcopy"]).toBe("rgba(46, 57, 83, 0.66)");
    expect(allTokens["color.crm-subscription.failed-link"]).toBe("rgba(46, 57, 83, 0.72)");
    expect(allTokens["color.crm-subscription.failed-supporting"]).toBe("rgba(46, 57, 83, 0.58)");
    expect(allTokens["color.crm-subscription.failed-action-fg"]).toBe("rgba(255, 255, 255, 0.88)");
    expect(allTokens["layout.crm-confirmed-setup-handoff.width"]).toBe("607px");
    expect(allTokens["layout.crm-checkout-review-panel.width"]).toBe("1076px");
    expect(allTokens["layout.crm-checkout-payment-card.width"]).toBe("399px");
    expect(allTokens["color.crm-checkout-payment-card.bg"]).toBe("var(--taliya-surface-card)");
    expect(allTokens["layout.crm-plan-summary-card.active-width"]).toBe("292px");
    expect(allTokens["layout.crm-plan-summary-card.review-width"]).toBe("636px");
    expect(allTokens["layout.crm-invoice-table.width"]).toBe("876px");
    expect(allTokens["layout.crm-invoice-table.columns"]).toContain("136px");
    expect(allTokens["layout.crm-invoice-table.actions-column"]).toBe("146px");
    expect(allTokens["layout.crm-addon-card.width"]).toBe("269px");
    expect(allTokens["layout.crm-addon-card.panel-gap"]).toBe("20px");
    expect(allTokens["layout.crm-settings-hub-card.width"]).toBe("332px");
    expect(allTokens["layout.crm-settings-section.width"]).toBe("944px");
    expect(allTokens["layout.crm-settings-section.row-columns"]).toContain("104px");
    expect(allTokens["layout.crm-conversation-list.width"]).toBe("483px");
    expect(allTokens["layout.crm-conversation-list.row-columns"]).toContain("50px");
    expect(allTokens["layout.crm-conversation-thread.width"]).toBe("502px");
    expect(allTokens["layout.crm-conversation-thread.message-columns"]).toContain("42px");
    expect(allTokens["layout.crm-rule-row.width"]).toBe("860px");
    expect(allTokens["layout.crm-rule-row.columns"]).toContain("273px");
    expect(allTokens["layout.crm-permission-matrix.width"]).toBe("851px");
    expect(allTokens["layout.crm-permission-matrix.columns"]).toContain("386px");
    expect(allTokens["layout.crm-agent-catalog.columns"]).toContain("repeat(3");
    expect(allTokens["layout.crm-agent-catalog.gap"]).toBe("16px");
    expect(allTokens["layout.crm-simulation-runner.columns"]).toContain("292px");
    expect(allTokens["layout.crm-simulation-runner.grid-offset-y"]).toBe("10px");
    expect(allTokens["layout.crm-simulation-runner.timeline-panel-gap"]).toBe("14px");
    expect(allTokens["control.crm-simulation-runner.phone-min-height"]).toBe("566px");
    expect(allTokens["control.crm-simulation-runner.phone-header-min-height"]).toBe("56px");
    expect(allTokens["control.crm-simulation-runner.timeline-title-height"]).toBe("22px");
    expect(allTokens["control.crm-simulation-runner.timeline-status-left"]).toBe("142px");
    expect(allTokens["control.crm-simulation-runner.timeline-status-dot-display"]).toBe("none");
    expect(allTokens["control.crm-phone-preview.header-columns"]).toBe("24px 40px minmax(0, 1fr) 28px");
    expect(allTokens["control.crm-phone-preview.header-subtitle-size"]).toBe("10px");
    expect(allTokens["control.crm-phone-preview.message-body-weight"]).toBe("400");
    expect(allTokens["control.crm-phone-preview.receipt-width"]).toBe("90%");
    expect(allTokens["control.crm-phone-preview.receipt-offset-x"]).toBe("-8px");
    expect(allTokens["control.crm-phone-preview.receipt-offset-y"]).toBe("-20px");
    expect(allTokens["control.crm-phone-preview.receipt-text-size"]).toBe("12px");
    expect(allTokens["control.crm-phone-preview.composer-columns"]).toBe("236px 44px");
    expect(allTokens["control.crm-phone-preview.composer-padding"]).toBe("8px 16px 32px");
    expect(allTokens["control.crm-phone-preview.send-size"]).toBe("44px");
    expect(allTokens["control.crm-phone-preview.send-icon-size"]).toBe("19px");
    expect(allTokens["control.crm-phone-preview.receipt-icon-size"]).toBe("38px");
    expect(allTokens["control.crm-phone-preview.receipt-title-size"]).toBe("15px");
    expect(allTokens["control.crm-phone-preview.send-icon-stroke-width"]).toBe("1.75");
    expect(allTokens["color.crm-phone-preview.header-bg"]).toContain("#00694F");
    expect(allTokens["color.crm-phone-preview.outbound-bg"]).toBe("#E0FBDC");
    expect(allTokens["color.crm-phone-preview.outbound-border"]).toBe("rgba(22, 163, 74, 0.20)");
    expect(allTokens["color.crm-phone-preview.send-bg"]).toBe("#050505");
    expect(allTokens["layout.crm-mode-selector.flow-columns"]).toContain("repeat(5");
    expect(allTokens["layout.crm-preflight-checklist.columns"]).toContain("repeat(5");
    expect(allTokens["layout.crm-execution-receipt.followup-columns"]).toContain("repeat(2");
    expect(allTokens["layout.crm-student-summary.columns"]).toContain("repeat(5");
    expect(allTokens["layout.crm-student-header.action-columns"]).toBe("repeat(2, 193px)");
    expect(allTokens["layout.crm-profile-tabs.width"]).toBe("1042px");
    expect(allTokens["control.crm-profile-tabs.height"]).toBe("58px");
    expect(allTokens["control.crm-profile-tabs.tab-height"]).toBe("38px");
    expect(allTokens["control.crm-profile-tabs.gap"]).toBe("25px");
    expect(allTokens["color.crm-profile-tabs.text"]).toBe("#25385F");
    expect(allTokens["shadow.crm-profile-tabs-active"]).toContain("0 9px 18px");
    expect(allTokens["layout.crm-relationship-list.columns"]).toBe("104px 34px 104px 34px 104px");
    expect(allTokens["layout.crm-payment-case-card.width"]).toBe("350px");
    expect(allTokens["layout.crm-finance-kanban-card.width"]).toBe("183px");
    expect(allTokens["layout.crm-reconciliation-row.width"]).toBe("832px");
    expect(allTokens["control.crm-surface.icon-size"]).toBe("38px");
    expect(allTokens["layout.crm-kanban.card-fact-columns"]).toBe("56px minmax(0, 1fr)");
    expect(allTokens["control.crm-kanban-card.min-height"]).toBe("150px");
    expect(allTokens["control.crm-kanban-card.title-size"]).toBe("12px");
    expect(allTokens["control.crm-kanban-card.text-size"]).toBe("10px");
    expect(allTokens["control.crm-kanban-card.chip-font-size"]).toBe("9px");
    expect(allTokens["control.crm-kanban-card.menu-size"]).toBe("18px");
    expect(allTokens["control.crm-kanban-card.menu-icon-size"]).toBe("13px");
    expect(allTokens["color.crm-kanban-blocked.fg"]).toBe("#FF2B31");
    expect(allTokens["control.crm-agent-card.min-height"]).toBe("216px");
    expect(allTokens["control.crm-agent-card.padding"]).toBe("20px");
    expect(allTokens["control.crm-agent-card.column-gap"]).toBe("24px");
    expect(allTokens["control.crm-agent-card.icon-size"]).toBe("76px");
    expect(allTokens["control.crm-agent-routine-card.padding"]).toBe("24px");
    expect(allTokens["control.crm-agent-routine-card.title-size"]).toBe("19px");
    expect(allTokens["control.crm-agent-routine-card.text-size"]).toBe("14px");
    expect(allTokens["control.crm-agent-flow-section-panel.padding"]).toBe("20px");
    expect(allTokens["control.crm-agent-flow-section-panel-mode.min-height"]).toBe("208px");
    expect(allTokens["control.crm-agent-flow-section-panel-mode.compact-min-height"]).toBe("150px");
    expect(allTokens["control.crm-agent-flow-section-panel.title-size"]).toBe("14px");
    expect(allTokens["control.crm-agent-routine-flow-card.min-height"]).toBe("210px");
    expect(allTokens["control.crm-agent-routine-flow-card.icon-size"]).toBe("58px");
    expect(allTokens["control.crm-agent-routine-flow-card.button-height"]).toBe("24px");
    expect(allTokens["control.crm-mode-card.flow-min-height"]).toBe("56px");
    expect(allTokens["control.crm-mode-card.flow-icon-size"]).toBe("24px");
    expect(allTokens["control.crm-mode-card.flow-padding-y"]).toBe("8px");
    expect(allTokens["control.crm-mode-card.flow-padding-x"]).toBe("10px");
    expect(allTokens["control.crm-mode-card.flow-gap"]).toBe("10px");
    expect(allTokens["control.crm-mode-card.flow-border-color"]).toBe("rgba(16, 20, 26, 0.12)");
    expect(allTokens["control.crm-mode-card.flow-title-color"]).toBe("rgba(16, 20, 26, 0.92)");
    expect(allTokens["control.crm-mode-card.flow-title-size"]).toBe("11px");
    expect(allTokens["control.crm-mode-card.flow-title-line-height"]).toBe("14px");
    expect(allTokens["control.crm-mode-card.flow-title-weight"]).toBe("650");
    expect(allTokens["control.crm-mode-card.check-size"]).toBe("18px");
    expect(allTokens["control.crm-flow-builder.title-size"]).toBe("18px");
    expect(allTokens["control.crm-flow-builder.title-line-height"]).toBe("24px");
    expect(allTokens["control.crm-flow-builder.title-weight"]).toBe("650");
    expect(allTokens["layout.crm-flow-builder.compact-columns"]).toContain("1.18fr");
    expect(allTokens["control.crm-flow-step-card.title-size"]).toBe("14px");
    expect(allTokens["control.crm-flow-step-card.title-line-height"]).toBe("19px");
    expect(allTokens["control.crm-flow-step-card.description-size"]).toBe("12px");
    expect(allTokens["control.crm-flow-step-card.description-line-height"]).toBe("17px");
    expect(allTokens["control.crm-flow-step-card.compact-title-size"]).toBe("13px");
    expect(allTokens["control.crm-flow-step-card.compact-last-padding-left"]).toBe("0px");
    expect(allTokens["control.crm-flow-step-card.compact-header-gap"]).toBe("2px");
    expect(allTokens["control.crm-flow-step-card.compact-icon-size"]).toBe("13px");
    expect(allTokens["control.crm-flow-step-card.compact-body-color"]).toBe("rgba(16, 20, 26, 0.56)");
    expect(allTokens["control.crm-flow-step-card.compact-divider-color"]).toBe("rgba(16, 20, 26, 0.04)");
    expect(allTokens["control.crm-flow-step-card.compact-info-icon-color"]).toBe("#0D6BFF");
    expect(allTokens["control.crm-flow-step-card.compact-success-color"]).toBe("#0F9A4A");
    expect(allTokens["control.crm-flow-step-card.compact-danger-color"]).toBe("#FF2B31");
    expect(allTokens["control.crm-flow-builder.connector-color"]).toBe("rgba(16, 20, 26, 0.18)");
    expect(allTokens["layout.crm-agent-flow-settings-panel.columns"]).toBe("218px 214px 285px 234px");
    expect(allTokens["control.crm-agent-flow-settings-panel.after-builder-offset"]).toBe("-8px");
    expect(allTokens["control.crm-agent-flow-settings-panel.padding-x"]).toBe("24px");
    expect(allTokens["control.crm-agent-flow-settings-panel.title-size"]).toBe("15px");
    expect(allTokens["control.crm-agent-flow-settings-panel.title-margin-bottom"]).toBe("12px");
    expect(allTokens["control.crm-agent-flow-settings-panel.title-line-height"]).toBe("21px");
    expect(allTokens["control.crm-agent-flow-settings-panel.field-grid-gap"]).toBe("8px 30px");
    expect(allTokens["control.crm-agent-flow-settings-panel.hint-color"]).toBe("rgba(16, 20, 26, 0.36)");
    expect(allTokens["control.crm-agent-flow-settings-panel.select-font-size"]).toBe("12px");
    expect(allTokens["control.crm-agent-flow-settings-panel.tag-chip-height"]).toBe("18px");
    expect(allTokens["control.crm-agent-flow-settings-panel.tag-input-gap"]).toBe("2px");
    expect(allTokens["control.crm-agent-flow-settings-panel.tag-input-padding"]).toBe("3px");
    expect(allTokens["control.crm-agent-flow-settings-panel.tag-chip-padding-x"]).toBe("5px");
    expect(allTokens["control.crm-agent-flow-settings-panel.tag-chip-bg"]).toBe("rgba(16, 20, 26, 0.05)");
    expect(allTokens["control.crm-agent-flow-settings-panel.tag-chip-color"]).toBe("rgba(16, 20, 26, 0.68)");
    expect(allTokens["control.crm-agent-flow-settings-panel.stack-offset-y"]).toBe("-17px");
    expect(allTokens["control.crm-agent-flow-settings-panel.textarea-min-height"]).toBe("61px");
    expect(allTokens["control.crm-agent-flow-settings-panel.textarea-padding"]).toBe("7px");
    expect(allTokens["control.crm-agent-flow-settings-panel.textarea-color"]).toBe("rgba(20, 25, 34, 0.52)");
    expect(allTokens["control.crm-agent-flow-settings-panel.textarea-resize"]).toBe("none");
    expect(allTokens["control.crm-agent-flow-settings-panel.message-label-color"]).toBe("rgba(16, 20, 26, 0.72)");
    expect(allTokens["control.crm-agent-flow-settings-panel.stack-gap"]).toBe("7px");
    expect(allTokens["control.crm-agent-flow-settings-panel.stack-height"]).toBe("96px");
    expect(allTokens["control.crm-agent-flow-settings-panel.stack-overflow"]).toBe("visible");
    expect(allTokens["control.crm-agent-flow-action-bar.primary-width"]).toBe("228px");
    expect(allTokens["control.crm-agent-flow-action-bar.secondary-width"]).toBe("203px");
    expect(allTokens["control.crm-agent-flow-action-bar.gap"]).toBe("9px");
    expect(allTokens["control.crm-agent-flow-action-bar.primary-bg"]).toBe("#000000");
    expect(allTokens["control.crm-agent-flow-action-bar.button-height"]).toBe("43px");
    expect(allTokens["control.crm-agent-flow-action-bar.button-font-size"]).toBe("13px");
    expect(allTokens["control.crm-agent-flow-action-bar.button-line-height"]).toBe("17px");
    expect(allTokens["control.crm-agent-flow-action-bar.icon-size"]).toBe("15px");
    expect(allTokens["control.crm-agent-flow-action-bar.primary-icon-fill"]).toBe("currentColor");
    expect(allTokens["control.crm-agent-flow-action-bar.primary-icon-stroke"]).toBe("none");
    expect(allTokens["control.crm-agent-flow-action-bar.primary-icon-offset-x"]).toBe("-2px");
    expect(allTokens["control.crm-agent-flow-action-bar.secondary-color"]).toBe("rgba(0, 0, 0, 0.9)");
    expect(allTokens["control.crm-agent-flow-action-bar.secondary-border-color"]).toBe("rgba(16, 20, 26, 0.11)");
    expect(allTokens["control.crm-agent-flow-action-bar.secondary-shadow"]).toBe("0 1px 2px rgba(16, 20, 26, 0.04)");
    expect(allTokens["control.crm-agent-flow-action-bar.secondary-icon-color"]).toBe("rgba(0, 0, 0, 0.86)");
    expect(allTokens["control.crm-preflight-checklist.panel-min-height"]).toBe("98px");
    expect(allTokens["control.crm-preflight-checklist.status-size"]).toBe("14px");
    expect(allTokens["control.crm-scenario-card.action-size"]).toBe("18px");
    expect(allTokens["control.crm-execution-receipt.timeline-row-height"]).toBe("58px");
    expect(allTokens["control.crm-phone-preview.width"]).toBe("360px");
    expect(allTokens["control.crm-phone-preview.receipt-icon-size"]).toBe("38px");
    expect(allTokens["color.crm-phone-preview.receipt-icon-bg"]).toBe("#0B6B52");
    expect(allTokens["color.crm-phone-preview.wallpaper-mark"]).toContain("rgba(16, 20, 26");
    expect(allTokens["color.crm-relationship-marker.bg"]).toBe("var(--taliya-color-accent-info)");
    expect(allTokens["color.crm-subscription.progress-current"]).toBe("#37BEB2");
    expect(allTokens["color.crm-subscription.link"]).toBe("#52617E");
    expect(allTokens["color.crm-subscription.detail-icon"]).toBe("#1F66E5");
    expect(allTokens["color.crm-subscription.confirmed-icon-bg"]).toBe("var(--taliya-surface-card)");
    expect(allTokens["color.crm-subscription.confirmed-icon-ring"]).toBe("#C4F7D3");
    expect(allTokens["color.crm-subscription.confirmed-icon-fg"]).toBe("#08D044");
    expect(allTokens["color.crm-subscription.release-note-bg"]).toBe("rgba(22, 163, 74, 0.04)");
    expect(allTokens["color.crm-subscription.primary-action-bg-start"]).toBe("#171B23");
    expect(allTokens["color.crm-subscription.primary-action-bg-end"]).toBe("#05070B");
    expect(allTokens["color.crm-subscription.failed-action-bg-start"]).toBe("#171C26");
    expect(allTokens["color.crm-subscription.failed-action-bg-end"]).toBe("#10141D");
    expect(allTokens["color.crm-subscription.failed-action-highlight"]).toBe("rgba(255, 255, 255, 0.055)");
    expect(allTokens["color.crm-subscription.failed-action-shadow"]).toBe("rgba(16, 20, 26, 0.045)");
    expect(allTokens["color.crm-checkout-payment-card.link"]).toBe("#5869D6");
    expect(allTokens["color.crm-plan-summary.icon-bg"]).toBe("rgba(46, 114, 255, 0.10)");
    expect(allTokens["color.crm-plan-summary.success"]).toBe("#20C86F");
    expect(allTokens["color.crm-invoice-table.open-bg"]).toBe("#FBEDE8");
    expect(allTokens["color.crm-invoice-table.paid-fg"]).toBe("#0F9A4A");
    expect(allTokens["color.crm-addon-card.consult-bg"]).toBe("#F1E7FF");
    expect(allTokens["color.crm-addon-card.action-primary-bg"]).toBe("var(--taliya-raw-black-950)");
    expect(allTokens["color.crm-settings-hub-card.ready-bg"]).toBe("#DFF7E8");
    expect(allTokens["color.crm-settings-hub-card.text"]).toBe("#52617E");
    expect(allTokens["color.crm-settings-hub-card.review-fg"]).toBe("#E65F00");
    expect(allTokens["color.crm-settings-section.toggle-on-bg"]).toBe("#0D6BFF");
    expect(allTokens["color.crm-settings-section.muted"]).toBe("#25385F");
    expect(allTokens["color.crm-conversation-list.whatsapp"]).toBe("#16C75B");
    expect(allTokens["color.crm-conversation-list.row-selected-border"]).toBe("#A8C7FF");
    expect(allTokens["color.crm-conversation-thread.suggestion-bg"]).toBe("#F4EFFF");
    expect(allTokens["color.crm-conversation-thread.banner-bg"]).toBe("var(--taliya-status-warning-banner-bg)");
    expect(allTokens["color.crm-kanban-waiting.bg"]).toBe("var(--taliya-status-warning-waiting-bg)");
    expect(allTokens["color.crm-roster.hover-bg"]).toBe("var(--taliya-surface-control-hover-faint)");
    expect(allTokens["color.crm-setup-review-panel.review-bg"]).toBe("var(--taliya-status-warning-review-bg)");
    expect(allTokens["color.crm-setup-review-panel.blocking-bg"]).toBe("var(--taliya-status-danger-blocking-bg)");
    expect(allTokens["color.crm-settings-section.dirty-bg"]).toBe("var(--taliya-status-warning-dirty-bg)");
    expect(allTokens["color.crm-permission-matrix.dirty-bg"]).toBe("var(--taliya-status-warning-dirty-bg)");
    expect(allTokens["color.crm-conversation-list.waiting-bg"]).toBe("var(--taliya-status-warning-waiting-bg)");
    expect(allTokens["color.crm-rule-row.toggle-on-bg"]).toBe("#12AA42");
    expect(allTokens["color.crm-rule-row.select-border"]).toBe("#DCE1EA");
    expect(allTokens["color.crm-permission-matrix.index-bg"]).toBe("var(--taliya-color-accent-info)");
    expect(allTokens["color.crm-permission-matrix.toggle-on-bg"]).toBe("var(--taliya-color-text-primary)");
    expect(allTokens["control.stepper.marker.size"]).toBe("30px");
    expect(allTokens["control.stepper.vertical.row-min-height"]).toBe("58px");
    expect(allTokens["control.checklist.row-height"]).toBe("31px");
    expect(allTokens["control.metric-tile.min-height"]).toBe("124px");
    expect(allTokens["control.metric-tile.operational-min-height"]).toBe("84px");
    expect(allTokens["control.status-summary.icon-size"]).toBe("40px");
    expect(allTokens["control.status-summary.details-grid"]).toContain("repeat(3");
    expect(allTokens["control.crm-subscription-status-card.min-height"]).toBe("662px");
    expect(allTokens["control.crm-subscription-status-card.verifying-padding"]).toBe("4px 66px 6px");
    expect(allTokens["control.crm-subscription-status-card.failed-min-height"]).toBe("653px");
    expect(allTokens["control.crm-subscription-status-card.confirmed-min-height"]).toBe("525px");
    expect(allTokens["control.crm-subscription-status-card.confirmed-padding"]).toBe("30px 40px 28px");
    expect(allTokens["control.crm-subscription-status-card.confirmed-header-gap"]).toBe("24px");
    expect(allTokens["control.crm-subscription-status-card.summary-header-gap"]).toBe("8px");
    expect(allTokens["control.crm-subscription-status-card.title-block-offset-y"]).toBe("9px");
    expect(allTokens["control.crm-subscription-status-card.failed-title-block-offset-y"]).toBe("-12px");
    expect(allTokens["control.crm-subscription-status-card.verifying-header-height"]).toBe("164px");
    expect(allTokens["control.crm-subscription-status-card.verifying-card-gap"]).toBe("3px");
    expect(allTokens["control.crm-subscription-status-card.failed-body-gap"]).toBe("14px");
    expect(allTokens["control.crm-subscription-status-card.confirmed-body-gap"]).toBe("7px");
    expect(allTokens["control.crm-subscription-status-card.title-size"]).toBe("23px");
    expect(allTokens["control.crm-subscription-status-card.title-line-height"]).toBe("29px");
    expect(allTokens["control.crm-subscription-status-card.title-weight"]).toBe("560");
    expect(allTokens["control.crm-subscription-status-card.failed-title-size"]).toBe("24px");
    expect(allTokens["control.crm-subscription-status-card.failed-title-line-height"]).toBe("30px");
    expect(allTokens["control.crm-subscription-status-card.failed-icon-offset-y"]).toBe("-8px");
    expect(allTokens["control.crm-subscription-status-card.header-gap"]).toBe("4px");
    expect(allTokens["control.crm-subscription-status-card.body-gap"]).toBe("9px");
    expect(allTokens["color.crm-subscription.verifying-action-bg-start"]).toBe("#414A57");
    expect(allTokens["color.crm-subscription.secure-icon"]).toBe("#18B96A");
    expect(allTokens["color.crm-subscription.secure-content"]).toBe("rgba(46, 57, 83, 0.48)");
    expect(allTokens["control.crm-subscription-result-header.icon-size"]).toBe("56px");
    expect(allTokens["control.crm-subscription-result-header.title-size"]).toBe("30px");
    expect(allTokens["control.crm-subscription-result-header.description-line-height"]).toBe("24px");
    expect(allTokens["control.crm-subscription-status-row.height"]).toBe("54px");
    expect(allTokens["control.crm-subscription-status-row.failed-height"]).toBe("48px");
    expect(allTokens["control.crm-subscription-status-row.label-weight"]).toBe("600");
    expect(allTokens["control.crm-subscription-detail-row.text-weight"]).toBe("450");
    expect(allTokens["control.crm-subscription-detail-row.confirmed-height"]).toBe("54px");
    expect(allTokens["control.crm-subscription-primary-weight"]).toBe("450");
    expect(allTokens["control.crm-subscription-failed-primary-height"]).toBe("44px");
    expect(allTokens["control.crm-subscription-failed-primary-radius"]).toBe("20px");
    expect(allTokens["control.crm-subscription-failed-primary-shadow-y"]).toBe("5px");
    expect(allTokens["control.crm-subscription-callout-title-weight"]).toBe("600");
    expect(allTokens["control.crm-subscription-callout-body-offset-y"]).toBe("1px");
    expect(allTokens["control.crm-subscription-callout-icon-offset-y"]).toBe("-1px");
    expect(allTokens["control.crm-subscription-failed-detail-row-text-weight"]).toBe("420");
    expect(allTokens["control.crm-subscription-failed-link-weight"]).toBe("500");
    expect(allTokens["control.crm-subscription-secure-body-offset-y"]).toBe("-1px");
    expect(allTokens["control.crm-subscription-secure-icon-offset-y"]).toBe("-1px");
    expect(allTokens["control.crm-subscription-release-note-inline-bleed"]).toBe("-12px");
    expect(allTokens["control.crm-subscription-callout-icon-size"]).toBe("24px");
    expect(allTokens["control.crm-subscription-progress-marker-size"]).toBe("26px");
    expect(allTokens["control.crm-subscription-progress-verifying-margin-top"]).toBe("14px");
    expect(allTokens["control.crm-subscription-details-verifying-margin-top"]).toBe("14px");
    expect(allTokens["control.crm-subscription-secure-verifying-margin-top"]).toBe("2px");
    expect(allTokens["control.crm-subscription-primary-verifying-margin-top"]).toBe("12px");
    expect(allTokens["control.crm-subscription-footer-verifying-margin-top"]).toBe("30px");
    expect(allTokens["control.crm-checkout-review-panel.gap"]).toBe("41px");
    expect(allTokens["control.crm-checkout-payment-card.min-height"]).toBe("539px");
    expect(allTokens["control.crm-checkout-payment-card.primary-height"]).toBe("41px");
    expect(allTokens["control.crm-confirmed-setup-handoff.min-height"]).toBe("525px");
    expect(allTokens["control.crm-confirmed-setup-handoff.padding"]).toBe("20px 42px 30px");
    expect(allTokens["control.crm-confirmed-setup-handoff.header-bottom-gap"]).toBe("12px");
    expect(allTokens["control.crm-confirmed-setup-handoff.title-size"]).toBe("24px");
    expect(allTokens["control.crm-confirmed-setup-handoff.title-weight"]).toBe("600");
    expect(allTokens["control.crm-confirmed-setup-handoff.description-width"]).toBe("395px");
    expect(allTokens["control.crm-confirmed-setup-handoff.step-number-size"]).toBe("44px");
    expect(allTokens["control.crm-confirmed-setup-handoff.step-title-weight"]).toBe("600");
    expect(allTokens["control.crm-confirmed-setup-handoff.action-inline-bleed"]).toBe("-12px");
    expect(allTokens["control.crm-confirmed-setup-handoff.action-font-size"]).toBe("18px");
    expect(allTokens["control.crm-plan-summary-card.active-min-height"]).toBe("515px");
    expect(allTokens["control.crm-plan-summary-card.review-row-height"]).toBe("29px");
    expect(allTokens["control.crm-plan-summary-card.review-status-offset-x"]).toBe("-40px");
    expect(allTokens["control.crm-plan-summary-card.confirmed-min-height"]).toBe("524px");
    expect(allTokens["control.crm-plan-summary-card.confirmed-release-note-inline-bleed"]).toBe("-10px");
    expect(allTokens["control.crm-plan-summary-card.failed-row-height"]).toBe("37px");
    expect(allTokens["control.crm-invoice-table.min-height"]).toBe("314px");
    expect(allTokens["control.crm-invoice-table.action-height"]).toBe("32px");
    expect(allTokens["control.crm-addon-card.height"]).toBe("344px");
    expect(allTokens["control.crm-addon-card.radius"]).toBe("14px");
    expect(allTokens["control.crm-addon-card.icon-offset-x"]).toBe("5px");
    expect(allTokens["control.crm-addon-card.title-weight"]).toBe("600");
    expect(allTokens["control.crm-addon-card.text-size"]).toBe("15px");
    expect(allTokens["control.crm-addon-card.meta-size"]).toBe("14px");
    expect(allTokens["control.crm-addon-card.action-width"]).toBe("232px");
    expect(allTokens["control.crm-addon-card.action-bottom"]).toBe("29px");
    expect(allTokens["control.crm-addon-card.action-left"]).toBe("0px");
    expect(allTokens["control.crm-settings-hub-card.height"]).toBe("286px");
    expect(allTokens["control.crm-settings-hub-card.icon-glyph"]).toBe("45px");
    expect(allTokens["control.crm-settings-hub-card.icon-stroke"]).toBe("1");
    expect(allTokens["control.crm-settings-hub-card.icon-offset-x"]).toBe("-2px");
    expect(allTokens["control.crm-settings-hub-card.icon-glyph-offset-y"]).toBe("1px");
    expect(allTokens["control.crm-settings-hub-card.title-size"]).toBe("19px");
    expect(allTokens["control.crm-settings-hub-card.title-weight"]).toBe("650");
    expect(allTokens["control.crm-settings-hub-card.status-height"]).toBe("29px");
    expect(allTokens["control.crm-settings-hub-card.action-width"]).toBe("258px");
    expect(allTokens["control.crm-settings-hub-card.action-offset-y"]).toBe("0px");
    expect(allTokens["control.crm-settings-section.height"]).toBe("250px");
    expect(allTokens["control.crm-settings-section.row-height"]).toBe("51px");
    expect(allTokens["control.crm-settings-section.toggle-width"]).toBe("38px");
    expect(allTokens["control.crm-conversation-list.height"]).toBe("733px");
    expect(allTokens["control.crm-conversation-list.filter-gap"]).toBe("5px");
    expect(allTokens["control.crm-conversation-list.filter-font-size"]).toBe("11px");
    expect(allTokens["control.crm-conversation-list.row-height"]).toBe("112px");
    expect(allTokens["control.crm-conversation-list.avatar-size"]).toBe("42px");
    expect(allTokens["control.crm-conversation-list.page-size-icon-size"]).toBe("13px");
    expect(allTokens["control.crm-conversation-thread.height"]).toBe("753px");
    expect(allTokens["layout.crm-conversation-thread.header-columns"]).toBe("42px minmax(148px, 1fr) auto");
    expect(allTokens["control.crm-conversation-thread.action-height"]).toBe("31px");
    expect(allTokens["control.crm-conversation-thread.message-width"]).toBe("330px");
    expect(allTokens["control.crm-conversation-thread.suggestion-action-height"]).toBe("35px");
    expect(allTokens["control.crm-conversation-thread.composer-height"]).toBe("158px");
    expect(allTokens["control.crm-conversation-thread.composer-surface-height"]).toBe("153px");
    expect(allTokens["control.crm-conversation-thread.composer-button-icon-size"]).toBe("16px");
    expect(allTokens["control.crm-conversation-thread.template-height"]).toBe("34px");
    expect(allTokens["shadow.crm-conversation-thread-composer"]).toContain("rgba(16, 20, 26");
    expect(allTokens["layout.crm-context-panel.width"]).toBe("280px");
    expect(allTokens["control.crm-context-panel.height"]).toBe("762px");
    expect(allTokens["control.crm-context-panel.title-size"]).toBe("13.5px");
    expect(allTokens["color.crm-context-panel.link"]).toBe("#1473FF");
    expect(allTokens["layout.crm-integration-status-row.width"]).toBe("224px");
    expect(allTokens["layout.crm-integration-status-row.columns"]).toBe("71px minmax(0, 1fr)");
    expect(allTokens["color.crm-integration-status-row.bg"]).toBe("var(--taliya-surface-card)");
    expect(allTokens["color.crm-integration-status-row.pix"]).toBe("#04BFA9");
    expect(allTokens["color.crm-integration-status-row.blocked"]).toBe("#2A3656");
    expect(allTokens["control.crm-integration-status-row.height"]).toBe("72px");
    expect(allTokens["control.crm-integration-status-row.pix-tile-size"]).toBe("13px");
    expect(allTokens["control.crm-integration-status-row.helper-width"]).toBe("72px");
    expect(allTokens["control.crm-integration-status-row.status-icon-size"]).toBe("13px");
    expect(allTokens["layout.crm-unsaved-changes-bar.width"]).toBe("943px");
    expect(allTokens["layout.crm-unsaved-changes-bar.columns"]).toBe("146px minmax(0, 1fr) 240px");
    expect(allTokens["color.crm-unsaved-changes-bar.primary-bg"]).toBe("var(--taliya-raw-black-950)");
    expect(allTokens["color.crm-unsaved-changes-bar.cancel-border"]).toBe("#E1E5EE");
    expect(allTokens["control.crm-unsaved-changes-bar.height"]).toBe("51px");
    expect(allTokens["control.crm-unsaved-changes-bar.button-height"]).toBe("46px");
    expect(allTokens["control.crm-rule-row.height"]).toBe("35px");
    expect(allTokens["layout.crm-rule-row.control-width"]).toBe("259px");
    expect(allTokens["control.crm-rule-row.select-icon-size"]).toBe("12px");
    expect(allTokens["control.crm-rule-row.toggle-width"]).toBe("34px");
    expect(allTokens["control.comparison-table.row-height"]).toBe("14px");
    expect(allTokens["control.permission-table.status-width"]).toBe("94px");
    expect(allTokens["control.audit-table.avatar-size"]).toBe("14px");
    expect(allTokens["control.import-progress.min-height"]).toBe("188px");
    expect(allTokens["control.import-progress.icon-size"]).toBe("35px");
    expect(allTokens["control.relationship-card.width"]).toBe("104px");
    expect(allTokens["control.relationship-card.padding"]).toBe("12px 9px");
    expect(allTokens["control.relationship-card.featured-min-height"]).toBe("88px");
    expect(allTokens["control.relationship-card.meta-size"]).toBe("9px");
    expect(allTokens["control.crm-student-header.min-height"]).toBe("173px");
    expect(allTokens["control.crm-student-header.padding"]).toBe("24px 28px 19px");
    expect(allTokens["control.crm-student-header.gap"]).toBe("42px");
    expect(allTokens["control.crm-student-header.action-gap"]).toBe("10px");
    expect(allTokens["control.crm-student-header.contact-item-gap"]).toBe("32px");
    expect(allTokens["control.crm-student-summary.gap"]).toBe("6px");
    expect(allTokens["control.crm-relationship-panel.width"]).toBe("443px");
    expect(allTokens["control.crm-relationship-panel.marker-size"]).toBe("18px");
    expect(allTokens["control.crm-relationship-panel.legend-width"]).toBe("334px");
    expect(allTokens["control.crm-relationship-panel.legend-height"]).toBe("34px");
    expect(allTokens["control.crm-relationship-connector-line-width"]).toBe("16px");
    expect(allTokens["control.crm-payment-case-card.min-height"]).toBe("181px");
    expect(allTokens["control.crm-payment-case-card.gap"]).toBe("4px");
    expect(allTokens["control.crm-payment-case-card.row-meta-font-size"]).toBe("9px");
    expect(allTokens["control.crm-finance-kanban-card.min-height"]).toBe("135px");
    expect(allTokens["control.crm-finance-kanban-card.gap"]).toBe("6px");
    expect(allTokens["status.finance.today.fg"]).toBe("#E65F00");
    expect(allTokens["status.finance.validation.bg"]).toBe("rgba(139, 92, 246, 0.13)");
    expect(allTokens["color.crm-finance.payment-method-pix"]).toBe("#18A982");
    expect(allTokens["control.crm-reconciliation-row.height"]).toBe("55px");
    expect(allTokens["layout.crm-pipeline-card.width"]).toBe("239px");
    expect(allTokens["layout.crm-lead-summary-row.width"]).toBe("835px");
    expect(allTokens["layout.crm-trial-class-row.width"]).toBe("832px");
    expect(allTokens["layout.crm-enrollment-checklist.width"]).toBe("292px");
    expect(allTokens["layout.crm-agent-flow-drawer.width"]).toBe("399px");
    expect(allTokens["layout.crm-agent-flow-drawer.height"]).toBe("780px");
    expect(allTokens["layout.crm-agent-flow-drawer.info-columns"]).toBe("21px minmax(0, 1fr)");
    expect(allTokens["layout.crm-agent-flow-drawer.test-info-columns"]).toBe("21px minmax(0, 1fr)");
    expect(allTokens["layout.crm-right-panel.drawer-simulation-main-width"]).toBe("1138px");
    expect(allTokens["layout.crm-right-panel.drawer-simulation-rail-width"]).toBe("237px");
    expect(allTokens["layout.crm-class-drawer.width"]).toBe("399px");
    expect(allTokens["layout.crm-class-drawer.compact-width"]).toBe("323px");
    expect(allTokens["layout.crm-class-drawer.roster-columns"]).toBe("44px minmax(0, 1fr) auto 32px");
    expect(allTokens["layout.crm-class-drawer.compact-roster-columns"]).toBe("42px minmax(0, 1fr) 82px 28px");
    expect(allTokens["layout.crm-class-drawer.compact-footer-columns"]).toBe("1fr");
    expect(allTokens["layout.crm-lead-drawer.width"]).toBe("399px");
    expect(allTokens["layout.crm-lead-drawer.compact-width"]).toBe("324px");
    expect(allTokens["layout.crm-lead-drawer.fact-columns"]).toBe("18px 104px minmax(0, 1fr)");
    expect(allTokens["layout.crm-lead-drawer.history-columns"]).toBe("68px minmax(0, 1fr)");
    expect(allTokens["control.crm-lead-drawer.compact-padding"]).toBe("14px 18px 16px");
    expect(allTokens["control.crm-lead-drawer.divider-margin"]).toBe("8px");
    expect(allTokens["control.crm-lead-drawer.copilot-padding"]).toBe("10px");
    expect(allTokens["control.crm-lead-drawer.notice-padding"]).toBe("6px");
    expect(allTokens["control.crm-lead-drawer.compact-action-height"]).toBe("34px");
    expect(allTokens["control.crm-lead-drawer.action-font-size"]).toBe("9px");
    expect(allTokens["layout.crm-usage-drawer.width"]).toBe("399px");
    expect(allTokens["layout.crm-usage-drawer.question-columns"]).toBe("18px minmax(0, 1fr) 14px");
    expect(allTokens["control.crm-pipeline-card.height"]).toBe("139px");
    expect(allTokens["control.crm-agent-flow-drawer.question-height"]).toBe("52px");
    expect(allTokens["control.crm-agent-flow-drawer.info-size"]).toBe("13px");
    expect(allTokens["control.crm-agent-flow-drawer.test-title-size"]).toBe("15px");
    expect(allTokens["control.crm-agent-flow-drawer.test-role-size"]).toBe("11px");
    expect(allTokens["control.crm-agent-flow-drawer.test-info-min-height"]).toBe("152px");
    expect(allTokens["control.crm-agent-flow-drawer.test-info-line-height"]).toBe("22px");
    expect(allTokens["color.crm-agent-flow-drawer.info-fg"]).toBe("#0D6BFF");
    expect(allTokens["control.crm-class-drawer.action-height"]).toBe("40px");
    expect(allTokens["color.crm-class-drawer.warning-fg"]).toBe("#FF6F16");
    expect(allTokens["control.crm-lead-drawer.action-icon-size"]).toBe("15px");
    expect(allTokens["color.crm-lead-drawer.info-fg"]).toBe("#0D6BFF");
    expect(allTokens["control.crm-usage-drawer.question-height"]).toBe("52px");
    expect(allTokens["color.crm-usage-drawer.info-fg"]).toBe("#0D6BFF");
    expect(allTokens["control.crm-commercial-row.height"]).toBe("66px");
    expect(allTokens["control.crm-commercial-row.trial-height"]).toBe("70px");
    expect(allTokens["control.crm-enrollment-checklist.height"]).toBe("152px");
    expect(allTokens["status.sales.copilot.bg"]).toBe("rgba(139, 92, 246, 0.13)");
    expect(allTokens["color.crm-sales.whatsapp"]).toBe("#10B963");
    expect(allTokens["layout.crm-risk-row.width"]).toBe("862px");
    expect(allTokens["layout.crm-risk-row.columns"]).toContain("30px 12px 96px");
    expect(allTokens["layout.crm-retention-panel.cancellation-width"]).toBe("397px");
    expect(allTokens["control.crm-retention-panel.cancellation-height"]).toBe("860px");
    expect(allTokens["control.crm-retention-panel.text-size"]).toBe("9px");
    expect(allTokens["status.retention.high.bg"]).toContain("rgba(239, 68, 68");
    expect(allTokens["color.crm-retention.suggestion-bg"]).toContain("rgba(139, 92, 246");
    expect(allTokens["layout.crm-support-ticket-panel.width"]).toBe("390px");
    expect(allTokens["layout.crm-tenant-row.columns"]).toContain("21px 34px");
    expect(allTokens["layout.crm-tenant-detail-layout.columns"]).toBe("1071px 346px");
    expect(allTokens["control.crm-internal-tenants-table.min-height"]).toBe("535px");
    expect(allTokens["control.crm-security-rule-panel.height"]).toBe("838px");
    expect(allTokens["color.crm-internal.copilot-bg"]).toContain("rgba(139, 92, 246");
    expect(allTokens["layout.crm-report-filter-bar.width"]).toBe("795px");
    expect(allTokens["layout.crm-report-card.width"]).toBe("493px");
    expect(allTokens["layout.crm-opportunity-drawer.width"]).toBe("368px");
    expect(allTokens["control.crm-opportunity-drawer.height"]).toBe("817px");
    expect(allTokens["control.conflict-card.min-height"]).toBe("190px");
    expect(allTokens["control.conflict-card.fact-grid"]).toContain("repeat(3");
    expect(allTokens["control.document-preview.rail-width"]).toBe("36px");
    expect(allTokens["control.document-preview-line.height"]).toBe("5px");
    expect(allTokens["control.document-preview-line.width-wide"]).toBe("86%");
    expect(allTokens["control.execution-row.marker-size"]).toBe("14px");
    expect(allTokens["control.execution-row.grid"]).toContain("minmax(82px, 1fr)");
    expect(allTokens["control.confidence-meter.segment-count"]).toBe("5");
    expect(allTokens["control.confidence-meter.segment-height"]).toBe("9px");
    expect(allTokens["connector.length"]).toBe("76px");
    expect(allTokens["chart.panel.min-height"]).toBe("190px");
    expect(allTokens["focus.ring.info"]).toContain("rgba(94, 142, 232");
    expect(allTokens["focus.field.shadow"]).toContain("rgba(16, 20, 26");
    expect(allTokens["motion.ease.standard"]).toContain("cubic-bezier");
  });

  it("keeps legacy aliases for already approved components", () => {
    expect(allTokens["color.black.900"]).toBe("#10141A");
    expect(allTokens["surface.page"]).toBe("#E4E4E4");
    expect(allTokens["shadow.1"]).toBe(allTokens["shadow.card"]);
    expect(tokenToCssVar("iconButton.md.size")).toBe("--taliya-iconButton-md-size");
  });

  it("maps token names to public CSS variables", () => {
    expect(tokenToCssVar("surface.app")).toBe("--taliya-surface-app");
    expect(tokenVar("radius.window")).toBe("var(--taliya-radius-window)");
  });

  it("keeps status and operational grammars explicit", () => {
    expect(statusNames).toEqual([
      "success",
      "info",
      "warning",
      "danger",
      "neutral",
      "paused",
      "blocked"
    ]);
    expect(operationalStateNames).toEqual([
      "active",
      "pending",
      "in-progress",
      "failed",
      "blocked",
      "human",
      "sensitive",
      "manual",
      "scheduled",
      "paused",
      "draft"
    ]);
    expect(quotaNames).toEqual(["normal", "attention", "warning", "blocked"]);
    expect(allTokens["operationalState.active.status"]).toBe("success");
    expect(allTokens["operationalState.human.status"]).toBe("info");
    expect(allTokens["quota.blocked.status"]).toBe("danger");
    expect(allTokens["layout.crm-quota-progress.width"]).toBe("890px");
    expect(allTokens["control.crm-quota-progress.height"]).toBe("287px");
    expect(allTokens["color.crm-quota-progress.fill"]).toBe("#005CFF");
    expect(allTokens["layout.crm-usage-ledger.width"]).toBe("893px");
    expect(allTokens["control.crm-usage-ledger.table-height"]).toBe("408px");
    expect(allTokens["color.crm-usage-ledger.link"]).toBe("#005CFF");
    expect(allTokens["layout.crm-impact-summary.width"]).toBe("848px");
    expect(allTokens["control.crm-impact-summary.height"]).toBe("185px");
    expect(allTokens["control.crm-impact-summary.title-weight"]).toBe("700");
    expect(allTokens["control.crm-impact-summary.header-text-offset"]).toBe("-3px");
    expect(allTokens["color.crm-impact-summary.text"]).toBe("#687180");
    expect(allTokens["color.crm-impact-summary.icon-warning-fg"]).toBe("var(--taliya-color-accent-warning)");
    expect(allTokens["layout.crm-settings-section.width"]).toBe("944px");
    expect(allTokens["control.crm-settings-section.action-size"]).toBe("30px");
    expect(allTokens["control.crm-permission-matrix.height"]).toBe("259px");
    expect(allTokens["control.crm-permission-matrix.select-width"]).toBe("166px");
    expect(allTokens["control.crm-permission-matrix.header-offset-x"]).toBe("4px");
    expect(allTokens["layout.crm-before-after-diff.width"]).toBe("346px");
    expect(allTokens["control.crm-before-after-diff.height"]).toBe("188px");
    expect(allTokens["color.crm-before-after-diff.changed-bg"]).toBe("rgba(22, 163, 74, 0.055)");
  });

  it("publishes the complete v1 registry", () => {
    expect(Object.keys(tokenGroups)).toEqual([
      "raw",
      "color",
      "surface",
      "crmProductShellSurface",
      "border",
      "status",
      "operationalState",
      "quota",
      "typography",
      "spacing",
      "layout",
      "density",
      "radius",
      "shadow",
      "control",
      "connector",
      "chart",
      "motion",
      "focus",
      "legacy",
      "certifiedCss"
    ]);
  });
});
