import type { TokenRecord } from "./types.js";

export const layoutTokens = {
  "layout.sidebar.compact": "72px",
  "layout.sidebar.expanded": "248px",
  "layout.topbar.height": "72px",
  "layout.page.padding-x": "32px",
  "layout.page.padding-y": "28px",
  "layout.grid.gap": "24px",
  "layout.panel.gap": "20px",
  "layout.context-panel.width": "320px",
  "layout.drawer.width": "420px",
  "layout.content.max-width": "1440px",
  "layout.viewport.height": "100vh",
  "layout.viewport.dynamic-height": "100dvh",
  "layout.state-page.max-width": "680px",
  "layout.state-page.min-height": "420px",
  "layout.state-page.viewport-offset": "180px",
  "layout.crm-list-detail.list-width": "190px",
  "layout.crm-list-detail.main-width": "780px",
  "layout.crm-list-detail.main-wide-width": "810px",
  "layout.crm-list-detail.main-closed-width": "1101px",
  "layout.crm-list-detail.detail-width": "330px",
  "layout.crm-list-detail.gap": "8px",
  "layout.crm-list-detail.spacious-filter-gap": "18px",
  "control.crm-work-list-detail.filter-padding-x": "8px",
  "control.crm-work-list-detail.filter-gap": "6px",
  "control.crm-work-list-detail.filter-icon-size": "14px",
  "control.crm-work-list-detail.filter-count-size": "18px",
  "control.crm-work-list-detail.filter-count-padding-x": "0px",
  "layout.crm-work-list-detail.main-priority-rail-width": "176px",
  "layout.crm-work-list-detail.balanced-rail-width": "190px",
  "control.crm-work-list-detail.main-priority-rail-padding": "18px 8px 14px",
  "control.crm-work-list-detail.main-priority-filter-padding-x": "4px",
  "control.crm-work-list-detail.main-priority-filter-gap": "4px",
  "control.crm-work-list-detail.main-priority-filter-icon-size": "13px",
  "control.crm-work-list-detail.main-priority-filter-count-size": "18px",
  "control.crm-work-list-detail.main-priority-filter-count-padding-x": "0px",
  "layout.crm-work-list-detail.compact-rail-width": "166px",
  "layout.crm-work-list-detail.wide-main-rail-width": "166px",
  "layout.crm-list-detail.source-width": "1316px",
  "layout.crm-list-detail.source-height": "930px",
  "layout.crm-list-detail.columns": "var(--taliya-layout-crm-list-detail-list-width) minmax(0, var(--taliya-layout-crm-list-detail-main-closed-width))",
  "layout.crm-list-detail.columns-with-detail": "var(--taliya-layout-crm-list-detail-list-width) minmax(0, var(--taliya-layout-crm-list-detail-main-width)) var(--taliya-layout-crm-list-detail-detail-width)",
  "layout.crm-three-pane.width": "1294px",
  "layout.crm-three-pane.height": "753px",
  "layout.crm-three-pane.left-width": "483px",
  "layout.crm-three-pane.center-width": "502px",
  "layout.crm-three-pane.right-width": "279px",
  "layout.crm-three-pane.gap": "15px",
  "layout.crm-three-pane.page-gap": "12px",
  "layout.crm-three-pane.page-inset-left": "13px",
  "layout.crm-three-pane.columns": "var(--taliya-layout-crm-three-pane-left-width) var(--taliya-layout-crm-three-pane-center-width) var(--taliya-layout-crm-three-pane-right-width)",
  "layout.crm-right-panel.width": "1390px",
  "layout.crm-right-panel.height": "738px",
  "layout.crm-right-panel.main-width": "974px",
  "layout.crm-right-panel.rail-width": "401px",
  "layout.crm-right-panel.student-profile-width": "100%",
  "layout.crm-right-panel.student-profile-height": "907px",
  "layout.crm-right-panel.student-profile-main-width": "901px",
  "layout.crm-right-panel.student-profile-rail-width": "377px",
  "layout.crm-right-panel.student-profile-gap": "11px",
  "layout.crm-right-panel.class-operation-width": "1385px",
  "layout.crm-right-panel.class-operation-height": "929px",
  "layout.crm-right-panel.class-operation-main-width": "957px",
  "layout.crm-right-panel.class-operation-rail-width": "407px",
  "layout.crm-right-panel.class-operation-gap": "21px",
  "layout.crm-right-panel.settings-width": "1318px",
  "layout.crm-right-panel.settings-main-width": "940px",
  "layout.crm-right-panel.settings-rail-width": "352px",
  "layout.crm-right-panel.settings-gap": "26px",
  "layout.crm-right-panel.settings-payments-width": "1324px",
  "layout.crm-right-panel.settings-payments-main-width": "940px",
  "layout.crm-right-panel.settings-payments-rail-width": "352px",
  "layout.crm-right-panel.settings-payments-gap": "32px",
  "layout.crm-right-panel.settings-payments-main-offset-y": "19px",
  "layout.crm-right-panel.settings-payments-panel-offset-y": "-83px",
  "layout.crm-right-panel.settings-payments-panel-height": "922px",
  "layout.crm-right-panel.settings-agenda-width": "1302px",
  "layout.crm-right-panel.settings-agenda-main-width": "884px",
  "layout.crm-right-panel.settings-agenda-rail-width": "382px",
  "layout.crm-right-panel.settings-agenda-gap": "36px",
  "layout.crm-right-panel.settings-agenda-main-offset-y": "38px",
  "layout.crm-right-panel.settings-agenda-panel-offset-y": "-56px",
  "layout.crm-right-panel.settings-agenda-panel-height": "860px",
  "layout.crm-right-panel.settings-notifications-width": "1311px",
  "layout.crm-right-panel.settings-notifications-main-width": "890px",
  "layout.crm-right-panel.settings-notifications-rail-width": "386px",
  "layout.crm-right-panel.settings-notifications-gap": "35px",
  "layout.crm-right-panel.settings-notifications-main-offset-y": "5px",
  "layout.crm-right-panel.settings-notifications-panel-offset-y": "-70px",
  "layout.crm-right-panel.settings-notifications-panel-height": "886px",
  "layout.crm-right-panel.settings-notifications-offset-x": "-3px",
  "layout.crm-right-panel.settings-permissions-width": "1353px",
  "layout.crm-right-panel.settings-permissions-main-width": "887px",
  "layout.crm-right-panel.settings-permissions-rail-width": "440px",
  "layout.crm-right-panel.settings-permissions-gap": "26px",
  "layout.crm-right-panel.settings-permissions-main-inset": "19px",
  "layout.crm-right-panel.settings-permissions-frame-top": "130px",
  "layout.crm-right-panel.settings-permissions-frame-bottom": "27px",
  "layout.crm-right-panel.settings-permissions-frame-left": "42px",
  "layout.crm-right-panel.billing-subscription-width": "1297px",
  "layout.crm-right-panel.billing-subscription-height": "888px",
  "layout.crm-right-panel.billing-subscription-main-width": "934px",
  "layout.crm-right-panel.billing-subscription-rail-width": "334px",
  "layout.crm-right-panel.billing-subscription-gap": "29px",
  "layout.crm-right-panel.billing-subscription-offset-x": "7px",
  "layout.crm-right-panel.billing-subscription-main-offset-y": "47px",
  "layout.crm-right-panel.billing-subscription-panel-offset-y": "-93px",
  "layout.crm-right-panel.billing-invoices-width": "1304px",
  "layout.crm-right-panel.billing-invoices-height": "858px",
  "layout.crm-right-panel.billing-invoices-main-width": "876px",
  "layout.crm-right-panel.billing-invoices-rail-width": "390px",
  "layout.crm-right-panel.billing-invoices-gap": "38px",
  "layout.crm-right-panel.billing-invoices-main-offset-y": "36px",
  "layout.crm-right-panel.billing-invoices-panel-offset-y": "-62px",
  "layout.crm-right-panel.billing-addons-width": "1279px",
  "layout.crm-right-panel.billing-addons-height": "850px",
  "layout.crm-right-panel.billing-addons-main-width": "884px",
  "layout.crm-right-panel.billing-addons-rail-width": "366px",
  "layout.crm-right-panel.billing-addons-gap": "29px",
  "layout.crm-right-panel.billing-addons-offset-x": "13px",
  "layout.crm-right-panel.billing-addons-main-offset-y": "64px",
  "layout.crm-right-panel.billing-addons-panel-offset-y": "-71px",
  "layout.crm-right-panel.usage-overview-width": "1296px",
  "layout.crm-right-panel.usage-overview-height": "872px",
  "layout.crm-right-panel.usage-overview-main-width": "890px",
  "layout.crm-right-panel.usage-overview-rail-width": "376px",
  "layout.crm-right-panel.usage-overview-gap": "30px",
  "layout.crm-right-panel.usage-overview-offset-x": "6px",
  "layout.crm-right-panel.usage-overview-main-offset-y": "39px",
  "layout.crm-right-panel.usage-overview-panel-offset-y": "-76px",
  "layout.crm-right-panel.usage-ledger-width": "1296px",
  "layout.crm-right-panel.usage-ledger-height": "829px",
  "layout.crm-right-panel.usage-ledger-main-width": "893px",
  "layout.crm-right-panel.usage-ledger-rail-width": "376px",
  "layout.crm-right-panel.usage-ledger-gap": "27px",
  "layout.crm-right-panel.usage-ledger-offset-x": "5px",
  "layout.crm-right-panel.usage-ledger-main-offset-y": "56px",
  "layout.crm-right-panel.usage-ledger-panel-offset-y": "-64px",
  "layout.crm-right-panel.class-operation-panel-offset-y": "-156px",
  "layout.crm-right-panel.class-operation-header-reserve": "442px",
  "layout.crm-right-panel.gap": "15px",
  "layout.crm-right-panel.columns": "var(--taliya-layout-crm-right-panel-main-width) var(--taliya-layout-crm-right-panel-rail-width)",
  "layout.crm-right-panel.student-profile-columns": "minmax(0, 1fr) var(--taliya-layout-crm-right-panel-student-profile-rail-width)",
  "layout.crm-right-panel.class-operation-columns": "var(--taliya-layout-crm-right-panel-class-operation-main-width) var(--taliya-layout-crm-right-panel-class-operation-rail-width)",
  "layout.crm-right-panel.billing-invoices-columns": "var(--taliya-layout-crm-right-panel-billing-invoices-main-width) var(--taliya-layout-crm-right-panel-billing-invoices-rail-width)",
  "layout.crm-right-panel.billing-addons-columns": "var(--taliya-layout-crm-right-panel-billing-addons-main-width) var(--taliya-layout-crm-right-panel-billing-addons-rail-width)",
  "layout.crm-right-panel.usage-overview-columns": "var(--taliya-layout-crm-right-panel-usage-overview-main-width) var(--taliya-layout-crm-right-panel-usage-overview-rail-width)",
  "layout.crm-right-panel.usage-ledger-columns": "var(--taliya-layout-crm-right-panel-usage-ledger-main-width) var(--taliya-layout-crm-right-panel-usage-ledger-rail-width)",
  "layout.crm-right-panel.settings-permissions-columns": "var(--taliya-layout-crm-right-panel-settings-permissions-main-width) var(--taliya-layout-crm-right-panel-settings-permissions-rail-width)",
  "layout.crm-right-panel.settings-payments-columns": "var(--taliya-layout-crm-right-panel-settings-payments-main-width) var(--taliya-layout-crm-right-panel-settings-payments-rail-width)",
  "layout.crm-right-panel.settings-agenda-columns": "var(--taliya-layout-crm-right-panel-settings-agenda-main-width) var(--taliya-layout-crm-right-panel-settings-agenda-rail-width)",
  "layout.crm-right-panel.settings-notifications-columns": "var(--taliya-layout-crm-right-panel-settings-notifications-main-width) var(--taliya-layout-crm-right-panel-settings-notifications-rail-width)",
  "layout.crm-right-panel.billing-subscription-columns": "var(--taliya-layout-crm-right-panel-billing-subscription-main-width) var(--taliya-layout-crm-right-panel-billing-subscription-rail-width)",
  "layout.crm-dashboard.columns-2": "repeat(2, minmax(0, 1fr))",
  "layout.crm-dashboard.columns-3": "repeat(3, minmax(0, 1fr))",
  "layout.crm-dashboard.columns-4": "repeat(4, minmax(0, 1fr))",
  "layout.field-grid.columns-4": "repeat(4, minmax(0, 1fr))",
  "layout.crm-dashboard.gap-compact": "12px",
  "layout.crm-dashboard.columns-asymmetrical": "minmax(0, 1.35fr) minmax(0, 0.65fr)",
  "layout.crm-dashboard.columns-support": "276px minmax(0, 1fr)",
  "layout.crm-dashboard.gap-support": "16px",
  "layout.crm-dashboard.columns-agenda": "minmax(200px, 204px) minmax(0, 1fr)",
  "layout.crm-dashboard.columns-reports": "repeat(6, minmax(0, 1fr))",
  "layout.crm-dashboard.reports-rows": "222px 206px 190px",
  "layout.crm-dashboard.opportunity-rows": "208px 196px 191px",
  "layout.crm-dashboard.opportunity-gap": "10px",
  "layout.crm-dashboard.today-width": "100%",
  "layout.crm-dashboard.today-height": "auto",
  "layout.crm-dashboard.today-gap": "14px",
  "layout.crm-dashboard.today-columns": "minmax(0, 393fr) minmax(0, 316fr) minmax(0, 270fr) minmax(0, 487fr)",
  "layout.crm-dashboard.today-rows": "minmax(255px, auto) minmax(230px, auto) minmax(194px, auto)",
  "layout.crm-dashboard.today-critical-column-gap": "12px",
  "layout.crm-dashboard.today-critical-row-gap": "10px",
  "layout.crm-dashboard.today-critical-columns": "minmax(0, 412fr) minmax(0, 321fr) minmax(0, 277fr) minmax(0, 461fr)",
  "layout.crm-dashboard.today-critical-rows": "minmax(260px, auto) minmax(245px, auto) minmax(196px, auto)",
  "layout.crm-dashboard.today-critical-offset-y": "-9px",
  "layout.crm-dashboard.today-critical-checklist-extra-width": "24px",
  "layout.crm-dashboard.today-critical-now-offset-x": "29px",
  "layout.crm-dashboard.today-critical-rows-margin-top": "8px",
  "control.crm-dashboard.today-critical-checklist-row-height": "47px",
  "control.crm-dashboard.today-critical-now-row-height": "63px",
  "control.crm-dashboard.today-critical-schedule-row-height": "44px",
  "control.crm-dashboard.today-critical-queue-row-height": "49px",
  "control.crm-dashboard.today-critical-action-row-height": "57px",
  "control.crm-dashboard.today-critical-compact-row-height": "42px",
  "type.crm-dashboard.today-critical-block-title-size": "12px",
  "layout.crm-activity-feed.width": "100%",
  "layout.crm-activity-feed.height": "auto",
  "layout.crm-activity-feed.grid-columns": "94px 1fr",
  "layout.crm-activity-feed.row-columns": "38px minmax(240px, 1fr) minmax(260px, 0.74fr) 24px",
  "layout.crm-activity-feed.panel-width": "620px",
  "layout.crm-operation-activity-table.row-columns": "48px 32px 128px 164px minmax(190px, 1fr) 132px 108px 112px",
  "layout.crm-audit-trail.width": "502px",
  "layout.crm-audit-trail.table-columns": "78px 66px 90px 102px 48px 54px 50px",
  "layout.crm-audit-trail.actor-column": "78px",
  "layout.crm-audit-trail.object-column": "66px",
  "layout.crm-audit-trail.action-column": "90px",
  "layout.crm-audit-trail.time-column": "102px",
  "layout.crm-audit-trail.origin-column": "48px",
  "layout.crm-audit-trail.status-column": "54px",
  "layout.crm-audit-trail.open-column": "50px",
  "layout.crm-kanban.board-width": "1284px",
  "layout.crm-kanban.board-height": "570px",
  "layout.crm-kanban.board-columns": "var(--taliya-layout-crm-page-quick-filters-width) repeat(5, minmax(0, 1fr))",
  "layout.crm-kanban.board-gap": "13px",
  "layout.crm-kanban.separate-board-gap": "11px",
  "layout.crm-page-quick-filters.width": "220px",
  "layout.crm-kanban.rail-width": "var(--taliya-layout-crm-page-quick-filters-width)",
  "layout.crm-kanban.compact-rail-width": "200px",
  "layout.crm-kanban.compact-board-height": "410px",
  "layout.crm-kanban.compact-column-width": "220px",
  "layout.crm-kanban.column-width": "195px",
  "layout.crm-kanban.finance-column-width": "205px",
  "layout.crm-kanban.finance-board-height": "607px",
  "layout.crm-kanban.finance-page-inset-inline": "26px 22px",
  "layout.crm-kanban.commercial-page-inset-inline": "26px",
  "layout.crm-kanban.commercial-column-width": "267px",
  "layout.crm-kanban.card-fact-columns": "56px minmax(0, 1fr)",
  "layout.crm-kanban.board-min-height": "570px",
  "layout.crm-kanban.column-min-height": "100%",
  "layout.crm-weekly-calendar.width": "765px",
  "layout.crm-reference-14.calendar-height": "394px",
  "layout.crm-reference-14.class-card-height": "274px",
  "layout.crm-reference-14.class-summary-height": "281px",
  "layout.crm-reference-14.roster-height": "125px",
  "layout.crm-reference-14.matcher-height": "235px",
  "layout.crm-reference-14.waitlist-height": "235px",
  "layout.crm-reference-14.conflict-height": "235px",
  "layout.crm-reference-14.document-height": "162px",
  "layout.crm-reference-14.upload-height": "162px",
  "layout.crm-reference-14.reconciliation-height": "126px",
  "layout.crm-reference-14.money-height": "126px",
  "layout.crm-reference-14.simulation-height": "143px",
  "layout.crm-reference-15.flow-builder-height": "226px",
  "layout.crm-reference-15.mode-height": "226px",
  "layout.crm-reference-15.simulator-height": "226px",
  "layout.crm-reference-15.preflight-height": "214px",
  "layout.crm-reference-15.trace-height": "214px",
  "layout.crm-reference-15.incident-height": "214px",
  "layout.crm-reference-15.quality-height": "214px",
  "layout.crm-reference-15.diff-height": "181px",
  "layout.crm-reference-15.audit-height": "181px",
  "layout.crm-reference-15.privacy-height": "181px",
  "layout.crm-reference-15.grant-height": "181px",
  "layout.crm-reference-15.reports-height": "194px",
  "layout.crm-reference-15.exports-height": "194px",
  "layout.crm-reference-15.segment-height": "194px",
  "layout.crm-reference-16.stage-padding-top": "88px",
  "layout.crm-reference-16.stage-padding-x": "42px",
  "layout.crm-reference-16.stage-padding-bottom": "95px",
  "layout.crm-reference-16.chrome-height": "63px",
  "layout.crm-reference-16.sidebar-width": "93px",
  "layout.crm-reference-16.topbar-height": "73px",
  "layout.crm-reference-16.header-height": "62px",
  "layout.crm-reference-16.content-padding-right": "32px",
  "layout.crm-reference-16.content-gap": "8px",
  "layout.crm-reference-16.primary-height": "485px",
  "layout.crm-reference-16.surface-radius": "30px",
  "layout.crm-reference-16.participant-size": "44px",
  "layout.crm-reference-16.back-left": "148px",
  "layout.crm-reference-16.nav-left": "267px",
  "layout.crm-reference-16.actions-right": "42px",
  "layout.crm-reference-16.title-offset-y": "8px",
  "layout.crm-weekly-calendar.height": "796px",
  "layout.crm-weekly-calendar.short-height": "720px",
  "layout.crm-weekly-calendar.compact-width": "100%",
  "layout.crm-weekly-calendar.compact-time-width": "48px",
  "layout.crm-weekly-calendar.compact-day-width": "calc((100% - 48px) / 5)",
  "layout.crm-weekly-calendar.compact-columns": "48px repeat(5, minmax(0, 1fr))",
  "layout.crm-weekly-calendar.time-width": "58px",
  "layout.crm-weekly-calendar.day-width": "137px",
  "layout.crm-weekly-calendar.day-min-width": "137px",
  "layout.crm-weekly-calendar.columns": "58px repeat(5, 137px)",
  "layout.crm-weekly-calendar.header-height": "42px",
  "layout.crm-weekly-calendar.detail-width": "320px",
  "layout.crm-class-card.width": "122px",
  "layout.crm-class-card.height": "85px",
  "layout.crm-class-card.selected-width": "123px",
  "layout.crm-class-card.selected-height": "86px",
  "layout.crm-roster.width": "375px",
  "layout.crm-roster.columns": "52px minmax(0, 1fr) 122px 31px",
  "layout.crm-roster.expected-width": "515px",
  "layout.crm-roster.expected-columns": "50px minmax(0, 1fr) 118px 30px",
  "layout.crm-student-drawer.width": "316px",
  "layout.crm-student-drawer.height": "927px",
  "layout.crm-student-drawer.fact-columns": "28px 122px minmax(0, 1fr)",
  "layout.crm-student-drawer.action-columns": "repeat(2, minmax(0, 1fr))",
  "layout.crm-mini-calendar.width": "204px",
  "layout.crm-mini-calendar.height": "242px",
  "layout.crm-mini-calendar.columns": "repeat(7, 24px)",
  "layout.crm-compact-calendar.width": "560px",
  "layout.crm-compact-calendar.body-columns": "minmax(0, 1.05fr) minmax(0, 0.95fr)",
  "layout.crm-channel-status-panel.width": "214px",
  "layout.crm-composer-panel.width": "280px",
  "layout.crm-setup-shell.width": "1660px",
  "layout.crm-setup-shell.height": "928px",
  "layout.crm-setup-shell.columns": "220px 978px 397px",
  "layout.crm-setup-shell.column-gap": "16px",
  "layout.crm-setup-shell.padding": "0 15px 15px",
  "layout.crm-setup-shell.topbar-height": "82px",
  "layout.crm-setup-shell.body-height": "738px",
  "layout.crm-setup-shell.bottom-bar-height": "73px",
  "layout.crm-setup-shell.guided-wide-columns": "207px 1062px 338px",
  "layout.crm-setup-shell.guided-wide-column-gap": "15px",
  "layout.crm-setup-shell.guided-wide-padding": "0 20px 13px 15px",
  "layout.crm-setup-shell.guided-wide-topbar-height": "79px",
  "layout.crm-setup-shell.guided-wide-body-height": "770px",
  "layout.crm-setup-shell.guided-wide-bottom-bar-height": "65px",
  "layout.crm-setup-shell.guided-wide-bottom-bar-width": "1637px",
  "layout.crm-setup-shell.guided-wide-stepper-height": "770px",
  "layout.crm-setup-shell.guided-review-columns": "210px 1064px 344px",
  "layout.crm-setup-shell.guided-review-column-gap": "12px",
  "layout.crm-setup-shell.guided-review-padding": "0 15px",
  "layout.crm-setup-shell.guided-review-topbar-height": "74px",
  "layout.crm-setup-shell.guided-review-body-height": "807px",
  "layout.crm-setup-shell.guided-review-bottom-bar-height": "52px",
  "layout.crm-setup-shell.guided-review-bottom-bar-width": "1642px",
  "layout.crm-setup-shell.guided-review-stepper-height": "807px",
  "layout.crm-setup-shell.guided-review-stepper-header-height": "70px",
  "layout.crm-setup-shell.bottom-bar-grid-column": "1 / 4",
  "layout.crm-setup-bottom-bar.columns": "278px 1px minmax(0, 1fr) 360px 1px 44px",
  "layout.crm-setup-bottom-bar.width": "1630px",
  "layout.crm-setup-bottom-bar.height": "73px",
  "layout.crm-setup-welcome.width": "690px",
  "layout.crm-setup-welcome.height": "470px",
  "layout.crm-setup-welcome.field-width": "600px",
  "layout.crm-setup-shell.welcome-topbar-height": "95px",
  "layout.crm-setup-shell.welcome-padding": "8px 16px 16px 32px",
  "layout.crm-setup-shell.welcome-main-offset-x": "13px",
  "layout.crm-setup-choice-card.width": "280px",
  "layout.crm-setup-choice-card.height": "90px",
  "layout.crm-setup-import-source-card.width": "166px",
  "layout.crm-setup-import-source-card.height": "75px",
  "layout.crm-setup-students-summary-height": "285px",
  "layout.crm-setup-students-worklist-height": "315px",
  "layout.crm-setup-classes-summary-height": "285px",
  "layout.crm-setup-classes-worklist-height": "315px",
  "layout.crm-setup-classes-source-card-height": "66px",
  "layout.crm-setup-agenda-summary-height": "150px",
  "layout.crm-setup-agenda-body-height": "460px",
  "layout.crm-setup-agenda-body-columns": "333px minmax(0, 1fr)",
  "layout.crm-setup-agenda-schedule-axis-rows": "repeat(6, 50px)",
  "layout.crm-setup-review-panel.width": "1064px",
  "layout.crm-setup-review-panel.height": "807px",
  "layout.crm-setup-review-panel.content-width": "1002px",
  "layout.crm-setup-review-panel.publish-grid": "repeat(4, 1fr)",
  "layout.crm-setup-review-panel.publish-card-width": "234px",
  "layout.crm-setup-review-panel.publish-card-height": "107px",
  "layout.crm-setup-review-panel.pending-grid": "1fr 1fr",
  "layout.crm-setup-review-panel.future-grid": "repeat(4, 1fr)",
  "layout.crm-setup-review-panel.future-card-height": "71px",
  "layout.crm-setup-review-panel.safe-grid": "185px 214px 278px 278px",
  "layout.crm-setup-agent-chat.width": "675px",
  "layout.crm-setup-agent-chat.height": "1381px",
  "layout.crm-setup-agent-chat.content-width": "613px",
  "layout.crm-setup-agent-chat.header-columns": "84px minmax(0, 1fr) 38px 38px",
  "layout.crm-setup-agent-chat.info-width": "494px",
  "layout.crm-setup-agent-chat.message-one-width": "468px",
  "layout.crm-setup-agent-chat.message-two-width": "454px",
  "layout.crm-setup-agent-chat.welcome-message-width": "342px",
  "layout.crm-setup-human-help-cta.width": "372px",
  "layout.crm-setup-human-help-cta.height": "83px",
  "layout.crm-setup-block-header.width": "735px",
  "layout.crm-setup-block-header.height": "84px",
  "layout.crm-setup-stepper.width": "220px",
  "layout.crm-setup-stepper.height": "738px",
  "layout.crm-setup-stepper.header-height": "86px",
  "layout.crm-setup-stepper.footer-height": "74px",
  "layout.crm-role-card.width": "862px",
  "layout.crm-invite-row.width": "862px",
  "layout.crm-invite-row.columns": "159px 114px 165px 144px 205px 1fr",
  "layout.crm-payment-method-row.width": "310px",
  "layout.crm-access-shell.content-columns": "minmax(0, 1fr) minmax(280px, 0.44fr)",
  "layout.crm-access-shell.main-width": "440px",
  "layout.crm-access-shell.rail-width": "420px",
  "layout.crm-access-shell.window-width": "1528px",
  "layout.crm-access-shell.window-height": "890px",
  "layout.crm-access-shell.chrome-height": "64px",
  "layout.crm-access-shell.brandbar-height": "90px",
  "layout.crm-access-shell.body-height": "826px",
  "layout.crm-access-shell.main-height": "663px",
  "layout.crm-access-shell.footer-height": "73px",
  "layout.crm-access-shell.content-width": "966px",
  "layout.crm-access-shell.content-height": "582px",
  "layout.crm-access-shell.content-padding": "23px 24px 21px",
  "layout.crm-access-shell.content-placeholder-height": "532px",
  "layout.crm-access-shell.centered-main-padding": "0",
  "layout.crm-access-shell.centered-content-width": "100%",
  "layout.crm-access-shell.centered-content-height": "100%",
  "layout.crm-access-shell.centered-content-padding": "0",
  "layout.crm-access-shell.centered-content-placeholder-height": "100%",
  "layout.crm-access-shell.rail-card-width": "475px",
  "layout.crm-access-shell.rail-card-context-height": "232px",
  "layout.crm-access-shell.rail-card-summary-height": "188px",
  "layout.crm-access-shell.rail-card-help-height": "134px",
  "layout.crm-access-shell.rail-gap": "15px",
  "layout.crm-access-shell.main-gap": "20px",
  "layout.crm-access-shell.main-padding": "20px 32px 0",
  "layout.crm-access-shell.brandbar-padding": "0 39px 0 45px",
  "layout.crm-access-shell.footer-gap": "31px",
  "layout.crm-access-shell.logo-width": "212px",
  "layout.crm-access-shell.centered-logo-width": "176px",
  "layout.crm-access-shell.browser-address-width": "405px",
  "layout.crm-access-shell.browser-address-height": "39px",
  "layout.crm-access-shell.browser-address-top": "15px",
  "layout.crm-access-shell.browser-traffic-left": "35px",
  "layout.crm-access-shell.browser-traffic-top": "26px",
    "layout.crm-access-shell.browser-toolbar-left": "149px",
    "layout.crm-access-shell.browser-toolbar-top": "24px",
    "control.crm-access-shell.browser-address.font-size": "16px",
    "control.crm-access-shell.browser-address.icon-size": "16px",
    "control.crm-access-shell.browser-address.font-weight": "400",
    "control.crm-access-footer-links.font-size": "16px",
    "control.crm-access-footer-links.line-height": "20px",
    "control.crm-access-footer-links.font-weight": "400",
    "control.crm-access-footer-links.cluster-gap": "38px",
    "control.crm-access-footer-links.separator-size": "16px",
    "control.crm-access-footer-links.cluster-offset-y": "4px",
    "layout.crm-auth-card.signup-width": "460px",
  "layout.crm-auth-card.signup-height": "618px",
  "layout.crm-auth-card.signin-width": "523px",
  "layout.crm-auth-card.signin-height": "577px",
  "layout.crm-auth-card.signup-content-width": "378px",
  "layout.crm-auth-card.signin-content-width": "456px",
  "layout.crm-auth-card.signup-padding": "36px 41px 26px",
    "layout.crm-auth-card.signin-padding": "32px 33px 31px",
  "layout.crm-auth-card.social-height": "49px",
  "layout.crm-auth-card.field-height": "48px",
  "layout.crm-auth-card.submit-height": "43px",
  "layout.crm-auth-card.signin-submit-height": "50px",
  "layout.crm-auth-card.radius": "18px",
  "layout.crm-auth-card.control-radius": "9px",
  "layout.crm-auth-card.divider-gap": "18px",
    "layout.crm-auth-card.signin-options-height": "22px",
    "layout.crm-auth-card.signin-options-columns": "1fr auto",
  "color.crm-auth-card.bg": "var(--taliya-surface-card)",
  "color.crm-auth-card.border": "var(--taliya-border-default)",
  "color.crm-auth-card.text": "var(--taliya-color-text-primary)",
  "color.crm-auth-card.muted": "#667085",
  "color.crm-auth-card.control-border": "#D9DEE8",
  "color.crm-auth-card.control-bg": "var(--taliya-surface-field)",
    "color.crm-auth-card.primary-bg": "#050505",
    "color.crm-auth-card.primary-bg-start": "#151515",
    "color.crm-auth-card.primary-bg-end": "var(--taliya-raw-black-950)",
    "color.crm-auth-card.primary-fg": "var(--taliya-surface-card)",
  "color.crm-auth-card.link": "#1F2A44",
    "shadow.crm-auth-card": "0 22px 52px rgba(16, 20, 26, 0.10)",
    "shadow.crm-auth-card-primary": "0 7px 14px var(--taliya-border-default), inset 0 1px 0 rgba(255, 255, 255, 0.10)",
    "control.crm-auth-card.title-size": "28px",
    "control.crm-auth-card.title-line-height": "34px",
    "control.crm-auth-card.title-weight": "600",
  "control.crm-auth-card.subtitle-size": "16px",
  "control.crm-auth-card.subtitle-line-height": "24px",
  "control.crm-auth-card.subtitle-width": "378px",
  "control.crm-auth-card.body-size": "15px",
    "control.crm-auth-card.body-line-height": "22px",
    "control.crm-auth-card.button-size": "16px",
    "control.crm-auth-card.button-line-height": "24px",
    "control.crm-auth-card.social-icon-column": "60px",
    "control.crm-auth-card.signup-header-margin-bottom": "10px",
    "control.crm-auth-card.signin-header-margin-bottom": "18px",
    "control.crm-auth-card.signup-divider-margin": "18px 0 12px",
    "control.crm-auth-card.signin-divider-margin": "18px 0 16px",
    "control.crm-auth-card.signin-options-margin": "13px 0 10px",
    "control.crm-auth-card.signup-submit-margin-top": "10px",
  "layout.crm-subscription-status-card.width": "726px",
  "layout.crm-subscription-status-card.content-width": "592px",
  "layout.crm-subscription-status-card.failed-width": "706px",
  "layout.crm-subscription-status-card.failed-content-width": "642px",
  "layout.crm-subscription-status-card.confirmed-width": "546px",
  "layout.crm-confirmed-setup-handoff.width": "607px",
  "layout.crm-checkout-review-panel.width": "1076px",
  "layout.crm-checkout-review-panel.columns": "var(--taliya-layout-crm-plan-summary-card-review-width) var(--taliya-layout-crm-checkout-payment-card-width)",
  "layout.crm-checkout-payment-card.width": "399px",
  "layout.crm-plan-summary-card.active-width": "292px",
  "layout.crm-plan-summary-card.review-width": "636px",
  "layout.crm-plan-summary-card.confirmed-width": "545px",
  "layout.crm-plan-summary-card.failed-width": "641px",
  "layout.crm-invoice-table.width": "876px",
  "layout.crm-invoice-table.columns": "136px 135px 138px 135px 139px minmax(146px, 1fr)",
  "layout.crm-invoice-table.period-column": "136px",
  "layout.crm-invoice-table.due-column": "135px",
  "layout.crm-invoice-table.amount-column": "138px",
  "layout.crm-invoice-table.status-column": "135px",
  "layout.crm-invoice-table.method-column": "139px",
  "layout.crm-invoice-table.actions-column": "146px",
  "layout.crm-addon-card.width": "269px",
  "layout.crm-addon-card.panel-width": "888px",
  "layout.crm-addon-card.panel-columns": "repeat(3, var(--taliya-layout-crm-addon-card-width))",
  "layout.crm-addon-card.panel-gap": "20px",
  "layout.crm-settings-hub-card.width": "332px",
  "layout.crm-quota-progress.width": "890px",
  "layout.crm-usage-overview.width": "890px",
  "layout.crm-usage-overview.lower-columns": "440px 424px",
  "layout.crm-usage-origin-row.width": "380px",
  "layout.crm-usage-origin-row.columns": "40px 94px 110px 52px 34px",
  "layout.crm-export-action.width": "115px",
  "layout.crm-export-action.menu-width": "164px",
  "layout.crm-usage-ledger.width": "893px",
  "layout.crm-usage-ledger.table-width": "855px",
  "layout.crm-usage-ledger.table-offset-x": "-9px",
  "layout.crm-usage-ledger.footer-width": "833px",
  "layout.crm-usage-ledger.table-columns": "108px 108px 190px 160px 87px 95px 107px",
  "layout.crm-usage-ledger.when-column": "108px",
  "layout.crm-usage-ledger.origin-column": "108px",
  "layout.crm-usage-ledger.agent-column": "190px",
  "layout.crm-usage-ledger.case-column": "160px",
  "layout.crm-usage-ledger.usage-column": "87px",
  "layout.crm-usage-ledger.status-column": "95px",
  "layout.crm-usage-ledger.action-column": "107px",
  "layout.crm-usage-ledger.filter-widths": "180px 145px 149px 139px",
  "layout.crm-usage-ledger.filter-period-width": "180px",
  "layout.crm-usage-ledger.filter-agent-width": "145px",
  "layout.crm-usage-ledger.filter-origin-width": "149px",
  "layout.crm-usage-ledger.filter-status-width": "139px",
  "layout.crm-approval-panel.width": "360px",
  "layout.crm-approval-panel.fact-columns": "18px 115px minmax(0, 1fr)",
  "layout.crm-approval-panel.action-columns": "repeat(3, minmax(0, 1fr))",
  "layout.crm-approval-panel.compact-width": "205px",
  "layout.crm-approval-panel.compact-header-columns": "14px minmax(0, 1fr)",
  "layout.crm-approval-panel.compact-fact-columns": "max-content minmax(0, 1fr)",
  "layout.crm-approval-panel.compact-action-columns": "repeat(3, minmax(0, 1fr))",
  "layout.crm-impact-summary.width": "848px",
  "layout.crm-impact-summary.item-columns": "28px minmax(0, 1fr)",
  "layout.crm-permission-matrix.width": "851px",
  "layout.crm-permission-matrix.table-width": "824px",
  "layout.crm-permission-matrix.columns": "31px 386px 229px minmax(0, 1fr)",
  "layout.crm-permission-matrix.control-width": "170px",
  "layout.crm-settings-section.width": "944px",
  "layout.crm-settings-section.columns": "repeat(2, minmax(0, 1fr))",
  "layout.crm-settings-section.row-columns": "40px minmax(0, 1fr) 104px 32px",
  "layout.crm-conversation-list.width": "483px",
  "layout.crm-conversation-list.compact-width": "516px",
  "layout.crm-conversation-list.row-columns": "50px minmax(0, 1fr) 46px",
  "layout.crm-conversation-list.footer-columns": "1fr 86px 1fr",
  "layout.crm-quick-reply-chips.width": "351px",
  "layout.crm-checklist-row.width": "302px",
  "layout.crm-comment-thread.width": "336px",
  "layout.crm-comment-thread.row-columns": "22px minmax(0, 1fr) 62px",
  "layout.crm-task-drawer.width": "401px",
  "layout.crm-checklist-drawer.width": "342px",
  "layout.crm-checklist-table.title-column": "24%",
  "layout.crm-checklist-table.compact-column": "10.25%",
  "layout.crm-checklist-table.owner-column": "13%",
  "layout.crm-checklist-table.status-column": "10.75%",
  "layout.crm-checklist-table.next-step-column": "10.5%",
  "layout.crm-checklist-table.activity-column": "11%",
  "layout.crm-task-drawer.height": "941px",
  "layout.crm-task-drawer.fact-columns": "24px 128px minmax(0, 1fr)",
  "layout.crm-task-drawer.footer-columns": "repeat(3, minmax(0, 1fr))",
  "layout.crm-task-drawer.conversation-footer-columns": "96px 76px 90px 74px",
  "layout.crm-case-drawer.width": "403px",
  "layout.crm-case-drawer.height": "1074px",
  "layout.crm-case-drawer.shell-top": "0px",
  "layout.crm-case-drawer.shell-height": "var(--taliya-layout-viewport-height)",
  "layout.crm-case-drawer.shell-z-index": "50",
  "layout.crm-case-drawer.fact-columns": "22px 152px minmax(0, 1fr)",
  "layout.crm-case-drawer.footer-columns": "repeat(3, minmax(0, 1fr))",
  "layout.crm-replacement-drawer.width": "376px",
  "layout.crm-replacement-drawer.height": "950px",
  "layout.crm-replacement-drawer.actions-columns": "repeat(2, minmax(0, 1fr))",
  "layout.crm-replacement-table.column-student": "15%",
  "layout.crm-replacement-table.column-original-class": "12%",
  "layout.crm-replacement-table.column-reason": "12%",
  "layout.crm-replacement-table.column-validity": "8%",
  "layout.crm-replacement-table.column-preference": "12%",
  "layout.crm-replacement-table.column-status": "15%",
  "layout.crm-replacement-table.column-next-action": "12%",
  "layout.crm-replacement-table.column-mode": "14%",
  "layout.crm-conversation-thread.width": "502px",
  "layout.crm-conversation-thread.compact-width": "625px",
  "layout.crm-conversation-thread.compact-special-message-width": "82%",
  "layout.crm-conversation-thread.compact-header-columns": "36px minmax(112px, 1fr) auto auto",
  "layout.crm-conversation-thread.compact-message-columns": "32px minmax(0, 1fr)",
  "layout.crm-conversation-thread.compact-suggestion-columns": "24px minmax(0, 1fr) auto",
  "layout.crm-copilot-panel.width": "420px",
  "layout.crm-copilot-panel.header-columns": "28px minmax(0, 1fr) 32px",
  "layout.crm-conversation-thread.header-columns": "42px minmax(148px, 1fr) auto",
  "layout.crm-conversation-thread.message-columns": "42px minmax(0, 1fr)",
  "layout.crm-conversation-thread.system-columns": "50px 56px 78px minmax(0, 1fr)",
  "layout.crm-conversation-thread.suggestion-columns": "46px minmax(0, 1fr) auto",
  "layout.crm-conversation-thread.composer-toolbar-columns": "auto minmax(0, 1fr) auto",
  "layout.crm-handoff-banner.compact-width": "200px",
  "layout.crm-handoff-banner.compact-header-columns": "14px minmax(0, 1fr)",
  "layout.crm-handoff-banner.compact-owner-columns": "28px minmax(0, 1fr)",
  "layout.crm-handoff-banner.compact-fact-columns": "max-content minmax(0, 1fr)",
  "layout.crm-context-panel.width": "280px",
  "layout.crm-context-panel.footer-columns": "1fr 1fr",
  "layout.crm-integration-status-row.width": "224px",
  "layout.crm-integration-status-row.columns": "71px minmax(0, 1fr)",
  "layout.crm-unsaved-changes-bar.width": "943px",
  "layout.crm-unsaved-changes-bar.columns": "146px minmax(0, 1fr) 240px",
  "layout.crm-rule-row.width": "860px",
  "layout.crm-rule-row.columns": "50px 273px 372px 165px",
  "layout.crm-rule-row.control-width": "259px",
  "layout.crm-before-after-diff.width": "346px",
  "layout.crm-before-after-diff.table-columns": "77px 97px 1fr",
  "layout.crm-before-after-diff.label-column": "77px",
  "layout.crm-before-after-diff.before-column": "97px",
  "layout.crm-before-after-diff.footer-columns": "1fr auto",
  "layout.crm-agent-catalog.columns": "repeat(3, minmax(280px, 445px))",
  "layout.crm-agent-catalog.card-width": "445px",
  "layout.crm-agent-catalog.gap": "16px",
  "layout.crm-agent-routines.max-width": "1224px",
  "layout.crm-agent-routines.gap": "20px",
  "layout.crm-agent-routines.intro-grid-gap": "25px",
  "layout.crm-domain-metrics.columns": "repeat(3, minmax(0, 1fr))",
  "layout.crm-domain-facts.columns": "repeat(4, minmax(0, 1fr))",
  "layout.crm-mode-selector.flow-columns": "repeat(5, minmax(168px, 1fr))",
  "layout.crm-mode-selector.routine-columns": "repeat(3, minmax(260px, 1fr))",
  "layout.crm-flow-builder.columns": "minmax(0, 1fr) 44px minmax(0, 1fr) 44px minmax(0, 1fr)",
  "layout.crm-agent-flow-settings-panel.columns": "218px 214px 285px 234px",
  "layout.crm-simulation-runner.columns": "292px 354px minmax(410px, 1fr)",
  "layout.crm-simulation-runner.grid-offset-y": "10px",
  "layout.crm-simulation-runner.timeline-panel-gap": "14px",
  "layout.crm-simulation-runner.test-columns": "292px 354px minmax(410px, 1fr)",
  "layout.crm-simulation-runner.test-column-gap": "16px",
  "layout.crm-preflight-checklist.columns": "repeat(5, minmax(148px, 1fr))",
  "layout.crm-agent-flow-drawer.width": "399px",
  "layout.crm-agent-flow-drawer.routine-width": "388px",
  "layout.crm-agent-flow-drawer.height": "780px",
  "layout.crm-agent-flow-drawer.info-columns": "21px minmax(0, 1fr)",
  "layout.crm-agent-flow-drawer.test-info-columns": "21px minmax(0, 1fr)",
  "layout.crm-agent-flow-drawer.question-columns": "18px minmax(0, 1fr) 14px",
  "layout.crm-agent-flow-drawer.composer-columns": "minmax(0, 1fr) 34px",
  "layout.crm-class-drawer.width": "399px",
  "layout.crm-class-drawer.height": "780px",
  "layout.crm-class-drawer.roster-columns": "44px minmax(0, 1fr) auto 32px",
  "layout.crm-class-drawer.compact-roster-columns": "42px minmax(0, 1fr) 82px 28px",
  "layout.crm-class-drawer.footer-columns": "repeat(3, minmax(0, 1fr))",
  "layout.crm-class-drawer.compact-footer-columns": "1fr",
  "layout.crm-lead-drawer.width": "399px",
  "layout.crm-lead-drawer.height": "780px",
  "layout.crm-lead-drawer.fact-columns": "18px 104px minmax(0, 1fr)",
  "layout.crm-lead-drawer.history-columns": "68px minmax(0, 1fr)",
  "layout.crm-lead-drawer.actions-columns": "repeat(2, minmax(0, 1fr))",
  "layout.crm-usage-drawer.width": "399px",
  "layout.crm-usage-drawer.height": "780px",
  "layout.crm-usage-drawer.question-columns": "18px minmax(0, 1fr) 14px",
  "layout.crm-usage-drawer.composer-columns": "minmax(0, 1fr) 34px",
  "layout.crm-payment-drawer.width": "371px",
  "layout.crm-payment-drawer.height": "941px",
  "layout.crm-payment-drawer.movement-offset-y": "-21px",
  "layout.crm-payment-drawer.fact-columns": "18px 112px minmax(0, 1fr)",
  "layout.crm-payment-drawer.actions-columns": "repeat(2, minmax(0, 1fr))",
  "layout.crm-execution-receipt.followup-columns": "repeat(2, minmax(0, 1fr))",
  "layout.crm-execution-receipt.compact-width": "190px",
  "layout.crm-execution-receipt.compact-header-columns": "14px minmax(0, 1fr)",
  "layout.crm-execution-receipt.compact-fact-columns": "max-content minmax(0, 1fr)",
  "layout.crm-student-summary.columns": "repeat(5, minmax(0, 1fr))",
  "layout.crm-student-header.columns": "auto minmax(0, 1fr) auto",
  "layout.crm-student-header.action-columns": "repeat(2, 193px)",
  "layout.crm-profile-tabs.width": "1042px",
  "layout.crm-relationship-list.columns": "104px 34px 104px 34px 104px",
  "layout.crm-payment-case-card.width": "350px",
  "layout.crm-payment-case-card.compact-width": "260px",
  "layout.crm-payment-case-card.row-columns": "90px 70px 76px minmax(0, 1fr) 14px",
  "layout.crm-finance-kanban-card.width": "183px",
  "layout.crm-reconciliation-row.width": "832px",
  "layout.crm-reconciliation-row.columns": "32px 98px 86px 76px 67px 60px 89px 75px 70px 63px 82px 18px",
  "layout.crm-pipeline-card.width": "239px",
  "layout.crm-lead-summary-row.width": "835px",
  "layout.crm-lead-summary-row.columns": "32px 6px 79px 16px 76px 20px 113px 22px 100px 32px 76px 19px 90px 24px 58px 18px 18px",
  "layout.crm-trial-class-row.width": "832px",
  "layout.crm-trial-class-row.columns": "32px 6px 73px 9px 91px 21px 57px 20px 75px 21px 80px 20px 75px 25px 72px 10px 83px 9px 20px",
  "layout.crm-enrollment-checklist.width": "292px",
  "layout.crm-risk-row.width": "862px",
  "layout.crm-risk-row.columns": "30px 12px 96px 15px 43px 29px 42px 31px 125px 47px 92px 48px 112px 21px 65px 18px 14px",
  "layout.crm-retention-panel.cancellation-width": "397px",
  "layout.crm-retention-panel.reactivation-width": "412px",
  "layout.crm-retention-panel.complaint-width": "398px",
  "layout.crm-support-ticket-panel.width": "390px",
  "layout.crm-internal-ticket-panel.width": "443px",
  "layout.crm-internal-overview.columns": "minmax(0, 325fr) minmax(0, 339fr) minmax(0, 367fr)",
  "layout.crm-internal-overview.card-rows": "198px 212px",
  "layout.crm-internal-overview.card-row-gap": "10px",
  "layout.crm-internal-overview.bottom-columns": "minmax(0, 538fr) minmax(0, 503fr)",
  "layout.crm-internal-overview.gap": "9px",
  "layout.crm-internal-overview.content-padding": "0 20px 28px 67px",
  "layout.crm-internal-overview.drawer-top": "124px",
  "layout.crm-internal-overview.drawer-right": "20px",
  "layout.crm-internal-overview.drawer-bottom": "57px",
  "layout.crm-support-ticket-panel.fact-columns": "24px 104px minmax(0, 1fr)",
  "layout.crm-grant-access-panel.width": "340px",
  "layout.crm-tenant-row.width": "955px",
  "layout.crm-tenant-row.columns": "21px 34px 104px 75px 72px 58px 79px 76px 72px 90px 96px",
  "layout.crm-internal-shell.width": "1080px",
  "layout.crm-internal-shell.card-columns": "repeat(3, 1fr)",
  "layout.crm-tenant-detail-layout.width": "1432px",
  "layout.crm-tenant-detail-layout.columns": "1071px 346px",
  "layout.crm-security-rule-panel.width": "346px",
  "layout.crm-report-filter-bar.width": "795px",
  "layout.crm-page-filter-bar.search-min-width": "224px",
  "layout.crm-page-filter-bar.search-basis": "320px",
  "layout.crm-page-filter-bar.search-max-width": "360px",
  "layout.crm-page-filter-bar.compact-search-min-width": "188px",
  "layout.crm-page-filter-bar.compact-search-basis": "220px",
  "layout.crm-page-filter-bar.compact-search-max-width": "260px",
  "layout.crm-page-filter-bar.compact-filter-width": "84px",
  "layout.crm-page-filter-bar.tight-search-min-width": "252px",
  "layout.crm-page-filter-bar.tight-search-basis": "264px",
  "layout.crm-page-filter-bar.tight-search-max-width": "276px",
  "layout.crm-page-filter-bar.tight-filter-width": "78px",
  "layout.crm-page-filter-bar.tight-wide-filter-width": "108px",
  "layout.crm-page-filter-bar.tight-priority-filter-width": "104px",
  "layout.crm-task-filter-bar.width": "977px",
  "layout.crm-task-filter-bar.search-width": "224px",
  "layout.crm-task-filter-bar.filter-width": "92px",
  "layout.crm-task-filter-bar.origin-width": "96px",
  "layout.crm-task-filter-bar.priority-width": "115px",
  "layout.crm-task-filter-bar.create-width": "106px",
  "layout.crm-task-queue-list.width": "190px",
  "layout.crm-task-queue-list.source-height": "726px",
  "layout.crm-task-queue-list.item-width": "166px",
  "layout.crm-task-table.width": "780px",
  "layout.crm-task-table.height": "727px",
  "layout.crm-work-list-detail.tall-height": "772px",
  "layout.crm-work-list-detail.tall-viewport-offset": "285px",
  "layout.crm-task-table.inner-width": "760px",
  "layout.crm-task-table.columns": "42px 150px 74px 64px 88px 116px 56px 119px 49px",
  "layout.crm-approval-table.title-column": "20%",
  "layout.crm-approval-table.type-column": "12%",
  "layout.crm-approval-table.origin-column": "10%",
  "layout.crm-approval-table.requester-column": "11%",
  "layout.crm-approval-table.risk-column": "8%",
  "layout.crm-approval-table.cost-column": "9%",
  "layout.crm-approval-table.deadline-column": "8%",
  "layout.crm-approval-table.status-column": "11%",
  "layout.crm-approval-table.activity-column": "11%",
  "layout.crm-report-card.width": "493px",
  "layout.crm-report-card.stat-columns": "141px 141px 151px",
  "layout.crm-opportunity-drawer.width": "368px",
  "layout.crm-opportunity-drawer.fact-columns": "24px 188px minmax(0, 1fr)",
  "layout.crm-opportunity-drawer.action-columns": "repeat(2, minmax(0, 1fr))",
  "layout.crm-import-progress-panel.width": "646px",
  "layout.crm-import-progress-panel.columns": "274px repeat(2, 154px)",
  "layout.crm-field-mapping-panel.width": "453px",
  "layout.crm-field-mapping-panel.row-columns": "132px 130px 88px 58px",
  "layout.crm-duplicate-resolver.width": "502px",
  "layout.crm-duplicate-resolver.columns": "164px 18px 164px 96px",
  "layout.crm-permission-state-panel.width": "357px",
  "layout.crm-permission-state-panel.columns": "82px 73px 68px 92px",
  "layout.crm-integration-failed-panel.width": "363px",
  "layout.crm-integration-failed-panel.columns": "36px minmax(0, 1fr) 82px 92px",
  "layout.crm-integration-failed-panel.connected-columns": "36px 104px 158px 22px",
  "layout.crm-plan-blocked-state.width": "269px",
  "layout.crm-quota-blocked-state.width": "423px",
  "layout.crm-empty-shell.stage.width": "1160px",
  "layout.crm-empty-shell.stage.height": "868px",
  "layout.crm-empty-shell.stage.padding-top": "71px",
  "layout.crm-empty-shell.stage.mobile-height": "229px",
  "layout.crm-empty-shell.stage.mobile-padding-top": "23px",
  "layout.crm-empty-shell.stage.mobile-scale": "0.285",
  "layout.crm-empty-shell.window.width": "1092px",
  "layout.crm-empty-shell.window.height": "722px",
  "layout.crm-empty-shell.window.radius": "10px",
  "layout.crm-empty-shell.window.chrome-height": "57px",
  "layout.crm-empty-shell.window.body-height": "665px",
  "layout.crm-empty-shell.sidebar.width": "72px",
  "layout.crm-empty-shell.sidebar.padding-top": "8px",
  "layout.crm-empty-shell.sidebar.padding-bottom": "88px",
  "layout.crm-empty-shell.sidebar.control-offset-x": "-29px",
  "layout.crm-empty-shell.sidebar.nav-offset-y": "35px",
  "layout.crm-empty-shell.sidebar.nav-gap": "13px",
  "layout.crm-empty-shell.sidebar.first-control-gap": "1px",
  "layout.crm-empty-shell.sidebar.late-control-offset-y": "0",
  "layout.crm-empty-shell.sidebar.utility-gap": "12px",
  "layout.crm-empty-shell.sidebar.utility-offset-y": "8px",
  "layout.crm-empty-shell.main.topbar-height": "58px",
  "layout.crm-empty-shell.main.header-height": "43px",
  "layout.crm-empty-shell.topbar.back-left": "119px",
  "layout.crm-empty-shell.topbar.back-top": "3px",
  "layout.crm-empty-shell.topbar.nav-left": "225px",
  "layout.crm-empty-shell.topbar.nav-top": "1px",
  "layout.crm-empty-shell.topbar.nav-gap": "19px",
  "layout.crm-empty-shell.topbar.nav-active-width": "84px",
  "layout.crm-empty-shell.topbar.actions-right": "20px",
  "layout.crm-empty-shell.topbar.actions-top": "3px",
  "layout.crm-empty-shell.topbar.actions-gap": "7px",
  "layout.crm-empty-shell.header.margin-left": "13px",
  "layout.crm-empty-shell.title.offset-y": "-4px",
  "layout.crm-empty-shell.image-79.sidebar.padding-bottom": "28px",
  "layout.crm-empty-shell.image-79.sidebar.nav-offset-y": "13px",
  "layout.crm-empty-shell.image-79.sidebar.nav-gap": "3px",
  "layout.crm-empty-shell.image-79.sidebar.utility-gap": "6px",
  "layout.crm-empty-shell.image-79.sidebar.utility-offset-y": "0",
  "layout.crm-empty-shell.image-79.topbar.nav-left": "211px",
  "layout.crm-empty-shell.image-79.topbar.nav-gap": "3px",
  "layout.crm-empty-shell.image-79.title.offset-y": "-1px",
  "layout.crm-product-shell.main.topbar-height": "72px",
  "layout.crm-product-shell.main.header-height": "56px",
  "layout.crm-product-shell.main.header-spacious-height": "72px",
  "layout.crm-product-shell.main.header-compact-stacked-height": "72px",
  "layout.crm-product-shell.main.header-dashboard-height": "74px",
  "layout.crm-product-shell.main.header-reports-height": "56px",
  "layout.crm-product-shell.main.header-support-height": "69px",
  "layout.crm-product-shell.main.header-internal-overview-height": "71px",
  "layout.crm-product-shell.main.header-stacked-height": "96px",
  "layout.crm-product-shell.main.header-stacked-meta-height": "130px",
  "layout.crm-product-shell.main.header-agents-height": "123px",
  "layout.crm-product-shell.main.header-agents-meta-height": "157px",
  "layout.crm-product-shell.main.header-agents-routines-height": "175px",
  "layout.crm-product-shell.main.header-agents-routine-detail-height": "141px",
  "layout.crm-product-shell.main.header-agents-flow-detail-height": "140px",
  "layout.crm-product-shell.main.header-agents-routines-meta-height": "209px",
  "layout.crm-product-shell.main.header-agents-publish-height": "85px",
  "layout.crm-product-shell.main.header-settings-hub-height": "161px",
  "layout.crm-product-shell.main.header-overview-height": "90px",
  "layout.crm-product-shell.main.header-usage-height": "126px",
  "layout.crm-product-shell.stage.width": "100%",
  "layout.crm-product-shell.stage.height": "auto",
  "layout.crm-product-shell.viewport-gutter": "clamp(8px, 0.7vw, 14px)",
  "layout.crm-product-shell.topbar.back-left": "168px",
  "layout.crm-product-shell.topbar.back-top": "9px",
  "layout.crm-product-shell.topbar.nav-left": "458px",
  "layout.crm-product-shell.topbar.responsive-nav-left": "276px",
  "layout.crm-product-shell.topbar.responsive-nav-gap": "12px",
  "layout.crm-product-shell.topbar.responsive-actions-reserve": "225px",
  "layout.crm-product-shell.topbar.drawer-nav-left": "346px",
  "layout.crm-product-shell.topbar.nav-top": "9px",
  "layout.crm-product-shell.topbar.actions-right": "28px",
  "layout.crm-product-shell.topbar.actions-top": "9px",
  "layout.crm-product-shell.topbar.dashboard-nav-left": "349px",
  "layout.crm-product-shell.topbar.dashboard-nav-top": "18px",
  "layout.crm-product-shell.topbar.dashboard-nav-gap": "37px",
  "layout.crm-product-shell.topbar.dashboard-actions-top": "15px",
  "layout.crm-product-shell.topbar.dashboard-actions-gap": "27px",
  "layout.crm-product-shell.topbar.opportunity-nav-left": "402px",
  "layout.crm-product-shell.topbar-operation-nav-left": "359px",
  "layout.crm-product-shell.topbar-inbox-nav-left": "390px",
  "layout.crm-product-shell.brand-offset-y": "7px",
  "layout.crm-product-shell.dashboard-brand-left": "37px",
  "layout.crm-product-shell.dashboard-brand-top": "0",
  "layout.crm-product-shell.header-dashboard-copy-offset-y": "18px",
  "layout.crm-product-shell.header-reports-margin-left": "40px",
  "layout.crm-product-shell.header-reports-copy-offset-y": "-7px",
  "layout.crm-product-shell.header-reports-copy-gap": "0px",
  "layout.crm-product-shell.header-support-margin-left": "38px",
  "layout.crm-product-shell.header-support-copy-offset-y": "-6px",
  "layout.crm-product-shell.header-support-copy-gap": "6px",
  "layout.crm-product-shell.header-support-title-offset-y": "-4px",
  "layout.crm-product-shell.header-internal-overview-margin-left": "71px",
  "layout.crm-product-shell.header-internal-overview-copy-offset-y": "-4px",
  "layout.crm-product-shell.header-internal-overview-copy-gap": "6px",
  "layout.crm-product-shell.header-internal-overview-actions-offset-y": "20px",
  "layout.crm-product-shell.header-internal-overview-padding-right": "16px",
  "layout.crm-product-shell.header-stacked-copy-offset-y": "14px",
  "layout.crm-product-shell.header-stacked-copy-gap": "8px",
  "layout.crm-product-shell.header-stacked-actions-offset-y": "26px",
  "layout.crm-product-shell.header-agents-copy-offset-y": "31px",
  "layout.crm-product-shell.header-agents-actions-offset-y": "43px",
  "layout.crm-product-shell.header-agents-routines-copy-offset-y": "57px",
  "layout.crm-product-shell.header-agents-routines-actions-offset-y": "69px",
  "layout.crm-product-shell.header-agents-routine-detail-copy-offset-y": "9px",
  "layout.crm-product-shell.header-agents-routine-detail-margin-left": "48px",
  "layout.crm-product-shell.content-agent-routine-padding": "0 28px 28px 49px",
  "layout.crm-product-shell.agent-flow-drawer-width": "395px",
  "layout.crm-product-shell.agent-test-drawer-width": "382px",
  "layout.crm-product-shell.header-agents-publish-copy-offset-y": "0px",
  "layout.crm-product-shell.header-agents-publish-margin-left": "86px",
  "layout.crm-product-shell.content-agent-publish-padding": "0 6px 18px 82px",
  "layout.crm-product-shell.header-settings-hub-copy-offset-y": "36px",
  "layout.crm-product-shell.header-settings-hub-margin-left": "96px",
  "layout.crm-product-shell.content-settings-hub-padding": "0 67px 28px 94px",
  "layout.crm-product-shell.content-settings-permissions-padding": "0 0 28px 42px",
  "layout.crm-product-shell.content-settings-payments-padding": "0 12px 28px 40px",
  "layout.crm-product-shell.settings-payments-header-copy-offset-x": "7px",
  "layout.crm-product-shell.settings-payments-title-offset-y": "8px",
  "layout.crm-product-shell.settings-payments-subtitle-offset-y": "3px",
  "layout.crm-product-shell.settings-payments-actions-left": "374px",
  "layout.crm-product-shell.settings-payments-actions-top": "53px",
  "layout.crm-product-shell.settings-payments-actions-gap": "24px",
  "control.crm-product-shell.settings-payments-action-height": "36px",
  "control.crm-product-shell.settings-payments-action-padding-x": "13px",
  "control.crm-product-shell.settings-payments-action-font-size": "13px",
  "control.crm-settings-payments-methods-height": "245px",
  "control.crm-settings-payments-method-row-height": "144px",
  "control.crm-settings-payments-method-grid-gap": "24px",
  "control.crm-settings-payments-card-padding": "18px",
  "control.crm-settings-payments-method-row-padding": "0 24px",
  "control.crm-settings-payments-method-row-mark-gap": "35px",
  "control.crm-settings-payments-method-row-mark-offset-y": "-34px",
  "control.crm-settings-payments-method-row-body-offset-y": "-8px",
  "control.crm-settings-payments-method-row-description-width": "150px",
  "control.crm-settings-payments-method-row-description-offset-y": "11px",
  "control.crm-settings-payments-taliya-height": "239px",
  "control.crm-settings-payments-workspace-gap": "9px",
  "layout.crm-product-shell.content-settings-agenda-padding": "0 21px 28px 53px",
  "layout.crm-product-shell.settings-agenda-header-copy-offset-x": "11px",
  "layout.crm-product-shell.settings-agenda-title-offset-y": "9px",
  "layout.crm-product-shell.settings-agenda-subtitle-offset-y": "4px",
  "layout.crm-product-shell.settings-agenda-actions-left": "247px",
  "layout.crm-product-shell.settings-agenda-actions-top": "81px",
  "layout.crm-product-shell.settings-agenda-actions-gap": "13px",
  "control.crm-settings-agenda-first-section-height": "266px",
  "control.crm-settings-agenda-second-section-height": "199px",
  "control.crm-settings-agenda-third-section-height": "221px",
  "control.crm-settings-agenda-card-padding": "18px 21px",
  "control.crm-settings-agenda-rows-top": "13px",
  "control.crm-settings-agenda-row-height": "54px",
  "control.crm-settings-agenda-rules-top": "4px",
  "control.crm-settings-agenda-rule-height": "42px",
  "control.crm-settings-agenda-footer-height": "44px",
  "control.crm-settings-agenda-action-height": "31px",
  "control.crm-settings-agenda-action-padding-x": "25px",
  "control.crm-settings-agenda-action-font-size": "12px",
  "control.crm-settings-agenda-add-button-width": "146px",
  "control.crm-settings-agenda-add-button-height": "34px",
  "control.crm-settings-agenda-agent-radius": "14px",
  "control.crm-settings-agenda-agent-header-height": "94px",
  "control.crm-settings-agenda-agent-intro-height": "112px",
  "control.crm-settings-agenda-agent-body-padding-top": "26px",
  "control.crm-settings-agenda-agent-question-offset-y": "84px",
  "control.crm-settings-agenda-agent-question-gap": "2px",
  "control.crm-settings-agenda-agent-composer-offset-y": "38px",
  "layout.crm-settings-agenda-rule-columns": "38px minmax(0, 1fr) 189px 89px",
  "layout.crm-settings-agenda-rule-control-width": "189px",
  "layout.crm-settings-agenda-rule-body-offset-x": "17px",
  "layout.crm-settings-agenda-rule-select-offset-x": "73px",
  "layout.crm-settings-agenda-rule-status-offset-x": "-18px",
  "layout.crm-product-shell.content-settings-notifications-padding": "0 19px 28px 50px",
  "layout.crm-product-shell.settings-notifications-header-copy-offset-x": "6px",
  "layout.crm-product-shell.settings-notifications-actions-left": "351px",
  "layout.crm-product-shell.settings-notifications-actions-top": "44px",
  "layout.crm-product-shell.settings-notifications-actions-gap": "13px",
  "control.crm-settings-notifications-action-height": "31px",
  "control.crm-settings-notifications-action-padding-x": "22px",
  "control.crm-settings-notifications-action-font-size": "12px",
  "control.crm-settings-notifications-workspace-gap": "14px",
  "control.crm-settings-notifications-first-section-height": "293px",
  "control.crm-settings-notifications-second-section-height": "217px",
  "control.crm-settings-notifications-third-section-height": "203px",
  "control.crm-settings-notifications-card-padding": "11px 20px",
  "control.crm-settings-notifications-role-height": "221px",
  "control.crm-settings-notifications-agent-body-padding-top": "29px",
  "control.crm-settings-notifications-agent-question-offset-y": "87px",
  "control.crm-settings-notifications-agent-question-gap": "2px",
  "control.crm-settings-notifications-agent-composer-offset-y": "34px",
  "control.crm-settings-notifications-rule-head-top": "7px",
  "layout.crm-settings-notifications-rule-body-offset-x": "7px",
  "layout.crm-settings-notifications-rule-control-offset-x": "5px",
  "control.crm-billing-subscription-workspace-gap": "20px",
  "layout.crm-product-shell.billing-subscription-header-margin-left": "57px",
  "layout.crm-product-shell.billing-subscription-copy-offset-y": "31px",
  "layout.crm-product-shell.billing-subscription-breadcrumb-offset-x": "4px",
  "layout.crm-product-shell.billing-subscription-actions-left": "404px",
  "layout.crm-product-shell.billing-subscription-actions-top": "91px",
  "layout.crm-product-shell.billing-subscription-actions-gap": "22px",
  "control.crm-billing-subscription-action-height": "42px",
  "control.crm-billing-subscription-action-padding-x": "20px",
  "control.crm-billing-subscription-action-font-size": "12px",
  "type.crm-billing-subscription-title-size": "32px",
  "type.crm-billing-subscription-title-line-height": "38px",
  "layout.crm-billing-subscription-drawer-header-offset-y": "8px",
  "type.crm-billing-subscription-drawer-title-size": "14px",
  "type.crm-billing-subscription-drawer-title-line-height": "20px",
  "layout.crm-billing-subscription-drawer-callout-offset-y": "27px",
  "layout.crm-billing-subscription-drawer-questions-offset-y": "64px",
  "layout.crm-billing-subscription-drawer-composer-offset-y": "-38px",
  "layout.crm-billing-subscription-drawer-footer-offset-y": "-17px",
  "layout.crm-settings-permissions.source-width": "847px",
  "layout.crm-settings-permissions.source-main-offset-y": "34px",
  "layout.crm-settings-permissions.source-header-copy-offset-x": "18px",
  "layout.crm-settings-permissions.source-breadcrumb-offset-y": "4px",
  "layout.crm-settings-permissions.source-title-offset-y": "13px",
  "layout.crm-settings-permissions.source-subtitle-offset-y": "6px",
  "layout.crm-settings-permissions.source-actions-top": "90px",
  "layout.crm-product-shell.header-usage-margin-left": "67px",
  "layout.crm-product-shell.header-usage-copy-offset-y": "40px",
  "layout.crm-product-shell.header-usage-copy-gap": "8px",
  "layout.crm-product-shell.header-usage-actions-left": "352px",
  "layout.crm-product-shell.header-usage-overview-actions-left": "397px",
  "layout.crm-product-shell.header-billing-margin-left": "71px",
  "layout.crm-product-shell.header-billing-actions-left": "396px",
  "layout.crm-product-shell.header-billing-invoices-margin-left": "59px",
  "layout.crm-product-shell.header-billing-invoices-actions-left": "376px",
  "layout.crm-product-shell.header-usage-actions-offset-y": "95px",
  "layout.crm-product-shell.header-usage-breadcrumb-gap": "22px",
  "layout.crm-product-shell.topbar-usage-back-left": "178px",
  "layout.crm-product-shell.topbar-usage-nav-left": "276px",
  "layout.crm-usage-header-summary.columns": "138px 134px 223px",
  "layout.crm-usage-header-summary.overview-columns": "158px 129px 165px",
  "layout.crm-usage-header-summary.billing-columns": "142px 158px 165px",
  "layout.crm-usage-header-summary.billing-invoices-columns": "142px 158px 153px",
  "layout.crm-usage-header-summary.gap": "16px",
  "layout.crm-product-shell.header.margin-left": "50px",
  "layout.crm-product-shell.content.padding": "0 28px 28px 50px",
  "layout.crm-product-shell.content-work-list-padding": "0 28px 28px 27px",
  "layout.crm-product-shell.content-work-list-compact-padding": "0 28px 28px 11px",
  "layout.crm-product-shell.content-work-list-wide-padding": "0 28px 28px 16px",
  "layout.crm-product-shell.content-main-priority-padding": "0 28px 27px 16px",
  "layout.crm-product-shell.content-kanban-padding": "0 28px 28px 24px",
  "layout.crm-product-shell.content-three-pane-padding": "0 39px 28px 20px",
  "layout.crm-product-shell.content-student-profile-padding": "0 28px 28px 24px",
  "layout.crm-product-shell.content-class-operation-padding": "40px 14px 20px 18px",
  "layout.crm-product-shell.content-dashboard-padding": "0 41px 28px 52px",
  "layout.crm-product-shell.content-opportunity-padding": "5px 28px 28px 30px",
  "layout.crm-product-shell.content-support-padding": "0 10px 28px 38px",
  "layout.crm-product-shell.drawer-z-index": "50",
  "control.crm-product-shell.nav-active-height": "44px",
  "control.crm-product-shell.nav-height": "40px",
  "control.crm-product-shell.nav-padding-x": "15px",
  "layout.crm-operational-row.columns": "32px minmax(0, 1fr) auto 20px",
  "layout.crm-operational-row.dense-columns": "32px minmax(0, 1fr) 20px",
  "layout.crm-operational-row.gap": "12px",
  "control.crm-operational-row.height": "60px",
  "control.crm-operational-row.dense-height": "43px",
  "control.crm-operational-row.schedule-dense-height": "41px",
  "control.crm-operational-row.compact-height": "39px",
  "control.crm-operational-row.padding-x": "14px",
  "control.crm-operational-row.icon-size": "32px",
  "control.crm-operational-row.checklist-columns": "14px minmax(0, 1fr) 20px",
  "control.crm-operational-row.checklist-height": "44px",
  "control.crm-operational-row.checklist-leading-size": "14px",
  "control.crm-operational-row.checklist-mark-size": "14px",
  "control.crm-operational-row.content-gap": "3px",
  "control.crm-operational-row.chip-height": "28px",
  "control.crm-operational-row.chip-padding-x": "14px",
  "control.crm-operational-panel.header-height": "26px",
  "control.crm-operational-panel.header-title-size": "15px",
  "control.crm-operational-panel.header-title-line-height": "20px",
  "control.crm-operational-panel.header-chip-size": "11px",
  "control.crm-operational-panel.header-chip-height": "24px",
  "control.crm-operational-panel.rows-margin-top": "11px",
  "control.crm-operational-panel.schedule-dense-rows-margin-top": "4px",
  "type.crm-operational-row-title.size": "13px",
  "type.crm-operational-row-title.line-height": "17px",
  "type.crm-operational-row-meta.size": "12px",
  "type.crm-operational-row-meta.line-height": "15px",
  "type.crm-operational-row-money.size": "15px",
  "layout.crm-browser.traffic.left": "17px",
  "layout.crm-browser.traffic.top": "18px",
  "layout.crm-browser.toolbar.left": "96px",
  "layout.crm-browser.toolbar.top": "17px",
  "layout.crm-browser.address.top": "10px",
  "layout.crm-shell-brand.left": "24px",
  "layout.crm-shell-brand.top": "-4px"
} as const satisfies TokenRecord;
