/* Compatibility facade over stable CRM domain modules. */
export { MessageBubble } from "@taliya/ui";
export { standardPageKitManifest } from "../standard-page-kit.js";
export type { StandardPageKitComponent, StandardPageKitManifest } from "../standard-page-kit.js";
export { crmComponentNames, crmComponentRegistry } from "../component-registry.js";
export type { CrmComponentDefinition, CrmComponentName, CrmPriority } from "../component-registry.js";
export * from "../domains/agenda/index.js";
export * from "../domains/settings/index.js";
export * from "../domains/billing/index.js";
export * from "../domains/students/index.js";
export * from "../patterns/index.js";
export * from "../patterns/shell.js";
export * from "../patterns/worklist-table.js";
export * from "./shell-core.js";
export * from "./shell-report.js";
export * from "./shell-operational.js";
export * from "./filters-types.js";
export * from "./filters-bar.js";
export * from "./filters-quick.js";
export * from "./filters-queue.js";
export * from "./worklist-task-types.js";
export * from "./worklist-task.js";
export * from "./worklist-lead-types.js";
export * from "./worklist-lead.js";
export * from "./worklist-drawer-types.js";
export * from "./worklist-drawer.js";
export * from "./worklist-checklist-types.js";
export * from "./worklist-checklist.js";
export * from "./worklist-approval-types-a.js";
export * from "./worklist-approval-types-b.js";
export * from "./worklist-approval.js";
export * from "./worklist-student-types-a.js";
export * from "./worklist-student-types-b.js";
export * from "./worklist-student.js";
export * from "./worklist-replacement-types.js";
export * from "./worklist-replacement.js";
export * from "./opportunity-types.js";
export * from "./opportunity.js";
export * from "./import-progress.js";
export * from "./import-mapping.js";
export * from "./import-resolution.js";
export * from "./governance-states.js";
export * from "./governance-panels.js";
export * from "./governance-setup.js";
export * from "./reference-core.js";
export * from "./reference-agent.js";
